// Game vocabulary data
// w = word (displayed on card), r = reading, m = English meaning, cat = category
// If w === r (katakana), reading is not shown separately
const gameData = {
  pokemon: {
    label: 'ポケモン',
    diff: 'N5',
    cats: ['すべて', 'ポケモン', 'わざ', 'アイテム', 'バトル', 'じょうたい'],
    vocab: [
      // ── ポケモン ────────────────────────────────────────────────────────
      {w:'フシギダネ',r:'フシギダネ',m:'Bulbasaur',cat:'ポケモン'},
      {w:'フシギソウ',r:'フシギソウ',m:'Ivysaur',cat:'ポケモン'},
      {w:'フシギバナ',r:'フシギバナ',m:'Venusaur',cat:'ポケモン'},
      {w:'ヒトカゲ',r:'ヒトカゲ',m:'Charmander',cat:'ポケモン'},
      {w:'リザード',r:'リザード',m:'Charmeleon',cat:'ポケモン'},
      {w:'リザードン',r:'リザードン',m:'Charizard',cat:'ポケモン'},
      {w:'ゼニガメ',r:'ゼニガメ',m:'Squirtle',cat:'ポケモン'},
      {w:'カメール',r:'カメール',m:'Wartortle',cat:'ポケモン'},
      {w:'カメックス',r:'カメックス',m:'Blastoise',cat:'ポケモン'},
      {w:'キャタピー',r:'キャタピー',m:'Caterpie',cat:'ポケモン'},
      {w:'トランセル',r:'トランセル',m:'Metapod',cat:'ポケモン'},
      {w:'バタフリー',r:'バタフリー',m:'Butterfree',cat:'ポケモン'},
      {w:'ビードル',r:'ビードル',m:'Weedle',cat:'ポケモン'},
      {w:'コクーン',r:'コクーン',m:'Kakuna',cat:'ポケモン'},
      {w:'スピアー',r:'スピアー',m:'Beedrill',cat:'ポケモン'},
      {w:'ポッポ',r:'ポッポ',m:'Pidgey',cat:'ポケモン'},
      {w:'ピジョン',r:'ピジョン',m:'Pidgeotto',cat:'ポケモン'},
      {w:'ピジョット',r:'ピジョット',m:'Pidgeot',cat:'ポケモン'},
      {w:'コラッタ',r:'コラッタ',m:'Rattata',cat:'ポケモン'},
      {w:'ラッタ',r:'ラッタ',m:'Raticate',cat:'ポケモン'},
      {w:'オニスズメ',r:'オニスズメ',m:'Spearow',cat:'ポケモン'},
      {w:'オニドリル',r:'オニドリル',m:'Fearow',cat:'ポケモン'},
      {w:'アーボ',r:'アーボ',m:'Ekans',cat:'ポケモン'},
      {w:'アーボック',r:'アーボック',m:'Arbok',cat:'ポケモン'},
      {w:'ピカチュウ',r:'ピカチュウ',m:'Pikachu',cat:'ポケモン'},
      {w:'ライチュウ',r:'ライチュウ',m:'Raichu',cat:'ポケモン'},
      {w:'サンド',r:'サンド',m:'Sandshrew',cat:'ポケモン'},
      {w:'サンドパン',r:'サンドパン',m:'Sandslash',cat:'ポケモン'},
      {w:'ニドラン♀',r:'ニドラン♀',m:'Nidoran♀',cat:'ポケモン'},
      {w:'ニドリーナ',r:'ニドリーナ',m:'Nidorina',cat:'ポケモン'},
      {w:'ニドクイン',r:'ニドクイン',m:'Nidoqueen',cat:'ポケモン'},
      {w:'ニドラン♂',r:'ニドラン♂',m:'Nidoran♂',cat:'ポケモン'},
      {w:'ニドリーノ',r:'ニドリーノ',m:'Nidorino',cat:'ポケモン'},
      {w:'ニドキング',r:'ニドキング',m:'Nidoking',cat:'ポケモン'},
      {w:'プリン',r:'プリン',m:'Jigglypuff',cat:'ポケモン'},
      {w:'プクリン',r:'プクリン',m:'Wigglytuff',cat:'ポケモン'},
      {w:'ロコン',r:'ロコン',m:'Vulpix',cat:'ポケモン'},
      {w:'キュウコン',r:'キュウコン',m:'Ninetales',cat:'ポケモン'},
      {w:'パラス',r:'パラス',m:'Paras',cat:'ポケモン'},
      {w:'パラセクト',r:'パラセクト',m:'Parasect',cat:'ポケモン'},
      {w:'コンパン',r:'コンパン',m:'Venonat',cat:'ポケモン'},
      {w:'モルフォン',r:'モルフォン',m:'Venomoth',cat:'ポケモン'},
      {w:'ディグダ',r:'ディグダ',m:'Diglett',cat:'ポケモン'},
      {w:'ダグトリオ',r:'ダグトリオ',m:'Dugtrio',cat:'ポケモン'},
      {w:'ニャース',r:'ニャース',m:'Meowth',cat:'ポケモン'},
      {w:'ペルシアン',r:'ペルシアン',m:'Persian',cat:'ポケモン'},
      {w:'コダック',r:'コダック',m:'Psyduck',cat:'ポケモン'},
      {w:'ゴルダック',r:'ゴルダック',m:'Golduck',cat:'ポケモン'},
      {w:'マンキー',r:'マンキー',m:'Mankey',cat:'ポケモン'},
      {w:'オコリザル',r:'オコリザル',m:'Primeape',cat:'ポケモン'},
      {w:'ガーディ',r:'ガーディ',m:'Growlithe',cat:'ポケモン'},
      {w:'ウインディ',r:'ウインディ',m:'Arcanine',cat:'ポケモン'},
      {w:'ニョロモ',r:'ニョロモ',m:'Poliwag',cat:'ポケモン'},
      {w:'ニョロゾ',r:'ニョロゾ',m:'Poliwhirl',cat:'ポケモン'},
      {w:'ニョロボン',r:'ニョロボン',m:'Poliwrath',cat:'ポケモン'},
      {w:'ケーシィ',r:'ケーシィ',m:'Abra',cat:'ポケモン'},
      {w:'ユンゲラー',r:'ユンゲラー',m:'Kadabra',cat:'ポケモン'},
      {w:'フーディン',r:'フーディン',m:'Alakazam',cat:'ポケモン'},
      {w:'ワンリキー',r:'ワンリキー',m:'Machop',cat:'ポケモン'},
      {w:'ゴーリキー',r:'ゴーリキー',m:'Machoke',cat:'ポケモン'},
      {w:'カイリキー',r:'カイリキー',m:'Machamp',cat:'ポケモン'},
      {w:'マダツボミ',r:'マダツボミ',m:'Bellsprout',cat:'ポケモン'},
      {w:'ウツドン',r:'ウツドン',m:'Weepinbell',cat:'ポケモン'},
      {w:'ウツボット',r:'ウツボット',m:'Victreebel',cat:'ポケモン'},
      {w:'メノクラゲ',r:'メノクラゲ',m:'Tentacool',cat:'ポケモン'},
      {w:'ドククラゲ',r:'ドククラゲ',m:'Tentacruel',cat:'ポケモン'},
      {w:'イシツブテ',r:'イシツブテ',m:'Geodude',cat:'ポケモン'},
      {w:'ゴローン',r:'ゴローン',m:'Graveler',cat:'ポケモン'},
      {w:'ゴローニャ',r:'ゴローニャ',m:'Golem',cat:'ポケモン'},
      {w:'ポニータ',r:'ポニータ',m:'Ponyta',cat:'ポケモン'},
      {w:'ギャロップ',r:'ギャロップ',m:'Rapidash',cat:'ポケモン'},
      {w:'ヤドン',r:'ヤドン',m:'Slowpoke',cat:'ポケモン'},
      {w:'ヤドラン',r:'ヤドラン',m:'Slowbro',cat:'ポケモン'},
      {w:'コイル',r:'コイル',m:'Magnemite',cat:'ポケモン'},
      {w:'レアコイル',r:'レアコイル',m:'Magneton',cat:'ポケモン'},
      {w:'ドードー',r:'ドードー',m:'Doduo',cat:'ポケモン'},
      {w:'ドードリオ',r:'ドードリオ',m:'Dodrio',cat:'ポケモン'},
      {w:'パウワウ',r:'パウワウ',m:'Seel',cat:'ポケモン'},
      {w:'ジュゴン',r:'ジュゴン',m:'Dewgong',cat:'ポケモン'},
      {w:'ベトベター',r:'ベトベター',m:'Grimer',cat:'ポケモン'},
      {w:'ベトベトン',r:'ベトベトン',m:'Muk',cat:'ポケモン'},
      {w:'シェルダー',r:'シェルダー',m:'Shellder',cat:'ポケモン'},
      {w:'パルシェン',r:'パルシェン',m:'Cloyster',cat:'ポケモン'},
      {w:'ゴース',r:'ゴース',m:'Gastly',cat:'ポケモン'},
      {w:'ゴースト',r:'ゴースト',m:'Haunter',cat:'ポケモン'},
      {w:'ゲンガー',r:'ゲンガー',m:'Gengar',cat:'ポケモン'},
      {w:'イワーク',r:'イワーク',m:'Onix',cat:'ポケモン'},
      {w:'スリープ',r:'スリープ',m:'Drowzee',cat:'ポケモン'},
      {w:'スリーパー',r:'スリーパー',m:'Hypno',cat:'ポケモン'},
      {w:'クラブ',r:'クラブ',m:'Krabby',cat:'ポケモン'},
      {w:'キングラー',r:'キングラー',m:'Kingler',cat:'ポケモン'},
      {w:'ビリリダマ',r:'ビリリダマ',m:'Voltorb',cat:'ポケモン'},
      {w:'マルマイン',r:'マルマイン',m:'Electrode',cat:'ポケモン'},
      {w:'タマタマ',r:'タマタマ',m:'Exeggcute',cat:'ポケモン'},
      {w:'ナッシー',r:'ナッシー',m:'Exeggutor',cat:'ポケモン'},
      {w:'カラカラ',r:'カラカラ',m:'Cubone',cat:'ポケモン'},
      {w:'ガラガラ',r:'ガラガラ',m:'Marowak',cat:'ポケモン'},
      {w:'ルージュラ',r:'ルージュラ',m:'Jynx',cat:'ポケモン'},
      {w:'エレブー',r:'エレブー',m:'Electabuzz',cat:'ポケモン'},
      {w:'ブーバー',r:'ブーバー',m:'Magmar',cat:'ポケモン'},
      {w:'カイロス',r:'カイロス',m:'Pinsir',cat:'ポケモン'},
      {w:'ケンタロス',r:'ケンタロス',m:'Tauros',cat:'ポケモン'},
      {w:'コイキング',r:'コイキング',m:'Magikarp',cat:'ポケモン'},
      {w:'ギャラドス',r:'ギャラドス',m:'Gyarados',cat:'ポケモン'},
      {w:'ラプラス',r:'ラプラス',m:'Lapras',cat:'ポケモン'},
      {w:'メタモン',r:'メタモン',m:'Ditto',cat:'ポケモン'},
      {w:'イーブイ',r:'イーブイ',m:'Eevee',cat:'ポケモン'},
      {w:'シャワーズ',r:'シャワーズ',m:'Vaporeon',cat:'ポケモン'},
      {w:'サンダース',r:'サンダース',m:'Jolteon',cat:'ポケモン'},
      {w:'ブースター',r:'ブースター',m:'Flareon',cat:'ポケモン'},
      {w:'ポリゴン',r:'ポリゴン',m:'Porygon',cat:'ポケモン'},
      {w:'オムナイト',r:'オムナイト',m:'Omanyte',cat:'ポケモン'},
      {w:'オムスター',r:'オムスター',m:'Omastar',cat:'ポケモン'},
      {w:'カブト',r:'カブト',m:'Kabuto',cat:'ポケモン'},
      {w:'カブトプス',r:'カブトプス',m:'Kabutops',cat:'ポケモン'},
      {w:'プテラ',r:'プテラ',m:'Aerodactyl',cat:'ポケモン'},
      {w:'カビゴン',r:'カビゴン',m:'Snorlax',cat:'ポケモン'},
      {w:'フリーザー',r:'フリーザー',m:'Articuno',cat:'ポケモン'},
      {w:'サンダー',r:'サンダー',m:'Zapdos',cat:'ポケモン'},
      {w:'ファイヤー',r:'ファイヤー',m:'Moltres',cat:'ポケモン'},
      {w:'ミニリュウ',r:'ミニリュウ',m:'Dratini',cat:'ポケモン'},
      {w:'ハクリュー',r:'ハクリュー',m:'Dragonair',cat:'ポケモン'},
      {w:'カイリュー',r:'カイリュー',m:'Dragonite',cat:'ポケモン'},
      {w:'ミュウツー',r:'ミュウツー',m:'Mewtwo',cat:'ポケモン'},
      {w:'ミュウ',r:'ミュウ',m:'Mew',cat:'ポケモン'},
      // ── わざ ────────────────────────────────────────────────────────
      {w:'ひのこ',r:'ひのこ',m:'Ember',cat:'わざ'},
      {w:'かえんほうしゃ',r:'かえんほうしゃ',m:'Flamethrower',cat:'わざ'},
      {w:'みずでっぽう',r:'みずでっぽう',m:'Water Gun',cat:'わざ'},
      {w:'なみのり',r:'なみのり',m:'Surf',cat:'わざ'},
      {w:'かみなり',r:'かみなり',m:'Thunder',cat:'わざ'},
      {w:'10まんボルト',r:'10まんボルト',m:'Thunderbolt',cat:'わざ'},
      {w:'はっぱカッター',r:'はっぱカッター',m:'Razor Leaf',cat:'わざ'},
      {w:'たいあたり',r:'たいあたり',m:'Tackle',cat:'わざ'},
      {w:'ひっかく',r:'ひっかく',m:'Scratch',cat:'わざ'},
      {w:'きりさく',r:'きりさく',m:'Cut',cat:'わざ'},
      {w:'はかいこうせん',r:'はかいこうせん',m:'Hyper Beam',cat:'わざ'},
      {w:'げきりん',r:'げきりん',m:'Outrage',cat:'わざ'},
      {w:'つるぎのまい',r:'つるぎのまい',m:'Sword Dance',cat:'わざ'},
      {w:'あくのはどう',r:'あくのはどう',m:'Dark Pulse',cat:'わざ'},
      {w:'サイコキネシス',r:'サイコキネシス',m:'Psychic',cat:'わざ'},
      {w:'ふぶき',r:'ふぶき',m:'Blizzard',cat:'わざ'},
      {w:'じしん',r:'じしん',m:'Earthquake',cat:'わざ'},
      {w:'いわなだれ',r:'いわなだれ',m:'Rock Slide',cat:'わざ'},
      {w:'ほのおのうず',r:'ほのおのうず',m:'Fire Spin',cat:'わざ'},
      {w:'さいみんじゅつ',r:'さいみんじゅつ',m:'Hypnosis',cat:'わざ'},
      {w:'しびれごな',r:'しびれごな',m:'Stun Spore',cat:'わざ'},
      {w:'どくどく',r:'どくどく',m:'Toxic',cat:'わざ'},
      {w:'かたくなる',r:'かたくなる',m:'Harden',cat:'わざ'},
      {w:'なきごえ',r:'なきごえ',m:'Growl',cat:'わざ'},
      {w:'でんこうせっか',r:'でんこうせっか',m:'Quick Attack',cat:'わざ'},
      {w:'そらをとぶ',r:'そらをとぶ',m:'Fly',cat:'わざ'},
      {w:'ねむる',r:'ねむる',m:'Rest',cat:'わざ'},
      {w:'めざめるパワー',r:'めざめるパワー',m:'Hidden Power',cat:'わざ'},
      {w:'メガドレイン',r:'メガドレイン',m:'Mega Drain',cat:'わざ'},
      {w:'くすぐる',r:'くすぐる',m:'Tickle',cat:'わざ'},
      // ── アイテム ─────────────────────────────────────────────────────
      {w:'モンスターボール',r:'モンスターボール',m:'Poké Ball',cat:'アイテム'},
      {w:'スーパーボール',r:'スーパーボール',m:'Great Ball',cat:'アイテム'},
      {w:'ハイパーボール',r:'ハイパーボール',m:'Ultra Ball',cat:'アイテム'},
      {w:'マスターボール',r:'マスターボール',m:'Master Ball',cat:'アイテム'},
      {w:'きずぐすり',r:'きずぐすり',m:'Potion',cat:'アイテム'},
      {w:'いいきずぐすり',r:'いいきずぐすり',m:'Super Potion',cat:'アイテム'},
      {w:'すごいきずぐすり',r:'すごいきずぐすり',m:'Hyper Potion',cat:'アイテム'},
      {w:'まんたんのくすり',r:'まんたんのくすり',m:'Max Potion',cat:'アイテム'},
      {w:'げんきのかけら',r:'げんきのかけら',m:'Revive',cat:'アイテム'},
      {w:'げんきのかたまり',r:'げんきのかたまり',m:'Max Revive',cat:'アイテム'},
      {w:'どうのみのみ',r:'どうのみのみ',m:'Oran Berry',cat:'アイテム'},
      {w:'ひかりのいし',r:'ひかりのいし',m:'Fire Stone',cat:'アイテム'},
      {w:'かみなりのいし',r:'かみなりのいし',m:'Thunder Stone',cat:'アイテム'},
      {w:'みずのいし',r:'みずのいし',m:'Water Stone',cat:'アイテム'},
      {w:'ぼうぐのこな',r:'ぼうぐのこな',m:'Escape Rope',cat:'アイテム'},
      {w:'むしよけスプレー',r:'むしよけスプレー',m:'Repel',cat:'アイテム'},
      {w:'スーパーじどうじてんしゃ',r:'スーパーじどうじてんしゃ',m:'Bicycle',cat:'アイテム'},
      {w:'なんでもなおし',r:'なんでもなおし',m:'Full Heal',cat:'アイテム'},
      {w:'カスタム',r:'カスタム',m:'TM (Technical Machine)',cat:'アイテム'},
      {w:'ひでんマシン',r:'ひでんマシン',m:'HM (Hidden Machine)',cat:'アイテム'},
      // ── バトル ───────────────────────────────────────────────────────
      {w:'たたかう',r:'たたかう',m:'Fight (battle command)',cat:'バトル'},
      {w:'にげる',r:'にげる',m:'Run (battle command)',cat:'バトル'},
      {w:'ポケモン',r:'ポケモン',m:'Pokémon (switch command)',cat:'バトル'},
      {w:'どうぐ',r:'どうぐ',m:'Bag / Items (battle command)',cat:'バトル'},
      {w:'こうどう',r:'こうどう',m:'Action / turn',cat:'バトル'},
      {w:'ひんし',r:'ひんし',m:'Fainted (KO\'d)',cat:'バトル'},
      {w:'きゅうしょにあたった',r:'きゅうしょにあたった',m:'Critical hit!',cat:'バトル'},
      {w:'こうかはばつぐんだ',r:'こうかはばつぐんだ',m:'It\'s super effective!',cat:'バトル'},
      {w:'こうかはいまひとつだ',r:'こうかはいまひとつだ',m:'It\'s not very effective...',cat:'バトル'},
      {w:'こうかがない',r:'こうかがない',m:'It has no effect.',cat:'バトル'},
      {w:'わざはそれいじょうつかえない',r:'わざはそれいじょうつかえない',m:'The move ran out of PP.',cat:'バトル'},
      // ── じょうたい ───────────────────────────────────────────────────
      {w:'まひ',r:'まひ',m:'Paralysis',cat:'じょうたい'},
      {w:'どく',r:'どく',m:'Poison',cat:'じょうたい'},
      {w:'もうどく',r:'もうどく',m:'Bad Poison',cat:'じょうたい'},
      {w:'やけど',r:'やけど',m:'Burn',cat:'じょうたい'},
      {w:'こおり',r:'こおり',m:'Frozen',cat:'じょうたい'},
      {w:'ねむり',r:'ねむり',m:'Sleep',cat:'じょうたい'},
      {w:'こんらん',r:'こんらん',m:'Confusion',cat:'じょうたい'},
      {w:'ひるみ',r:'ひるみ',m:'Flinch',cat:'じょうたい'},
      {w:'メロメロ',r:'メロメロ',m:'Infatuation (Attract)',cat:'じょうたい'},
    ]
  },

  acnh: {
    label: 'どうぶつの森',
    diff: 'N5–N4',
    cats: ['すべて', '日常', 'どうぐ', 'しぜん', 'むらびと', 'いえ'],
    vocab: [
      // ── 日常 ─────────────────────────────────────────────────────────
      {w:'たぬきち',r:'たぬきち',m:'Tom Nook',cat:'むらびと'},
      {w:'しずえ',r:'しずえ',m:'Isabelle',cat:'むらびと'},
      {w:'もりのくらし',r:'もりのくらし',m:'island life; living in the village',cat:'日常'},
      {w:'まいにちのせいかつ',r:'まいにちのせいかつ',m:'daily life',cat:'日常'},
      {w:'おはなし',r:'おはなし',m:'talking; conversation (polite)',cat:'日常'},
      {w:'ごあいさつ',r:'ごあいさつ',m:'greeting (polite)',cat:'日常'},
      {w:'にっか',r:'にっか',m:'daily schedule; program',cat:'日常'},
      {w:'かいもの',r:'かいもの',m:'shopping',cat:'日常'},
      {w:'かせぐ',r:'かせぐ',m:'to earn (money, miles)',cat:'日常'},
      {w:'ローン',r:'ローン',m:'loan; mortgage',cat:'日常'},
      {w:'かえす',r:'かえす',m:'to pay back; to return',cat:'日常'},
      {w:'マイル',r:'マイル',m:'Nook Miles',cat:'日常'},
      {w:'おいのり',r:'おいのり',m:'prayer; wishing on a star',cat:'日常'},
      {w:'まつり',r:'まつり',m:'festival',cat:'日常'},
      {w:'きねんび',r:'きねんび',m:'anniversary; special day',cat:'日常'},
      // ── どうぐ ───────────────────────────────────────────────────────
      {w:'つりざお',r:'つりざお',m:'fishing rod',cat:'どうぐ'},
      {w:'あみ',r:'あみ',m:'net; bug net',cat:'どうぐ'},
      {w:'スコップ',r:'スコップ',m:'shovel',cat:'どうぐ'},
      {w:'ジョウロ',r:'ジョウロ',m:'watering can',cat:'どうぐ'},
      {w:'おの',r:'おの',m:'axe',cat:'どうぐ'},
      {w:'パチンコ',r:'パチンコ',m:'slingshot',cat:'どうぐ'},
      {w:'はしご',r:'はしご',m:'ladder; stepladder',cat:'どうぐ'},
      {w:'さおだけ',r:'さおだけ',m:'vaulting pole',cat:'どうぐ'},
      {w:'かいちゅうでんとう',r:'かいちゅうでんとう',m:'flashlight; torch',cat:'どうぐ'},
      {w:'スマホ',r:'スマホ',m:'smartphone (NookPhone)',cat:'どうぐ'},
      {w:'きれいなみず',r:'きれいなみず',m:'fresh water; watering',cat:'どうぐ'},
      // ── しぜん ───────────────────────────────────────────────────────
      {w:'さかな',r:'さかな',m:'fish',cat:'しぜん'},
      {w:'むし',r:'むし',m:'bug; insect',cat:'しぜん'},
      {w:'はな',r:'はな',m:'flower',cat:'しぜん'},
      {w:'き',r:'き',m:'tree',cat:'しぜん'},
      {w:'くだもの',r:'くだもの',m:'fruit',cat:'しぜん'},
      {w:'しましまのかぶ',r:'しましまのかぶ',m:'turnip (Stalk Market)',cat:'しぜん'},
      {w:'ほし',r:'ほし',m:'star',cat:'しぜん'},
      {w:'りゅうせい',r:'りゅうせい',m:'shooting star; meteor',cat:'しぜん'},
      {w:'おちば',r:'おちば',m:'fallen leaves',cat:'しぜん'},
      {w:'ゆき',r:'ゆき',m:'snow',cat:'しぜん'},
      {w:'かわ',r:'かわ',m:'river',cat:'しぜん'},
      {w:'うみ',r:'うみ',m:'sea; ocean',cat:'しぜん'},
      {w:'がけ',r:'がけ',m:'cliff',cat:'しぜん'},
      {w:'たきつぼ',r:'たきつぼ',m:'waterfall pool',cat:'しぜん'},
      {w:'かぶ',r:'かぶ',m:'turnip; stock (Stalk Market)',cat:'しぜん'},
      // ── むらびと ─────────────────────────────────────────────────────
      {w:'むらびと',r:'むらびと',m:'villager; island resident',cat:'むらびと'},
      {w:'しまのせいかつ',r:'しまのせいかつ',m:'island life',cat:'むらびと'},
      {w:'あそびにくる',r:'あそびにくる',m:'to come to visit; come hang out',cat:'むらびと'},
      {w:'プレゼント',r:'プレゼント',m:'present; gift',cat:'むらびと'},
      {w:'てがみ',r:'てがみ',m:'letter',cat:'むらびと'},
      {w:'なかよし',r:'なかよし',m:'close friends; getting along well',cat:'むらびと'},
      {w:'ともだちコード',r:'ともだちコード',m:'friend code',cat:'むらびと'},
      // ── いえ ─────────────────────────────────────────────────────────
      {w:'かぐ',r:'かぐ',m:'furniture',cat:'いえ'},
      {w:'かべがみ',r:'かべがみ',m:'wallpaper',cat:'いえ'},
      {w:'ゆか',r:'ゆか',m:'flooring',cat:'いえ'},
      {w:'おへや',r:'おへや',m:'room (polite)',cat:'いえ'},
      {w:'インテリア',r:'インテリア',m:'interior design',cat:'いえ'},
      {w:'テント',r:'テント',m:'tent',cat:'いえ'},
      {w:'いえ',r:'いえ',m:'house; home',cat:'いえ'},
      {w:'かんせい',r:'かんせい',m:'completion; finished',cat:'いえ'},
      {w:'DIY',r:'ディーアイワイ',m:'DIY crafting',cat:'いえ'},
      {w:'レシピ',r:'レシピ',m:'recipe; crafting formula',cat:'いえ'},
    ]
  },

  dq11: {
    label: 'DQ XI',
    diff: 'N4–N3',
    cats: ['すべて', 'バトル', 'じゅもん', 'アイテム', 'ストーリー', 'しょくぎょう'],
    vocab: [
      // ── バトル ───────────────────────────────────────────────────────
      {w:'こうげき',r:'こうげき',m:'attack',cat:'バトル'},
      {w:'ぼうぎょ',r:'ぼうぎょ',m:'defense; defend',cat:'バトル'},
      {w:'とくぎ',r:'とくぎ',m:'special skill; ability',cat:'バトル'},
      {w:'じゅもん',r:'じゅもん',m:'magic spell',cat:'バトル'},
      {w:'どうぐをつかう',r:'どうぐをつかう',m:'use an item',cat:'バトル'},
      {w:'にげる',r:'にげる',m:'flee; run away',cat:'バトル'},
      {w:'MP',r:'エムピー',m:'MP (Magic Points)',cat:'バトル'},
      {w:'HP',r:'エイチピー',m:'HP (Hit Points)',cat:'バトル'},
      {w:'ちから',r:'ちから',m:'strength; power',cat:'バトル'},
      {w:'すばやさ',r:'すばやさ',m:'agility; speed',cat:'バトル'},
      {w:'みのまもり',r:'みのまもり',m:'defense stat; protection',cat:'バトル'},
      {w:'かいふく',r:'かいふく',m:'recovery; healing',cat:'バトル'},
      {w:'せんとう',r:'せんとう',m:'battle; combat',cat:'バトル'},
      {w:'まものつかい',r:'まものつかい',m:'monster tamer',cat:'バトル'},
      {w:'さきどり',r:'さきどり',m:'pre-emptive strike; first move',cat:'バトル'},
      {w:'ランダムエンカウント',r:'ランダムエンカウント',m:'random encounter',cat:'バトル'},
      {w:'いちげきひっさつ',r:'いちげきひっさつ',m:'one-hit kill; instant kill',cat:'バトル'},
      {w:'はんどう',r:'はんどう',m:'recoil; backlash',cat:'バトル'},
      // ── じゅもん ─────────────────────────────────────────────────────
      {w:'ホイミ',r:'ホイミ',m:'Heal (healing spell)',cat:'じゅもん'},
      {w:'ベホイミ',r:'ベホイミ',m:'Midheal (medium healing)',cat:'じゅもん'},
      {w:'ベホマ',r:'ベホマ',m:'Fullheal (full HP recovery)',cat:'じゅもん'},
      {w:'ギラ',r:'ギラ',m:'Sizz (fire spell)',cat:'じゅもん'},
      {w:'メラ',r:'メラ',m:'Frizz (small fire spell)',cat:'じゅもん'},
      {w:'メラゾーマ',r:'メラゾーマ',m:'Kafrizzle (powerful fire)',cat:'じゅもん'},
      {w:'バギ',r:'バギ',m:'Whoosh (wind spell)',cat:'じゅもん'},
      {w:'イオ',r:'イオ',m:'Bang (explosion spell)',cat:'じゅもん'},
      {w:'ヒャド',r:'ヒャド',m:'Crack (ice spell)',cat:'じゅもん'},
      {w:'デイン',r:'デイン',m:'Zap (lightning)',cat:'じゅもん'},
      {w:'ザキ',r:'ザキ',m:'Whack (instant death spell)',cat:'じゅもん'},
      {w:'マホカンタ',r:'マホカンタ',m:'Bounce (magic reflection)',cat:'じゅもん'},
      {w:'スカラ',r:'スカラ',m:'Buff (defense boost spell)',cat:'じゅもん'},
      {w:'ルーラ',r:'ルーラ',m:'Zoom (teleport to towns)',cat:'じゅもん'},
      {w:'リレミト',r:'リレミト',m:'Evac (escape dungeon)',cat:'じゅもん'},
      // ── アイテム ─────────────────────────────────────────────────────
      {w:'やくそう',r:'やくそう',m:'medicinal herb (small heal)',cat:'アイテム'},
      {w:'どくけしそう',r:'どくけしそう',m:'antidote herb (cures poison)',cat:'アイテム'},
      {w:'まんどらごら',r:'まんどらごら',m:'mandrake (removes sleep)',cat:'アイテム'},
      {w:'せいすい',r:'せいすい',m:'holy water (repels monsters)',cat:'アイテム'},
      {w:'かがみのたて',r:'かがみのたて',m:'mirror shield (reflects magic)',cat:'アイテム'},
      {w:'てんくうのつるぎ',r:'てんくうのつるぎ',m:'Sword of Light',cat:'アイテム'},
      {w:'おうじゃのけん',r:'おうじゃのけん',m:'king\'s sword',cat:'アイテム'},
      {w:'まほうのせいすい',r:'まほうのせいすい',m:'magic water (restores MP)',cat:'アイテム'},
      {w:'エルフののみぐすり',r:'エルフののみぐすり',m:'elf elixir (restores MP)',cat:'アイテム'},
      {w:'げんきのもと',r:'げんきのもと',m:'revive herb (revives ally)',cat:'アイテム'},
      {w:'きのみ',r:'きのみ',m:'nut; seed item',cat:'アイテム'},
      {w:'ルーンスタッフ',r:'ルーンスタッフ',m:'rune staff',cat:'アイテム'},
      {w:'しんぴのよろい',r:'しんぴのよろい',m:'mysterious armor',cat:'アイテム'},
      // ── ストーリー ───────────────────────────────────────────────────
      {w:'えいゆう',r:'えいゆう',m:'hero; champion',cat:'ストーリー'},
      {w:'よげん',r:'よげん',m:'prophecy; prediction',cat:'ストーリー'},
      {w:'めいかい',r:'めいかい',m:'the underworld; realm of the dead',cat:'ストーリー'},
      {w:'しれん',r:'しれん',m:'trial; ordeal',cat:'ストーリー'},
      {w:'くらやみ',r:'くらやみ',m:'darkness',cat:'ストーリー'},
      {w:'ひかり',r:'ひかり',m:'light',cat:'ストーリー'},
      {w:'ほのお',r:'ほのお',m:'flame; fire',cat:'ストーリー'},
      {w:'まおう',r:'まおう',m:'Demon King; Dark Lord',cat:'ストーリー'},
      {w:'なかま',r:'なかま',m:'companion; party member',cat:'ストーリー'},
      {w:'おうこく',r:'おうこく',m:'kingdom',cat:'ストーリー'},
      {w:'たび',r:'たび',m:'journey; trip; travel',cat:'ストーリー'},
      {w:'ぼうけん',r:'ぼうけん',m:'adventure',cat:'ストーリー'},
      {w:'たんけん',r:'たんけん',m:'exploration; expedition',cat:'ストーリー'},
      {w:'しんじる',r:'しんじる',m:'to believe; to trust',cat:'ストーリー'},
      {w:'まもる',r:'まもる',m:'to protect; to defend; to guard',cat:'ストーリー'},
      {w:'やくそく',r:'やくそく',m:'promise',cat:'ストーリー'},
      {w:'きぼう',r:'きぼう',m:'hope; wish',cat:'ストーリー'},
      {w:'ぜつぼう',r:'ぜつぼう',m:'despair; hopelessness',cat:'ストーリー'},
      {w:'せんめつ',r:'せんめつ',m:'annihilation; extermination',cat:'ストーリー'},
      {w:'さだめ',r:'さだめ',m:'fate; destiny',cat:'ストーリー'},
      // ── しょくぎょう ─────────────────────────────────────────────────
      {w:'ゆうしゃ',r:'ゆうしゃ',m:'brave hero',cat:'しょくぎょう'},
      {w:'けんし',r:'けんし',m:'swordsman',cat:'しょくぎょう'},
      {w:'まほうつかい',r:'まほうつかい',m:'mage; wizard; spell caster',cat:'しょくぎょう'},
      {w:'そうりょ',r:'そうりょ',m:'priest; cleric',cat:'しょくぎょう'},
      {w:'たんていか',r:'たんていか',m:'scout; detective (thief class)',cat:'しょくぎょう'},
      {w:'バトルマスター',r:'バトルマスター',m:'battle master (fighter class)',cat:'しょくぎょう'},
      {w:'りょうし',r:'りょうし',m:'hunter; ranger',cat:'しょくぎょう'},
      {w:'ブーメラン',r:'ブーメラン',m:'boomerang (weapon type)',cat:'しょくぎょう'},
    ]
  }
};
