// Game vocabulary data
// w = word (displayed on card), r = reading, m = English meaning, cat = category
// If w === r (katakana), reading is not shown separately
const gameData = {
  pokemon: {
    label: 'ポケモン',
    diff: 'N5',
    cats: ['すべて', 'ポケモン', 'わざ', 'アイテム', 'バトル', 'じょうたい', 'セリフ'],
    vocab: [
      // ── ポケモン ────────────────────────────────────────────────────────
      {w:'フシギダネ',r:'フシギダネ',m:'Bulbasaur',cat:'ポケモン'},
      {w:'フシギソウ',r:'フシギソウ',m:'Ivysaur',cat:'ポケモン'},
      {w:'フシギバナ',r:'フシギバナ',m:'Venusaur',cat:'ポケモン'},
      {w:'ヒトカゲ',r:'ヒトカゲ',m:'Charmander',cat:'ポケモン'},
      {w:'リザード',r:'リザード',m:'Charmeleon',cat:'ポケモン'},
      {w:'リザードン',r:'リザードン',m:'Charizard',cat:'ポケモン'},
      {w:'ゼニガメ',r:'ゼニガメ',m:'Squirtle',cat:'ポケモン'},
      {w:'カメール',r:'カメール',m:'Wartortle',cat:'ポケモン'},
      {w:'カメックス',r:'カメックス',m:'Blastoise',cat:'ポケモン'},
      {w:'キャタピー',r:'キャタピー',m:'Caterpie',cat:'ポケモン'},
      {w:'トランセル',r:'トランセル',m:'Metapod',cat:'ポケモン'},
      {w:'バタフリー',r:'バタフリー',m:'Butterfree',cat:'ポケモン'},
      {w:'ビードル',r:'ビードル',m:'Weedle',cat:'ポケモン'},
      {w:'コクーン',r:'コクーン',m:'Kakuna',cat:'ポケモン'},
      {w:'スピアー',r:'スピアー',m:'Beedrill',cat:'ポケモン'},
      {w:'ポッポ',r:'ポッポ',m:'Pidgey',cat:'ポケモン'},
      {w:'ピジョン',r:'ピジョン',m:'Pidgeotto',cat:'ポケモン'},
      {w:'ピジョット',r:'ピジョット',m:'Pidgeot',cat:'ポケモン'},
      {w:'コラッタ',r:'コラッタ',m:'Rattata',cat:'ポケモン'},
      {w:'ラッタ',r:'ラッタ',m:'Raticate',cat:'ポケモン'},
      {w:'オニスズメ',r:'オニスズメ',m:'Spearow',cat:'ポケモン'},
      {w:'オニドリル',r:'オニドリル',m:'Fearow',cat:'ポケモン'},
      {w:'アーボ',r:'アーボ',m:'Ekans',cat:'ポケモン'},
      {w:'アーボック',r:'アーボック',m:'Arbok',cat:'ポケモン'},
      {w:'ピカチュウ',r:'ピカチュウ',m:'Pikachu',cat:'ポケモン'},
      {w:'ライチュウ',r:'ライチュウ',m:'Raichu',cat:'ポケモン'},
      {w:'サンド',r:'サンド',m:'Sandshrew',cat:'ポケモン'},
      {w:'サンドパン',r:'サンドパン',m:'Sandslash',cat:'ポケモン'},
      {w:'ニドラン♀',r:'ニドラン♀',m:'Nidoran♀',cat:'ポケモン'},
      {w:'ニドリーナ',r:'ニドリーナ',m:'Nidorina',cat:'ポケモン'},
      {w:'ニドクイン',r:'ニドクイン',m:'Nidoqueen',cat:'ポケモン'},
      {w:'ニドラン♂',r:'ニドラン♂',m:'Nidoran♂',cat:'ポケモン'},
      {w:'ニドリーノ',r:'ニドリーノ',m:'Nidorino',cat:'ポケモン'},
      {w:'ニドキング',r:'ニドキング',m:'Nidoking',cat:'ポケモン'},
      {w:'プリン',r:'プリン',m:'Jigglypuff',cat:'ポケモン'},
      {w:'プクリン',r:'プクリン',m:'Wigglytuff',cat:'ポケモン'},
      {w:'ロコン',r:'ロコン',m:'Vulpix',cat:'ポケモン'},
      {w:'キュウコン',r:'キュウコン',m:'Ninetales',cat:'ポケモン'},
      {w:'パラス',r:'パラス',m:'Paras',cat:'ポケモン'},
      {w:'パラセクト',r:'パラセクト',m:'Parasect',cat:'ポケモン'},
      {w:'コンパン',r:'コンパン',m:'Venonat',cat:'ポケモン'},
      {w:'モルフォン',r:'モルフォン',m:'Venomoth',cat:'ポケモン'},
      {w:'ディグダ',r:'ディグダ',m:'Diglett',cat:'ポケモン'},
      {w:'ダグトリオ',r:'ダグトリオ',m:'Dugtrio',cat:'ポケモン'},
      {w:'ニャース',r:'ニャース',m:'Meowth',cat:'ポケモン'},
      {w:'ペルシアン',r:'ペルシアン',m:'Persian',cat:'ポケモン'},
      {w:'コダック',r:'コダック',m:'Psyduck',cat:'ポケモン'},
      {w:'ゴルダック',r:'ゴルダック',m:'Golduck',cat:'ポケモン'},
      {w:'マンキー',r:'マンキー',m:'Mankey',cat:'ポケモン'},
      {w:'オコリザル',r:'オコリザル',m:'Primeape',cat:'ポケモン'},
      {w:'ガーディ',r:'ガーディ',m:'Growlithe',cat:'ポケモン'},
      {w:'ウインディ',r:'ウインディ',m:'Arcanine',cat:'ポケモン'},
      {w:'ニョロモ',r:'ニョロモ',m:'Poliwag',cat:'ポケモン'},
      {w:'ニョロゾ',r:'ニョロゾ',m:'Poliwhirl',cat:'ポケモン'},
      {w:'ニョロボン',r:'ニョロボン',m:'Poliwrath',cat:'ポケモン'},
      {w:'ケーシィ',r:'ケーシィ',m:'Abra',cat:'ポケモン'},
      {w:'ユンゲラー',r:'ユンゲラー',m:'Kadabra',cat:'ポケモン'},
      {w:'フーディン',r:'フーディン',m:'Alakazam',cat:'ポケモン'},
      {w:'ワンリキー',r:'ワンリキー',m:'Machop',cat:'ポケモン'},
      {w:'ゴーリキー',r:'ゴーリキー',m:'Machoke',cat:'ポケモン'},
      {w:'カイリキー',r:'カイリキー',m:'Machamp',cat:'ポケモン'},
      {w:'マダツボミ',r:'マダツボミ',m:'Bellsprout',cat:'ポケモン'},
      {w:'ウツドン',r:'ウツドン',m:'Weepinbell',cat:'ポケモン'},
      {w:'ウツボット',r:'ウツボット',m:'Victreebel',cat:'ポケモン'},
      {w:'メノクラゲ',r:'メノクラゲ',m:'Tentacool',cat:'ポケモン'},
      {w:'ドククラゲ',r:'ドククラゲ',m:'Tentacruel',cat:'ポケモン'},
      {w:'イシツブテ',r:'イシツブテ',m:'Geodude',cat:'ポケモン'},
      {w:'ゴローン',r:'ゴローン',m:'Graveler',cat:'ポケモン'},
      {w:'ゴローニャ',r:'ゴローニャ',m:'Golem',cat:'ポケモン'},
      {w:'ポニータ',r:'ポニータ',m:'Ponyta',cat:'ポケモン'},
      {w:'ギャロップ',r:'ギャロップ',m:'Rapidash',cat:'ポケモン'},
      {w:'ヤドン',r:'ヤドン',m:'Slowpoke',cat:'ポケモン'},
      {w:'ヤドラン',r:'ヤドラン',m:'Slowbro',cat:'ポケモン'},
      {w:'コイル',r:'コイル',m:'Magnemite',cat:'ポケモン'},
      {w:'レアコイル',r:'レアコイル',m:'Magneton',cat:'ポケモン'},
      {w:'ドードー',r:'ドードー',m:'Doduo',cat:'ポケモン'},
      {w:'ドードリオ',r:'ドードリオ',m:'Dodrio',cat:'ポケモン'},
      {w:'パウワウ',r:'パウワウ',m:'Seel',cat:'ポケモン'},
      {w:'ジュゴン',r:'ジュゴン',m:'Dewgong',cat:'ポケモン'},
      {w:'ベトベター',r:'ベトベター',m:'Grimer',cat:'ポケモン'},
      {w:'ベトベトン',r:'ベトベトン',m:'Muk',cat:'ポケモン'},
      {w:'シェルダー',r:'シェルダー',m:'Shellder',cat:'ポケモン'},
      {w:'パルシェン',r:'パルシェン',m:'Cloyster',cat:'ポケモン'},
      {w:'ゴース',r:'ゴース',m:'Gastly',cat:'ポケモン'},
      {w:'ゴースト',r:'ゴースト',m:'Haunter',cat:'ポケモン'},
      {w:'ゲンガー',r:'ゲンガー',m:'Gengar',cat:'ポケモン'},
      {w:'イワーク',r:'イワーク',m:'Onix',cat:'ポケモン'},
      {w:'スリープ',r:'スリープ',m:'Drowzee',cat:'ポケモン'},
      {w:'スリーパー',r:'スリーパー',m:'Hypno',cat:'ポケモン'},
      {w:'クラブ',r:'クラブ',m:'Krabby',cat:'ポケモン'},
      {w:'キングラー',r:'キングラー',m:'Kingler',cat:'ポケモン'},
      {w:'ビリリダマ',r:'ビリリダマ',m:'Voltorb',cat:'ポケモン'},
      {w:'マルマイン',r:'マルマイン',m:'Electrode',cat:'ポケモン'},
      {w:'タマタマ',r:'タマタマ',m:'Exeggcute',cat:'ポケモン'},
      {w:'ナッシー',r:'ナッシー',m:'Exeggutor',cat:'ポケモン'},
      {w:'カラカラ',r:'カラカラ',m:'Cubone',cat:'ポケモン'},
      {w:'ガラガラ',r:'ガラガラ',m:'Marowak',cat:'ポケモン'},
      {w:'ルージュラ',r:'ルージュラ',m:'Jynx',cat:'ポケモン'},
      {w:'エレブー',r:'エレブー',m:'Electabuzz',cat:'ポケモン'},
      {w:'ブーバー',r:'ブーバー',m:'Magmar',cat:'ポケモン'},
      {w:'カイロス',r:'カイロス',m:'Pinsir',cat:'ポケモン'},
      {w:'ケンタロス',r:'ケンタロス',m:'Tauros',cat:'ポケモン'},
      {w:'コイキング',r:'コイキング',m:'Magikarp',cat:'ポケモン'},
      {w:'ギャラドス',r:'ギャラドス',m:'Gyarados',cat:'ポケモン'},
      {w:'ラプラス',r:'ラプラス',m:'Lapras',cat:'ポケモン'},
      {w:'メタモン',r:'メタモン',m:'Ditto',cat:'ポケモン'},
      {w:'イーブイ',r:'イーブイ',m:'Eevee',cat:'ポケモン'},
      {w:'シャワーズ',r:'シャワーズ',m:'Vaporeon',cat:'ポケモン'},
      {w:'サンダース',r:'サンダース',m:'Jolteon',cat:'ポケモン'},
      {w:'ブースター',r:'ブースター',m:'Flareon',cat:'ポケモン'},
      {w:'ポリゴン',r:'ポリゴン',m:'Porygon',cat:'ポケモン'},
      {w:'オムナイト',r:'オムナイト',m:'Omanyte',cat:'ポケモン'},
      {w:'オムスター',r:'オムスター',m:'Omastar',cat:'ポケモン'},
      {w:'カブト',r:'カブト',m:'Kabuto',cat:'ポケモン'},
      {w:'カブトプス',r:'カブトプス',m:'Kabutops',cat:'ポケモン'},
      {w:'プテラ',r:'プテラ',m:'Aerodactyl',cat:'ポケモン'},
      {w:'カビゴン',r:'カビゴン',m:'Snorlax',cat:'ポケモン'},
      {w:'フリーザー',r:'フリーザー',m:'Articuno',cat:'ポケモン'},
      {w:'サンダー',r:'サンダー',m:'Zapdos',cat:'ポケモン'},
      {w:'ファイヤー',r:'ファイヤー',m:'Moltres',cat:'ポケモン'},
      {w:'ミニリュウ',r:'ミニリュウ',m:'Dratini',cat:'ポケモン'},
      {w:'ハクリュー',r:'ハクリュー',m:'Dragonair',cat:'ポケモン'},
      {w:'カイリュー',r:'カイリュー',m:'Dragonite',cat:'ポケモン'},
      {w:'ミュウツー',r:'ミュウツー',m:'Mewtwo',cat:'ポケモン'},
      {w:'ミュウ',r:'ミュウ',m:'Mew',cat:'ポケモン'},
      // ── わざ ────────────────────────────────────────────────────────
      {w:'ひのこ',r:'ひのこ',m:'Ember',cat:'わざ'},
      {w:'かえんほうしゃ',r:'かえんほうしゃ',m:'Flamethrower',cat:'わざ'},
      {w:'みずでっぽう',r:'みずでっぽう',m:'Water Gun',cat:'わざ'},
      {w:'なみのり',r:'なみのり',m:'Surf',cat:'わざ'},
      {w:'かみなり',r:'かみなり',m:'Thunder',cat:'わざ'},
      {w:'10まんボルト',r:'10まんボルト',m:'Thunderbolt',cat:'わざ'},
      {w:'はっぱカッター',r:'はっぱカッター',m:'Razor Leaf',cat:'わざ'},
      {w:'たいあたり',r:'たいあたり',m:'Tackle',cat:'わざ'},
      {w:'ひっかく',r:'ひっかく',m:'Scratch',cat:'わざ'},
      {w:'きりさく',r:'きりさく',m:'Cut',cat:'わざ'},
      {w:'はかいこうせん',r:'はかいこうせん',m:'Hyper Beam',cat:'わざ'},
      {w:'げきりん',r:'げきりん',m:'Outrage',cat:'わざ'},
      {w:'つるぎのまい',r:'つるぎのまい',m:'Sword Dance',cat:'わざ'},
      {w:'あくのはどう',r:'あくのはどう',m:'Dark Pulse',cat:'わざ'},
      {w:'サイコキネシス',r:'サイコキネシス',m:'Psychic',cat:'わざ'},
      {w:'ふぶき',r:'ふぶき',m:'Blizzard',cat:'わざ'},
      {w:'じしん',r:'じしん',m:'Earthquake',cat:'わざ'},
      {w:'いわなだれ',r:'いわなだれ',m:'Rock Slide',cat:'わざ'},
      {w:'ほのおのうず',r:'ほのおのうず',m:'Fire Spin',cat:'わざ'},
      {w:'さいみんじゅつ',r:'さいみんじゅつ',m:'Hypnosis',cat:'わざ'},
      {w:'しびれごな',r:'しびれごな',m:'Stun Spore',cat:'わざ'},
      {w:'どくどく',r:'どくどく',m:'Toxic',cat:'わざ'},
      {w:'かたくなる',r:'かたくなる',m:'Harden',cat:'わざ'},
      {w:'なきごえ',r:'なきごえ',m:'Growl',cat:'わざ'},
      {w:'でんこうせっか',r:'でんこうせっか',m:'Quick Attack',cat:'わざ'},
      {w:'そらをとぶ',r:'そらをとぶ',m:'Fly',cat:'わざ'},
      {w:'ねむる',r:'ねむる',m:'Rest',cat:'わざ'},
      {w:'めざめるパワー',r:'めざめるパワー',m:'Hidden Power',cat:'わざ'},
      {w:'メガドレイン',r:'メガドレイン',m:'Mega Drain',cat:'わざ'},
      {w:'くすぐる',r:'くすぐる',m:'Tickle',cat:'わざ'},
      // ── アイテム ─────────────────────────────────────────────────────
      {w:'モンスターボール',r:'モンスターボール',m:'Poké Ball',cat:'アイテム'},
      {w:'スーパーボール',r:'スーパーボール',m:'Great Ball',cat:'アイテム'},
      {w:'ハイパーボール',r:'ハイパーボール',m:'Ultra Ball',cat:'アイテム'},
      {w:'マスターボール',r:'マスターボール',m:'Master Ball',cat:'アイテム'},
      {w:'きずぐすり',r:'きずぐすり',m:'Potion',cat:'アイテム'},
      {w:'いいきずぐすり',r:'いいきずぐすり',m:'Super Potion',cat:'アイテム'},
      {w:'すごいきずぐすり',r:'すごいきずぐすり',m:'Hyper Potion',cat:'アイテム'},
      {w:'まんたんのくすり',r:'まんたんのくすり',m:'Max Potion',cat:'アイテム'},
      {w:'げんきのかけら',r:'げんきのかけら',m:'Revive',cat:'アイテム'},
      {w:'げんきのかたまり',r:'げんきのかたまり',m:'Max Revive',cat:'アイテム'},
      {w:'どうのみのみ',r:'どうのみのみ',m:'Oran Berry',cat:'アイテム'},
      {w:'ひかりのいし',r:'ひかりのいし',m:'Fire Stone',cat:'アイテム'},
      {w:'かみなりのいし',r:'かみなりのいし',m:'Thunder Stone',cat:'アイテム'},
      {w:'みずのいし',r:'みずのいし',m:'Water Stone',cat:'アイテム'},
      {w:'ぼうぐのこな',r:'ぼうぐのこな',m:'Escape Rope',cat:'アイテム'},
      {w:'むしよけスプレー',r:'むしよけスプレー',m:'Repel',cat:'アイテム'},
      {w:'スーパーじどうじてんしゃ',r:'スーパーじどうじてんしゃ',m:'Bicycle',cat:'アイテム'},
      {w:'なんでもなおし',r:'なんでもなおし',m:'Full Heal',cat:'アイテム'},
      {w:'カスタム',r:'カスタム',m:'TM (Technical Machine)',cat:'アイテム'},
      {w:'ひでんマシン',r:'ひでんマシン',m:'HM (Hidden Machine)',cat:'アイテム'},
      // ── バトル ───────────────────────────────────────────────────────
      {w:'たたかう',r:'たたかう',m:'Fight (battle command)',cat:'バトル'},
      {w:'にげる',r:'にげる',m:'Run (battle command)',cat:'バトル'},
      {w:'ポケモン',r:'ポケモン',m:'Pokémon (switch command)',cat:'バトル'},
      {w:'どうぐ',r:'どうぐ',m:'Bag / Items (battle command)',cat:'バトル'},
      {w:'こうどう',r:'こうどう',m:'Action / turn',cat:'バトル'},
      {w:'ひんし',r:'ひんし',m:'Fainted (KO\'d)',cat:'バトル'},
      {w:'きゅうしょにあたった',r:'きゅうしょにあたった',m:'Critical hit!',cat:'バトル'},
      {w:'こうかはばつぐんだ',r:'こうかはばつぐんだ',m:'It\'s super effective!',cat:'バトル'},
      {w:'こうかはいまひとつだ',r:'こうかはいまひとつだ',m:'It\'s not very effective...',cat:'バトル'},
      {w:'こうかがない',r:'こうかがない',m:'It has no effect.',cat:'バトル'},
      {w:'わざはそれいじょうつかえない',r:'わざはそれいじょうつかえない',m:'The move ran out of PP.',cat:'バトル'},
      // ── じょうたい ───────────────────────────────────────────────────
      {w:'まひ',r:'まひ',m:'Paralysis',cat:'じょうたい'},
      {w:'どく',r:'どく',m:'Poison',cat:'じょうたい'},
      {w:'もうどく',r:'もうどく',m:'Bad Poison',cat:'じょうたい'},
      {w:'やけど',r:'やけど',m:'Burn',cat:'じょうたい'},
      {w:'こおり',r:'こおり',m:'Frozen',cat:'じょうたい'},
      {w:'ねむり',r:'ねむり',m:'Sleep',cat:'じょうたい'},
      {w:'こんらん',r:'こんらん',m:'Confusion',cat:'じょうたい'},
      {w:'ひるみ',r:'ひるみ',m:'Flinch',cat:'じょうたい'},
      {w:'メロメロ',r:'メロメロ',m:'Infatuation (Attract)',cat:'じょうたい'},
    ],
    dialogues: [
      // ── オーキド博士 ──────────────────────────────────────────────────
      {
        s:'この世界には、ポケモンと呼ばれる生き物が住んでいる！ある者はペットとして、ある者はたたかいの道具として…わしにとっては研究の対象じゃ！',
        r:'このせかいには、ポケモンとよばれるいきものがすんでいる！あるものはペットとして、あるものはたたかいのどうぐとして…わしにとってはけんきゅうのたいしょうじゃ！',
        sp:'オーキド博士',
        a:'In this world, there are creatures called Pokémon! For some they are pets, for others tools for battle… to me they are subjects of research!',
        c:[
          'In this world, there are creatures called Pokémon! For some they are pets, for others tools for battle… to me they are subjects of research!',
          'In this world, Pokémon are rare. Most people have never encountered one in the wild.',
          'Pokémon are dangerous creatures. Only trained researchers should approach them.',
          'This world is divided between those who love Pokémon and those who fear them.',
        ],
        e:'〜と呼ばれる = called ~ (passive of 呼ぶ). ある者は〜として = "for some, ~ is used as ~". 〜にとっては = "as far as ~ is concerned; to ~"',
      },
      {
        s:'わしの夢はすべてのポケモンを図鑑に記録することじゃ。おぬしに、わしの夢の続きをたくしたいのじゃ。',
        r:'わしのゆめはすべてのポケモンをずかんにきろくすることじゃ。おぬしに、わしのゆめのつづきをたくしたいのじゃ。',
        sp:'オーキド博士',
        a:'My dream is to record all Pokémon in the Pokédex. I want to entrust the continuation of my dream to you.',
        c:[
          'My dream is to record all Pokémon in the Pokédex. I want to entrust the continuation of my dream to you.',
          'I once dreamed of catching all Pokémon, but the task proved impossible.',
          'My dream is for trainers and Pokémon to live in peace. That is all I ask of you.',
          'The Pokédex project is complete. Every Pokémon has been recorded already.',
        ],
        e:'夢は〜することじゃ = "My dream is to ~" (こと nominalises the verb). 続き = continuation. たくしたい = want to entrust / leave in someone\'s care',
      },
      // ── ポケモンセンター ──────────────────────────────────────────────
      {
        s:'いらっしゃいませ！ポケモンセンターへようこそ。ポケモンをお預かりして、回復させていただきますね。',
        r:'いらっしゃいませ！ポケモンセンターへようこそ。ポケモンをおあずかりして、かいふくさせていただきますね。',
        sp:'ジョーイ',
        a:'Welcome! Welcome to the Pokémon Center. We will take care of your Pokémon and restore them to full health.',
        c:[
          'Welcome! Welcome to the Pokémon Center. We will take care of your Pokémon and restore them to full health.',
          'The Pokémon Center is full today. Please come back tomorrow.',
          'We only treat injured Pokémon here. Healthy Pokémon must go to the lab.',
          'You need a membership card to use this Pokémon Center.',
        ],
        e:'いらっしゃいませ = polite "welcome" (shop/service greeting). お預かりする = to take care of / hold for someone (humble 預かる). 〜させていただく = humble "allow me to ~"',
      },
      {
        s:'お待たせしました！ポケモンたちは完全に元気になりましたよ！またお越しくださいね。',
        r:'おまたせしました！ポケモンたちはかんぜんにげんきになりましたよ！またおこしくださいね。',
        sp:'ジョーイ',
        a:'Sorry to keep you waiting! Your Pokémon are all back to full health! Please come again.',
        c:[
          'Sorry to keep you waiting! Your Pokémon are all back to full health! Please come again.',
          'Treatment was only partial. Some of your Pokémon still need rest.',
          'Your Pokémon recovered, but one seems unhappy. Please check on it.',
          'We ran out of medicine. Your Pokémon\'s HP is only partially restored.',
        ],
        e:'お待たせしました = "Sorry to keep you waiting" (set service phrase). 完全に元気になる = to fully recover. またお越しください = "please come again" (polite invitation)',
      },
      // ── 道ばたのNPC ───────────────────────────────────────────────────
      {
        s:'草むらには野生のポケモンが住んでいるよ。ポケモンなしで入ると危ないから気をつけてね！',
        r:'くさむらにはやせいのポケモンがすんでいるよ。ポケモンなしではいるとあぶないからきをつけてね！',
        sp:'村人',
        a:'Wild Pokémon live in the tall grass. It\'s dangerous to enter without Pokémon, so be careful!',
        c:[
          'Wild Pokémon live in the tall grass. It\'s dangerous to enter without Pokémon, so be careful!',
          'The tall grass is perfectly safe. Wild Pokémon are very friendly.',
          'Wild Pokémon avoid humans. You can walk through the grass without worries.',
          'There are no Pokémon in this area — the grass is just overgrown.',
        ],
        e:'野生の = wild (野生 = wild/untamed). 〜なしで = without ~. 〜と危ない = if ~ it\'s dangerous (と = inevitable result conditional). 気をつけて = be careful (set phrase)',
      },
      {
        s:'このバッジを持っていれば、交換で手に入れたポケモンも言うことをきくようになるよ。',
        r:'このバッジをもっていれば、こうかんでてにいれたポケモンもいうことをきくようになるよ。',
        sp:'ジムの関係者',
        a:'If you have this Badge, even Pokémon you obtained through trading will obey you.',
        c:[
          'If you have this Badge, even Pokémon you obtained through trading will obey you.',
          'This Badge makes your Pokémon stronger, but traded Pokémon still won\'t listen.',
          'With enough Badges, you can make wild Pokémon obey you without catching them.',
          'Badges do nothing for obedience — only training builds trust.',
        ],
        e:'持っていれば = if you have / are carrying (ていれば = conditional of ている). 手に入れた = obtained. 言うことをきく = to obey / do as told (set phrase). 〜ようになる = come to ~; start to ~',
      },
      // ── ライバル ──────────────────────────────────────────────────────
      {
        s:'負けるもんか！ぼくのほうがずっと強いはずなんだ！',
        r:'まけるもんか！ぼくのほうがずっとつよいはずなんだ！',
        sp:'ライバル',
        a:'As if I\'d lose! I\'m supposed to be way stronger than you!',
        c:[
          'As if I\'d lose! I\'m supposed to be way stronger than you!',
          'I admit it — you\'re stronger. I\'ll work harder and challenge you again.',
          'This battle is pointless. I\'m going to win easily anyway.',
          'I\'m not interested in battling. Go away.',
        ],
        e:'〜もんか = "as if ~!" (strong masculine refusal, indignant). 〜のほうがずっと〜 = "~ is way more ~ than ~". 〜はずだ = "supposed to be ~; it should be that ~"',
      },
      // ── ジムリーダー ──────────────────────────────────────────────────
      {
        s:'おめでとう！きみは本当に強いトレーナーだ。これからも、ポケモンと一緒にがんばってね。',
        r:'おめでとう！きみはほんとうにつよいトレーナーだ。これからも、ポケモンといっしょにがんばってね。',
        sp:'ジムリーダー',
        a:'Congratulations! You are a truly strong trainer. Keep doing your best together with your Pokémon.',
        c:[
          'Congratulations! You are a truly strong trainer. Keep doing your best together with your Pokémon.',
          'You got lucky this time. Don\'t think you\'ve actually beaten me.',
          'I\'m impressed you got this far, but the Elite Four won\'t be so easy.',
          'Take this Badge. But don\'t celebrate — the next Gym is much harder.',
        ],
        e:'おめでとう = Congratulations (set phrase). 〜と一緒に = together with ~. これからも = from now on too. がんばる = to do one\'s best; keep at it',
      },
      // ── バトル・ゲームシステム ─────────────────────────────────────────
      {
        s:'〇〇は進化しようとしている！',
        r:'〇〇はしんかしようとしている！',
        sp:'ナレーション',
        a:'〇〇 is trying to evolve!',
        c:[
          '〇〇 is trying to evolve!',
          '〇〇 refused to evolve.',
          '〇〇 has already evolved once and cannot evolve again.',
          '〇〇 reached max level but is not able to evolve.',
        ],
        e:'進化する = to evolve (進化 = evolution). 〜しようとしている = is trying to ~; is about to ~ (volitional form + としている = in the process of attempting)',
      },
      {
        s:'〇〇をゲットした！ポケモン図鑑に登録した。',
        r:'〇〇をゲットした！ポケモンずかんにとうろくした。',
        sp:'ナレーション',
        a:'Caught 〇〇! Registered to the Pokédex.',
        c:[
          'Caught 〇〇! Registered to the Pokédex.',
          '〇〇 escaped! The Poké Ball was no match for it.',
          '〇〇 was already in the Pokédex. No new data recorded.',
          '〇〇 fainted before it could be caught.',
        ],
        e:'ゲットした = caught / got (ゲット is the Pokémon-specific term for catching). 図鑑 = illustrated reference / Pokédex. 登録した = registered / recorded (登録する = to register)',
      },
    ],
  },

  hgss: {
    label: 'HGSS',
    diff: 'N4',
    cats: ['すべて', 'ポケモン', 'まち', 'キャラ', 'セリフ'],
    dialogues: [
      // ── ウツギ博士 ─────────────────────────────────────────────────────
      {
        s:'やあ、ちょうどよかった！ポケモンのことで、きみに頼みたいことがあるんだが…まず、この中から1匹選んでくれないか？',
        r:'やあ、ちょうどよかった！ポケモンのことで、きみにたのみたいことがあるんだが…まず、このなかから1ぴきえらんでくれないか？',
        sp:'ウツギ博士',
        a:'Ah, perfect timing! I have a favour to ask regarding Pokémon… first, would you choose one of these?',
        c:[
          'Ah, perfect timing! I have a favour to ask regarding Pokémon… first, would you choose one of these?',
          'Come back tomorrow — the Pokémon aren\'t ready yet.',
          'I\'m afraid I can\'t give you a Pokémon today. My research is at a critical stage.',
          'The Pokémon you ordered is ready — please come to the lab to pick it up.',
        ],
        e:'ちょうどよかった = "perfect timing" (set phrase). 〜に頼みたいことがある = "I have a favour to ask of ~". 〜から1匹選んでくれないか = "wouldn\'t you choose one from ~?" (polite request with くれないか)',
      },
      {
        s:'ポケモンはすごいよ。どんな環境でも一生懸命生きて、トレーナーを信頼してくれる。わたしはそこに感動するんだ。',
        r:'ポケモンはすごいよ。どんなかんきょうでもいっしょうけんめいいきて、トレーナーをしんらいしてくれる。わたしはそこにかんどうするんだ。',
        sp:'ウツギ博士',
        a:'Pokémon are amazing. They live with all their effort in any environment and trust their trainer. That\'s what moves me.',
        c:[
          'Pokémon are amazing. They live with all their effort in any environment and trust their trainer. That\'s what moves me.',
          'Pokémon are just tools for battle. Their feelings don\'t matter to my research.',
          'Pokémon are mysterious, but I\'ve already figured out everything about them.',
          'I used to love Pokémon, but after years of research it\'s just a job now.',
        ],
        e:'どんな〜でも = no matter what ~; in any ~. 一生懸命 = with all one\'s effort. 信頼してくれる = trust you (くれる = do ~ for me/us). 感動する = to be moved / touched emotionally',
      },
      // ── シルバー（ライバル）────────────────────────────────────────────
      {
        s:'フン、弱いポケモンなんか必要ない。強くなければポケモンじゃないんだよ！',
        r:'フン、よわいポケモンなんかひつようない。つよくなければポケモンじゃないんだよ！',
        sp:'シルバー',
        a:'Hmph. I don\'t need weak Pokémon. If you\'re not strong, you\'re not worth calling a Pokémon!',
        c:[
          'Hmph. I don\'t need weak Pokémon. If you\'re not strong, you\'re not worth calling a Pokémon!',
          'Weak Pokémon are the most interesting. Their potential is limitless.',
          'Strong or weak doesn\'t matter — what matters is the bond between trainer and Pokémon.',
          'I\'ve been collecting only the rarest Pokémon. Strength isn\'t everything.',
        ],
        e:'フン = "hmph" (dismissive snort). 〜なんか = ~ (dismissive particle, belittling something). 〜なければ〜じゃない = double negative for emphasis. This is Silver\'s defining character line.',
      },
      {
        s:'なぜ負けた…。おれのポケモンたちは最強のはずだったのに。おれには…まだ足りないものがあるのか。',
        r:'なぜまけた…。おれのポケモンたちはさいきょうのはずだったのに。おれには…まだたりないものがあるのか。',
        sp:'シルバー',
        a:'Why did I lose…. My Pokémon were supposed to be the strongest. Is there still… something I\'m lacking?',
        c:[
          'Why did I lose…. My Pokémon were supposed to be the strongest. Is there still… something I\'m lacking?',
          'I lost on purpose. I was testing your strength — you passed.',
          'I admit defeat. You\'re clearly stronger. I\'ll find better Pokémon.',
          'That doesn\'t count. My Pokémon weren\'t at full strength today.',
        ],
        e:'〜のはずだったのに = "was supposed to be ~, but…" (expectation unmet; のに = disappointment). 足りない = not enough; lacking. Silver\'s rare moment of self-doubt — key to his character arc.',
      },
      // ── ランス ────────────────────────────────────────────────────────
      {
        s:'悪事を見逃すことはできない。ポケモンを傷つける者は、このランスが許さない！',
        r:'あくじをみのがすことはできない。ポケモンをきずつけるものは、このランスがゆるさない！',
        sp:'ランス',
        a:'I cannot overlook evil. Anyone who harms Pokémon — I, Lance, will not forgive them!',
        c:[
          'I cannot overlook evil. Anyone who harms Pokémon — I, Lance, will not forgive them!',
          'I try not to get involved in other people\'s battles. It\'s not my place.',
          'Evil is a relative concept. What seems harmful may serve a greater purpose.',
          'I forgive those who harm Pokémon, as long as they promise to change.',
        ],
        e:'見逃す = to overlook / let pass (見+逃す = look then let escape). 〜者 = person who ~ (formal/literary). この〜が = "I, ~" (speaker names themselves dramatically). 許さない = will not forgive',
      },
      {
        s:'ポケモンと心が通じ合えれば、どんな壁も乗り越えられる。それがチャンピオンの信念だ。',
        r:'ポケモンとこころがつうじあえれば、どんなかべものりこえられる。それがチャンピオンのしんねんだ。',
        sp:'ランス',
        a:'If your heart can connect with your Pokémon\'s, any wall can be overcome. That is a Champion\'s conviction.',
        c:[
          'If your heart can connect with your Pokémon\'s, any wall can be overcome. That is a Champion\'s conviction.',
          'Champions rely on strategy alone. Feelings for Pokémon can cloud your judgement.',
          'The strongest trainer doesn\'t need a bond — just the strongest Pokémon.',
          'A Champion\'s secret is training 20 hours a day, every day.',
        ],
        e:'心が通じ合う = hearts connect / understand each other (通じ合う = mutually communicate). どんな〜も = any ~ at all. 信念 = conviction; belief; creed',
      },
      // ── キモノガール ──────────────────────────────────────────────────
      {
        s:'ポケモンと旅をする者だけが、伝説の扉を開くことができる。あなたはその資格があると、わたしたちは信じています。',
        r:'ポケモンとたびをするものだけが、でんせつのとびらをひらくことができる。あなたはそのしかくがあると、わたしたちはしんじています。',
        sp:'キモノガール',
        a:'Only those who journey with Pokémon can open the door to legend. We believe you have that right.',
        c:[
          'Only those who journey with Pokémon can open the door to legend. We believe you have that right.',
          'The door to legend is sealed forever. No trainer has ever managed to open it.',
          'Anyone can open the legendary door — you just need the right item.',
          'The legendary Pokémon left long ago. There is no door left to open.',
        ],
        e:'〜者だけが = only those who ~. 扉を開く = to open a door (扉 = door, literary). 〜ことができる = can ~. 資格がある = to have the qualification / right to ~',
      },
      // ── ロケット団 ────────────────────────────────────────────────────
      {
        s:'じゃまをするな！おれたちロケット団に逆らう気か？今すぐ後悔させてやる！',
        r:'じゃまをするな！おれたちロケットだんにさからうきか？いますぐこうかいさせてやる！',
        sp:'ロケット団',
        a:'Stay out of our way! Are you planning to defy Team Rocket? We\'ll make you regret it right now!',
        c:[
          'Stay out of our way! Are you planning to defy Team Rocket? We\'ll make you regret it right now!',
          'We\'re Team Rocket, and we\'re actually the good guys. Please don\'t interfere.',
          'We\'re not here to cause trouble — we\'re just borrowing this building for a moment.',
          'Team Rocket disbanded years ago. We\'re just wearing the uniforms for fun.',
        ],
        e:'じゃまをするな = "don\'t get in the way!" (な = negative command, rough). 〜に逆らう = to defy / go against ~. 〜気か = "are you intending to ~?" (threatening). 後悔させてやる = "I\'ll make you regret it" (させる causative + やる rough)',
      },
      // ── 伝説のポケモン ────────────────────────────────────────────────
      {
        s:'伝説のポケモン、ホウオウがすがたをあらわした！虹色の羽が空を染める。',
        r:'でんせつのポケモン、ホウオウがすがたをあらわした！にじいろのはねがそらをそめる。',
        sp:'ナレーション',
        a:'The legendary Pokémon Ho-Oh appeared! Its rainbow-coloured wings dye the sky.',
        c:[
          'The legendary Pokémon Ho-Oh appeared! Its rainbow-coloured wings dye the sky.',
          'A strange bird flew overhead. It was probably just a Pidgey.',
          'The legendary Ho-Oh has already been caught by another trainer.',
          'Ho-Oh appeared, but fled before anyone could see it clearly.',
        ],
        e:'姿をあらわす = to appear; show oneself (姿 = figure/form). 虹色 = rainbow-coloured (虹 = rainbow). 〜が空を染める = ~ dyes the sky (染める = to dye/colour)',
      },
      // ── 白銀山の伝説 ──────────────────────────────────────────────────
      {
        s:'白銀山の頂上に、すべてのトレーナーを退けてきた伝説の少年がいる。彼は何も語らず、ただ戦うだけだ。',
        r:'しろがねやまのちょうじょうに、すべてのトレーナーをしりぞけてきたでんせつのしょうねんがいる。かれはなにもかたらず、ただたたかうだけだ。',
        sp:'ひとつわたし',
        a:'At the summit of Mt. Silver, there is a legendary boy who has turned away every trainer. He says nothing — he only battles.',
        c:[
          'At the summit of Mt. Silver, there is a legendary boy who has turned away every trainer. He says nothing — he only battles.',
          'A young boy lives on Mt. Silver studying Pokémon. He\'s friendly and will answer your questions.',
          'Mt. Silver\'s summit is empty. The legend of the trainer there is just a rumour.',
          'The trainer on Mt. Silver is a disguised Gym Leader doing secret training.',
        ],
        e:'頂上 = summit; peak. 退ける = to turn away; repel (退 = retreat/back). 何も語らず = without saying anything (語る = to speak; ず = classical negative). ただ〜だけだ = nothing but ~',
      },
    ],
    vocab: [
      // ── ポケモン ─────────────────────────────────────────────────────
      {w:'チコリータ',r:'チコリータ',m:'Chikorita — Grass starter',cat:'ポケモン'},
      {w:'ベイリーフ',r:'ベイリーフ',m:'Bayleef',cat:'ポケモン'},
      {w:'メガニウム',r:'メガニウム',m:'Meganium — final Grass evolution',cat:'ポケモン'},
      {w:'ヒノアラシ',r:'ヒノアラシ',m:'Cyndaquil — Fire starter',cat:'ポケモン'},
      {w:'マグマラシ',r:'マグマラシ',m:'Quilava',cat:'ポケモン'},
      {w:'バクフーン',r:'バクフーン',m:'Typhlosion — final Fire evolution',cat:'ポケモン'},
      {w:'ワニノコ',r:'ワニノコ',m:'Totodile — Water starter',cat:'ポケモン'},
      {w:'アリゲイツ',r:'アリゲイツ',m:'Croconaw',cat:'ポケモン'},
      {w:'オーダイル',r:'オーダイル',m:'Feraligatr — final Water evolution',cat:'ポケモン'},
      {w:'ホウオウ',r:'ホウオウ',m:'Ho-Oh — legendary rainbow Pokémon (HeartGold)',cat:'ポケモン'},
      {w:'ルギア',r:'ルギア',m:'Lugia — legendary diving Pokémon (SoulSilver)',cat:'ポケモン'},
      {w:'スイクン',r:'スイクン',m:'Suicune — legendary Water beast',cat:'ポケモン'},
      {w:'ライコウ',r:'ライコウ',m:'Raikou — legendary Electric beast',cat:'ポケモン'},
      {w:'エンテイ',r:'エンテイ',m:'Entei — legendary Fire beast',cat:'ポケモン'},
      {w:'セレビィ',r:'セレビィ',m:'Celebi — mythical time-travel Pokémon',cat:'ポケモン'},
      // ── まち（ジョウト地方）──────────────────────────────────────────
      // Japanese town names differ entirely from English — the kanji roots are worth knowing
      {w:'ワカバタウン',r:'ワカバタウン',m:'New Bark Town (若葉 = young leaf)',cat:'まち'},
      {w:'ウバメシティ',r:'ウバメシティ',m:'Cherrygrove City (ウバメガシ = ubame oak)',cat:'まち'},
      {w:'キキョウシティ',r:'キキョウシティ',m:'Violet City (桔梗 = bellflower)',cat:'まち'},
      {w:'ヒワダタウン',r:'ヒワダタウン',m:'Azalea Town (檜皮 = hinoki bark)',cat:'まち'},
      {w:'コガネシティ',r:'コガネシティ',m:'Goldenrod City (黄金 = gold)',cat:'まち'},
      {w:'エンジュシティ',r:'エンジュシティ',m:'Ecruteak City (槐 = pagoda tree)',cat:'まち'},
      {w:'アサギシティ',r:'アサギシティ',m:'Olivine City (浅葱 = pale blue-green)',cat:'まち'},
      {w:'タンバシティ',r:'タンバシティ',m:'Cianwood City (丹波 = old region name)',cat:'まち'},
      {w:'チョウジタウン',r:'チョウジタウン',m:'Mahogany Town (丁子 = clove)',cat:'まち'},
      {w:'フスベシティ',r:'フスベシティ',m:'Blackthorn City (燻 = to smoke)',cat:'まち'},
      {w:'白銀山',r:'しろがねやま',m:'Mt. Silver (白銀 = silver/white gold) — Red waits at the summit',cat:'まち'},
      {w:'チャンピオンロード',r:'チャンピオンロード',m:'Victory Road — final route before the Pokémon League',cat:'まち'},
      // ── キャラ ───────────────────────────────────────────────────────
      {w:'ウツギ博士',r:'ウツギはかせ',m:'Professor Elm — Johto\'s Pokémon researcher',cat:'キャラ'},
      {w:'シルバー',r:'シルバー',m:'Silver — the rival; cold and obsessed with strength',cat:'キャラ'},
      {w:'ランス',r:'ランス',m:'Lance — Dragon Master and Johto Champion',cat:'キャラ'},
      {w:'カリン',r:'カリン',m:'Karen — Dark-type Elite Four member',cat:'キャラ'},
      {w:'レッド',r:'レッド',m:'Red — the legendary silent trainer at Mt. Silver\'s summit',cat:'キャラ'},
      {w:'ブルー',r:'ブルー',m:'Blue (Gary) — Viridian City Gym Leader',cat:'キャラ'},
      {w:'キモノガール',r:'キモノガール',m:'Kimono Girls — five dancers who guard the path to the legendaries',cat:'キャラ'},
      {w:'ロケット団',r:'ロケットだん',m:'Team Rocket — villain organisation',cat:'キャラ'},
    ],
  },

  bw: {
    label: 'ぼうけん日誌',
    diff: 'N5–N4',
    cats: ['すべて', 'フィールド', 'わざ'],
    // Personal word log — add new words as you encounter them in Pokémon White
    vocab: [
      // ── フィールド ───────────────────────────────────────────────────
      {w:'届く',r:'とどく',m:'to reach; to arrive; to be delivered (e.g. a letter)',cat:'フィールド'},
      {w:'一歩踏み出す',r:'いっぽふみだす',m:'to take a step forward; to set out on a journey',cat:'フィールド'},
      {w:'博士',r:'はかせ',m:'professor; doctor (here: the Pokémon professor of Unova)',cat:'フィールド'},
      {w:'調べる',r:'しらべる',m:'to investigate; to look into; to check on something',cat:'フィールド'},
      {w:'開ける',r:'あける',m:'to open (a box, a door, a present)',cat:'フィールド'},
      {w:'手紙',r:'てがみ',m:'letter (written message — e.g. from mom at the start)',cat:'フィールド'},
      {w:'三匹',r:'さんびき',m:'three small animals / Pokémon (counter: 匹 for small creatures)',cat:'フィールド'},
      {w:'仲良く',r:'なかよく',m:'on good terms; getting along well; in a friendly way',cat:'フィールド'},
      {w:'決める',r:'きめる',m:'to decide; to choose; to make up one\'s mind',cat:'フィールド'},
      {w:'最初',r:'さいしょ',m:'the first; the beginning; the very start',cat:'フィールド'},
      {w:'勝負',r:'しょうぶ',m:'match; contest; showdown; putting it to the test',cat:'フィールド'},
      {w:'弱い',r:'よわい',m:'weak; frail; not strong',cat:'フィールド'},
      {w:'戦う',r:'たたかう',m:'to fight; to battle; to struggle against',cat:'フィールド'},
      {w:'育てる',r:'そだてる',m:'to raise; to bring up; to nurture (a Pokémon)',cat:'フィールド'},
      {w:'周り',r:'まわり',m:'surroundings; around; nearby',cat:'フィールド'},
      {w:'回復',r:'かいふく',m:'recovery; restoration; healing',cat:'フィールド'},
      {w:'詳しい',r:'くわしい',m:'detailed; familiar with; well-versed in',cat:'フィールド'},
      {w:'知識',r:'ちしき',m:'knowledge; expertise; know-how',cat:'フィールド'},
      {w:'ツタージャ',r:'ツタージャ',m:'Snivy — Grass starter (蔦=ivy + 蛇=snake → ツタージャ)',cat:'フィールド'},
      {w:'騒がしい',r:'さわがしい',m:'noisy; boisterous; rowdy; bustling',cat:'フィールド'},
      {w:'失礼します',r:'しつれいします',m:'excuse me; sorry to intrude (polite phrase when entering or leaving)',cat:'フィールド'},
      {w:'お礼',r:'おれい',m:'thanks; expression of gratitude',cat:'フィールド'},
      {w:'研究所',r:'けんきゅうじょ',m:"research lab; the Pokémon professor's laboratory",cat:'フィールド'},
      {w:'一度',r:'いちど',m:'once; one time; for once',cat:'フィールド'},
      {w:'お邪魔します',r:'おじゃまします',m:"excuse me for intruding; said when entering someone's room or home",cat:'フィールド'},
      {w:'賑やか',r:'にぎやか',m:'lively; bustling; cheerful; merry',cat:'フィールド'},
      {w:'鳴き声',r:'なきごえ',m:'Pokémon cry; animal call; sound a creature makes',cat:'フィールド'},
      {w:'聞こえる',r:'きこえる',m:'to be heard; to be audible; to sound like',cat:'フィールド'},
      {w:'思い出す',r:'おもいだす',m:'to recall; to remember; to recollect',cat:'フィールド'},
      {w:'大切',r:'たいせつ',m:'important; precious; valued; dear',cat:'フィールド'},
      {w:'活躍',r:'かつやく',m:'being active; playing an active role; making great efforts',cat:'フィールド'},
      {w:'書き込みます',r:'かきこみます',m:'to write in; to fill in an entry (e.g. a Pokédex record)',cat:'フィールド'},
      {w:'鹿の子',r:'かのこ',m:'fawn; little deer (鹿=deer, 子=child) — used as カノコタウン, the starting town in Pokémon White',cat:'フィールド'},
      {w:'様々な',r:'さまざまな',m:'various; diverse; all kinds of',cat:'フィールド'},
      {w:'点',r:'てん',m:'point; aspect; mark; dot',cat:'フィールド'},
      {w:'集う',r:'つどう',m:'to gather; to assemble; to come together',cat:'フィールド'},
      {w:'街',r:'まち',m:'town; city; streets; neighborhood',cat:'フィールド'},
      {w:'のんびりしている',r:'のんびりしている',m:'relaxed; easygoing; laid-back; taking it easy',cat:'フィールド'},
      {w:'いつものように',r:'いつものように',m:'as usual; just like always; in the usual way',cat:'フィールド'},
      {w:'きっと',r:'きっと',m:'surely; certainly; undoubtedly; I bet',cat:'フィールド'},
      {w:'立派',r:'りっぱ',m:'splendid; fine; impressive; admirable',cat:'フィールド'},
      {w:'冒険',r:'ぼうけん',m:'adventure; venture; setting out into the unknown',cat:'フィールド'},
      {w:'娘',r:'むすめ',m:'daughter; girl; young woman',cat:'フィールド'},
      {w:'旅',r:'たび',m:'journey; travel; trip',cat:'フィールド'},
      {w:'世間知らず',r:'せけんしらず',m:'unworldly; naive; inexperienced in the ways of the world',cat:'フィールド'},
      {w:'心配',r:'しんぱい',m:'worry; concern; anxiety',cat:'フィールド'},
      {w:'秘密',r:'ひみつ',m:'secret; mystery',cat:'フィールド'},
      {w:'自己紹介',r:'じこしょうかい',m:'self-introduction',cat:'フィールド'},
      {w:'改めて',r:'あらためて',m:'once more; again; formally; starting fresh',cat:'フィールド'},
      {w:'記念となる日',r:'きねんとなるひ',m:'a memorable day; a day that marks a milestone',cat:'フィールド'},
      {w:'畏まった',r:'かしこまった',m:'formal; stiff; overly respectful (used to describe stiff/formal speech)',cat:'フィールド'},
      {w:'種族',r:'しゅぞく',m:'species; tribe; race (here: Pokémon species)',cat:'フィールド'},
      {w:'誕生',r:'たんじょう',m:'birth; emergence; creation',cat:'フィールド'},
      {w:'起源',r:'きげん',m:'origin; beginning; source',cat:'フィールド'},
      {w:'信頼する',r:'しんらいする',m:'to trust; to have faith in; to rely on',cat:'フィールド'},
      {w:'そんな感じ',r:'そんなかんじ',m:'something like that; that kind of feeling; sort of',cat:'フィールド'},
      {w:'理由',r:'りゆう',m:'reason; cause; grounds',cat:'フィールド'},
      {w:'図鑑',r:'ずかん',m:'illustrated encyclopedia; Pokédex (picture guide of Pokémon)',cat:'フィールド'},
      {w:'説明',r:'せつめい',m:'explanation; description',cat:'フィールド'},
      {w:'出会う',r:'であう',m:'to encounter; to meet; to come across',cat:'フィールド'},
      {w:'自動的',r:'じどうてき',m:'automatic (自動的に = automatically)',cat:'フィールド'},
      {w:'記録',r:'きろく',m:'record; log; documentation',cat:'フィールド'},
      {w:'道具',r:'どうぐ',m:'tool; item; implement (Pokémon: items in your bag)',cat:'フィールド'},
      {w:'イッシュ地方',r:'イッシュちほう',m:'Unova Region — the setting of Pokémon Black and White',cat:'フィールド'},
      {w:'お聞きします',r:'おききします',m:'may I ask; I would like to hear (polite form of 聞く)',cat:'フィールド'},
      {w:'完成',r:'かんせい',m:'completion; finished; accomplished',cat:'フィールド'},
      {w:'出かける',r:'でかける',m:'to go out; to head out; to set off',cat:'フィールド'},
      {w:'お陰で',r:'おかげで',m:'thanks to; owing to (usually positive)',cat:'フィールド'},
      {w:'念願',r:'ねんがん',m:'long-cherished wish; lifelong dream',cat:'フィールド'},
      {w:'最高',r:'さいこう',m:'the best; greatest; excellent; awesome',cat:'フィールド'},
      {w:'返事',r:'へんじ',m:'reply; answer; response',cat:'フィールド'},
      {w:'方法',r:'ほうほう',m:'method; way; means',cat:'フィールド'},
      {w:'教える',r:'おしえる',m:'to teach; to tell; to show; to inform',cat:'フィールド'},
      {w:'一番道路',r:'いちばんどうろ',m:'Route 1 — first route leaving カノコタウン (Nuvema Town)',cat:'フィールド'},
      {w:'頼む',r:'たのむ',m:'to ask; to request; to beg; to rely on',cat:'フィールド'},
      {w:'探す',r:'さがす',m:'to search; to look for; to seek',cat:'フィールド'},
      {w:'やりたいこと',r:'やりたいこと',m:'what you want to do; your aspirations; things you want to try',cat:'フィールド'},
      {w:'好きな様に',r:'すきなように',m:'however you like; in your own way; as you please',cat:'フィールド'},
      {w:'なんだかドキドキしてきた',r:'なんだかドキドキしてきた',m:"my heart is starting to pound; I'm getting nervous/excited (なんだか=somehow, ドキドキ=heart pounding)",cat:'フィールド'},
      {w:'漸く',r:'ようやく',m:'finally; at last; barely; with difficulty',cat:'フィールド'},
      {w:'実戦',r:'じっせん',m:'actual battle; real combat; field experience (not just practice)',cat:'フィールド'},
      {w:'重ねて',r:'かさねて',m:'repeatedly; again; additionally; on top of that',cat:'フィールド'},
      {w:'強い',r:'つよい',m:'strong; powerful',cat:'フィールド'},
      {w:'気にしない',r:'きにしない',m:"don't mind; don't worry about it; not bothered",cat:'フィールド'},
      {w:'吹き飛ばす',r:'ふきとばす',m:'to blow away; to blast off; to knock flying',cat:'フィールド'},
      {w:'ほど',r:'ほど',m:'to the extent that; about; approximately; the more… the more',cat:'フィールド'},
      {w:'とんでもない',r:'とんでもない',m:'outrageous; unthinkable; absolutely not! (strong denial or surprise)',cat:'フィールド'},
      {w:'秘める',r:'ひめる',m:'to keep secret; to hold within; to harbor (a feeling)',cat:'フィールド'},
      {w:'安心',r:'あんしん',m:'relief; peace of mind; reassurance',cat:'フィールド'},
      {w:'伝える',r:'つたえる',m:'to convey; to tell; to pass on; to communicate',cat:'フィールド'},
      {w:'素敵な',r:'すてきな',m:'wonderful; lovely; splendid; great',cat:'フィールド'},
      {w:'見つける',r:'みつける',m:'to find; to discover; to come across',cat:'フィールド'},
      {w:'捕まえる',r:'つかまえる',m:'to catch; to capture; to grab (the core Pokémon mechanic)',cat:'フィールド'},
      {w:'情報',r:'じょうほう',m:'information; data; news',cat:'フィールド'},
      {w:'得られる',r:'えられる',m:'can be obtained; obtainable; able to gain',cat:'フィールド'},
      {w:'実際に',r:'じっさいに',m:'actually; in practice; in reality',cat:'フィールド'},
      {w:'解説する',r:'かいせつする',m:'to explain; to commentate; to give commentary',cat:'フィールド'},
      {w:'体力',r:'たいりょく',m:'stamina; physical strength; HP (hit points)',cat:'フィールド'},
      {w:'減らす',r:'へらす',m:"to reduce; to lower; to decrease (e.g. a Pokémon's HP)",cat:'フィールド'},
      {w:'技',r:'わざ',m:'technique; skill; move (a Pokémon move/attack)',cat:'フィールド'},
      {w:'眠らせる',r:'ねむらせる',m:'to put to sleep; to inflict the sleep status condition',cat:'フィールド'},
      {w:'麻痺させる',r:'まひさせる',m:'to paralyze; to inflict the paralysis status condition',cat:'フィールド'},
      {w:'連れる',r:'つれる',m:'to take along; to bring with you (a Pokémon)',cat:'フィールド'},
      {w:'運ぶ',r:'はこぶ',m:'to carry; to transport; to bring',cat:'フィールド'},
      {w:'この先',r:'このさき',m:'ahead; beyond this point; from here on',cat:'フィールド'},
      {w:'ちなみに',r:'ちなみに',m:'by the way; incidentally; for reference',cat:'フィールド'},
      {w:'飛び出す',r:'とびだす',m:'to jump out; to burst out; to rush out (wild Pokémon appearing!)',cat:'フィールド'},
      {w:'草むら',r:'くさむら',m:'tall grass; patch of grass (where wild Pokémon hide)',cat:'フィールド'},
      {w:'向かう',r:'むかう',m:'to head toward; to face; to go in the direction of',cat:'フィールド'},
      {w:'賛成',r:'さんせい',m:'agreement; approval; I agree!',cat:'フィールド'},
      {w:'隣町',r:'となりまち',m:'neighboring town; the next town over',cat:'フィールド'},
      {w:'競争',r:'きょうそう',m:'competition; race; rivalry',cat:'フィールド'},
      {w:'含めて',r:'ふくめて',m:'including; inclusive of',cat:'フィールド'},
      {w:'勝ち',r:'かち',m:'win; victory',cat:'フィールド'},
      {w:'埋まる',r:'うまる',m:"to be filled in; to be completed (e.g. Pokédex entries filled)",cat:'フィールド'},
      {w:'喜ぶ',r:'よろこぶ',m:'to be glad; to be pleased; to rejoice',cat:'フィールド'},
      {w:'着く',r:'つく',m:'to arrive; to reach; to get to a destination',cat:'フィールド'},
      {w:'自宅',r:'じたく',m:"one's own home; own residence",cat:'フィールド'},
      {w:'唐草',r:'からくさ',m:'arabesque; scrolling vine pattern (traditional decorative motif)',cat:'フィールド'},
      {w:'お得な',r:'おとくな',m:'advantageous; a good deal; great value; bargain',cat:'フィールド'},
      {w:'掲示板',r:'けいじばん',m:'bulletin board; message board; notice board',cat:'フィールド'},
      {w:'せっかく',r:'せっかく',m:'since you went to the trouble; specially; with much effort',cat:'フィールド'},
      {w:'役立つ',r:'やくだつ',m:'to be useful; to be helpful; to serve a purpose',cat:'フィールド'},
      {w:'野生',r:'やせい',m:'wild; untamed (野生のポケモン = wild Pokémon)',cat:'フィールド'},
      {w:'潜む',r:'ひそむ',m:'to lurk; to hide; to lie in wait',cat:'フィールド'},
      {w:'ばっちり',r:'ばっちり',m:'perfectly; spot on; nailed it (casual praise)',cat:'フィールド'},
      {w:'真ん中',r:'まんなか',m:'middle; center; right in the middle',cat:'フィールド'},
      {w:'無理せず',r:'むりせず',m:"without overdoing it; don't push yourself; take it easy",cat:'フィールド'},
      {w:'こまめに',r:'こまめに',m:'diligently; frequently; attentively (doing small things regularly)',cat:'フィールド'},
      {w:'ヨーテリー',r:'ヨーテリー',m:'Lillipup — the puppy Pokémon (from ヨークシャーテリア = Yorkshire Terrier)',cat:'フィールド'},
      {w:'投げる',r:'なげる',m:'to throw; to hurl; to toss (e.g. a Poké Ball)',cat:'フィールド'},
      {w:'式',r:'しき',m:'ceremony; style; method; formula',cat:'フィールド'},
      {w:'休憩',r:'きゅうけい',m:'rest; break; recess',cat:'フィールド'},
      {w:'元気いっぱい',r:'げんきいっぱい',m:'full of energy; very lively; bursting with vitality',cat:'フィールド'},
      {w:'ミネズミ',r:'ミネズミ',m:'Patrat — the scout Pokémon (Normal type; from 峰鼠 = peak mouse)',cat:'フィールド'},
      {w:'比べる',r:'くらべる',m:'to compare; to contrast',cat:'フィールド'},
      {w:'数',r:'かず',m:'number; count; quantity',cat:'フィールド'},
      {w:'繋げる',r:'つなげる',m:'to connect; to link; to join together',cat:'フィールド'},
      {w:'案内する',r:'あんないする',m:'to guide; to show around; to give directions',cat:'フィールド'},
      {w:'早くおいで',r:'はやくおいで',m:'hurry up and come here!; come quickly!',cat:'フィールド'},
      {w:'先に行くよ',r:'さきにいくよ',m:"I'll go ahead; going on first",cat:'フィールド'},
      {w:'道',r:'みち',m:'road; path; way; route',cat:'フィールド'},
      {w:'共に',r:'ともに',m:'together; along with; both',cat:'フィールド'},
      {w:'施設',r:'しせつ',m:'facility; institution; establishment',cat:'フィールド'},
      {w:'付いてきて',r:'ついてきて',m:'follow me; come along (te-form of 付いてくる)',cat:'フィールド'},
      {w:'落ち着く',r:'おちつく',m:'to calm down; to settle down; to be at ease',cat:'フィールド'},
      {w:'なんとなく',r:'なんとなく',m:'somehow; vaguely; for no particular reason',cat:'フィールド'},
      {w:'無料',r:'むりょう',m:'free of charge; no cost; gratis',cat:'フィールド'},
      {w:'しかも',r:'しかも',m:'moreover; furthermore; and yet; what is more',cat:'フィールド'},
      {w:'味方',r:'みかた',m:'ally; friend; one who is on your side',cat:'フィールド'},
      {w:'預かる',r:'あずかる',m:'to look after; to take care of; to hold in custody (e.g. Pokémon PC)',cat:'フィールド'},
      {w:'利用',r:'りよう',m:'use; utilization; making use of',cat:'フィールド'},
      {w:'引き出す',r:'ひきだす',m:'to pull out; to draw out; to withdraw (e.g. Pokémon from PC)',cat:'フィールド'},
      {w:'逆に',r:'ぎゃくに',m:'conversely; on the contrary; in reverse',cat:'フィールド'},
      {w:'転送する',r:'てんそうする',m:'to transfer; to send over; to forward (e.g. transferring Pokémon)',cat:'フィールド'},
      {w:'評価',r:'ひょうか',m:'evaluation; assessment; rating',cat:'フィールド'},
      {w:'選ぶ',r:'えらぶ',m:'to choose; to select; to pick',cat:'フィールド'},
      {w:'画面',r:'がめん',m:'screen; display; image on screen',cat:'フィールド'},
      {w:'よく気づいた',r:'よくきづいた',m:'good catch!; well spotted; you noticed well',cat:'フィールド'},
      {w:'質問',r:'しつもん',m:'question; inquiry',cat:'フィールド'},
      {w:'要る',r:'いる',m:'to need; to require; to be necessary',cat:'フィールド'},
      {w:'売る',r:'うる',m:'to sell',cat:'フィールド'},
      {w:'笑顔',r:'えがお',m:'smiling face; smile; beaming expression',cat:'フィールド'},
      {w:'対応する',r:'たいおうする',m:'to respond to; to deal with; to handle',cat:'フィールド'},
      {w:'基礎',r:'きそ',m:'foundation; basis; basics; fundamentals',cat:'フィールド'},
      {w:'最後',r:'さいご',m:'last; final; end; conclusion',cat:'フィールド'},
      {w:'発明家',r:'はつめいか',m:'inventor',cat:'フィールド'},
      {w:'山陽シティ',r:'さんようシティ',m:'Striaton City — first gym city in Pokémon BW',cat:'フィールド'},
      {w:'古い',r:'ふるい',m:'old; aged; ancient; antique',cat:'フィールド'},
      {w:'手助け',r:'てだすけ',m:'help; assistance; lending a hand',cat:'フィールド'},
      {w:'友達',r:'ともだち',m:'friend; companion; pal',cat:'フィールド'},
      {w:'実り多いもの',r:'みのりおおいもの',m:'something rewarding; a fruitful outcome; something of great value',cat:'フィールド'},
      {w:'大事',r:'だいじ',m:'important; precious; valuable; serious matter',cat:'フィールド'},
      {w:'傷薬',r:'きずぐすり',m:'Potion — basic wound medicine; healing item',cat:'フィールド'},
      {w:'お買い上げ',r:'おかいあげ',m:'purchase; buying (honorific: thank you for your purchase)',cat:'フィールド'},
      {w:'広場',r:'ひろば',m:'plaza; town square; open space',cat:'フィールド'},
      {w:'始まる',r:'はじまる',m:'to begin; to start; to commence',cat:'フィールド'},
      {w:'団',r:'だん',m:'group; organization; corps (as in プラズマ団 = Team Plasma)',cat:'フィールド'},
      {w:'解放',r:'かいほう',m:"liberation; release; setting free (Team Plasma's stated goal)",cat:'フィールド'},
      {w:'人間',r:'にんげん',m:'human being; person; mankind',cat:'フィールド'},
      {w:'暮らす',r:'くらす',m:'to live; to get along; to make a living',cat:'フィールド'},
      {w:'お互い',r:'おたがい',m:'each other; one another; mutually',cat:'フィールド'},
      {w:'求める',r:'もとめる',m:'to seek; to desire; to demand; to ask for',cat:'フィールド'},
      {w:'必要とする',r:'ひつようとする',m:'to need; to require; to necessitate',cat:'フィールド'},
      {w:'～合う',r:'あう',m:'(suffix) to do mutually; with each other (e.g. 助け合う = help each other)',cat:'フィールド'},
      {w:'思い込む',r:'おもいこむ',m:'to be convinced of; to assume without basis; to be under the impression',cat:'フィールド'},
      {w:'ふうに',r:'ふうに',m:'in a way; in the manner of; like (e.g. そういうふうに = in that way)',cat:'フィールド'},
      {w:'好き勝手',r:'すきかって',m:'doing as one pleases; self-indulgent; acting however you like',cat:'フィールド'},
      {w:'命令',r:'めいれい',m:'order; command; instruction; directive',cat:'フィールド'},
      {w:'こき使っている',r:'こきつかっている',m:'working someone to the bone; exploiting; driving someone relentlessly',cat:'フィールド'},
      {w:'言い切る',r:'いいきる',m:'to declare; to state definitively; to say with certainty',cat:'フィールド'},
      {w:'はっきり',r:'はっきり',m:'clearly; distinctly; plainly; without ambiguity',cat:'フィールド'},
      {w:'異なり',r:'ことなり',m:'differing; being different (conjunctive form of 異なる)',cat:'フィールド'},
      {w:'未知の',r:'みちの',m:'unknown; unexplored; undiscovered',cat:'フィールド'},
      {w:'可能性',r:'かのうせい',m:'possibility; potential; chance',cat:'フィールド'},
      {w:'生き物',r:'いきもの',m:'living thing; creature; living being',cat:'フィールド'},
      {w:'学ぶ',r:'まなぶ',m:'to learn; to study; to take lessons in',cat:'フィールド'},
      {w:'べき',r:'べき',m:'should; ought to; must (expresses obligation or expectation)',cat:'フィールド'},
      {w:'数多く',r:'かずおおく',m:'many; numerous; in large numbers',cat:'フィールド'},
      {w:'持つ',r:'もつ',m:'to hold; to have; to possess; to carry',cat:'フィールド'},
      {w:'存在',r:'そんざい',m:'existence; being; presence',cat:'フィールド'},
      {w:'対し',r:'たいし',m:'toward; against; regarding (from 対する = to face; to be directed at)',cat:'フィールド'},
      {w:'対等',r:'たいとう',m:'equal; on equal terms; peer-to-peer',cat:'フィールド'},
      {w:'正し',r:'ただし',m:'however; but; that said; provided that',cat:'フィールド'},
      {w:'付き合う',r:'つきあう',m:'to associate with; to keep company with; to get along with',cat:'フィールド'},
      {w:'静聴',r:'せいちょう',m:'attentive listening (ご静聴ありがとうございました = thank you for your attention)',cat:'フィールド'},
      {w:'感謝',r:'かんしゃ',m:'gratitude; thanks; appreciation',cat:'フィールド'},
      {w:'終わる',r:'おわる',m:'to end; to finish; to conclude',cat:'フィールド'},
      {w:'演説',r:'えんぜつ',m:'speech; address; oration (a public speech)',cat:'フィールド'},
      {w:'あり得る',r:'ありえる',m:'possible; conceivable; can happen',cat:'フィールド'},
      {w:'ずいぶんと',r:'ずいぶんと',m:'quite; considerably; very; rather (colloquial intensifier)',cat:'フィールド'},
      {w:'早口',r:'はやくち',m:'fast talker; speaking rapidly; fast speech',cat:'フィールド'},
      {w:'目標',r:'もくひょう',m:'goal; target; objective; aim',cat:'フィールド'},
      {w:'閉じ込める',r:'とじこめる',m:'to lock in; to shut in; to confine; to imprison',cat:'フィールド'},
      {w:'幾多の',r:'いくたの',m:'many; numerous; countless; a great many',cat:'フィールド'},
      {w:'疑問',r:'ぎもん',m:'question; doubt; skepticism; unresolved concern',cat:'フィールド'},
      {w:'声',r:'こえ',m:'voice; sound; cry',cat:'フィールド'},
      {w:'聴かせて',r:'きかせて',m:'let me hear; please tell me (te-form of 聴かせる = to let hear)',cat:'フィールド'},
      {w:'完全な',r:'かんぜんな',m:'complete; perfect; whole; total',cat:'フィールド'},
      {w:'変える',r:'かえる',m:'to change; to alter; to transform',cat:'フィールド'},
      {w:'変更',r:'へんこう',m:'change; modification; alteration; revision',cat:'フィールド'},
      {w:'可笑しい',r:'おかしい',m:'funny; strange; odd; suspicious; ridiculous',cat:'フィールド'},
      {w:'各地',r:'かくち',m:'various places; every region; all parts of a country',cat:'フィールド'},
      {w:'電光',r:'でんこう',m:'lightning; flash of light; electric light',cat:'フィールド'},
      {w:'流れる',r:'ながれる',m:'to flow; to stream; to run (like water or current)',cat:'フィールド'},
      {w:'幸せ',r:'しあわせ',m:'happiness; good fortune; luck; blessing',cat:'フィールド'},
      {w:'連絡',r:'れんらく',m:'contact; communication; getting in touch',cat:'フィールド'},
      {w:'追う',r:'おう',m:'to chase; to pursue; to follow',cat:'フィールド'},
      {w:'おそらく',r:'おそらく',m:'probably; perhaps; presumably',cat:'フィールド'},
      {w:'履く',r:'はく',m:'to put on (shoes, pants); to wear on the lower body',cat:'フィールド'},
      {w:'取扱',r:'とりあつかい',m:'handling; treatment; dealing with (as in 取扱説明書 = instruction manual)',cat:'フィールド'},
      {w:'説明書',r:'せつめいしょ',m:'instruction manual; written explanation; manual',cat:'フィールド'},
      {w:'読む',r:'よむ',m:'to read',cat:'フィールド'},
      {w:'速く',r:'はやく',m:'fast; quickly; rapidly',cat:'フィールド'},
      {w:'走る',r:'はしる',m:'to run; to dash; to race',cat:'フィールド'},
      {w:'押す',r:'おす',m:'to push; to press; to stamp',cat:'フィールド'},
      {w:'片づけ',r:'かたづけ',m:'tidying up; putting away; cleaning up',cat:'フィールド'},
      {w:'たまに',r:'たまに',m:'occasionally; once in a while; sometimes; rarely',cat:'フィールド'},
      {w:'想う',r:'おもう',m:'to think; to feel; to yearn for (deeper/more emotional than 思う)',cat:'フィールド'},
      {w:'逃げる',r:'にげる',m:'to run away; to escape; to flee',cat:'フィールド'},
      {w:'許されない',r:'ゆるされない',m:'unforgivable; not permitted; cannot be forgiven',cat:'フィールド'},
      {w:'真剣',r:'しんけん',m:'serious; earnest; in earnest; with all one\'s heart',cat:'フィールド'},
      {w:'チョロネコ',r:'チョロネコ',m:'Purrloin — the sneaky cat Pokémon (Dark type; from ちょろい猫 = sneaky cat)',cat:'フィールド'},
      {w:'下げる',r:'さげる',m:'to lower; to reduce; to bring down',cat:'フィールド'},
      {w:'攻撃',r:'こうげき',m:'attack; assault; offensive',cat:'フィールド'},
      {w:'相手',r:'あいて',m:'opponent; partner; the other party',cat:'フィールド'},
      {w:'段差',r:'だんさ',m:'step; ledge; level difference; height gap',cat:'フィールド'},
      {w:'近道',r:'ちかみち',m:'shortcut; shorter route',cat:'フィールド'},
      {w:'降りる',r:'おりる',m:'to descend; to get off; to come down',cat:'フィールド'},
      {w:'歩く',r:'あるく',m:'to walk',cat:'フィールド'},
      {w:'戦闘',r:'せんとう',m:'battle; combat; fight (Pokémon battle!)',cat:'フィールド'},
      {w:'参加する',r:'さんかする',m:'to participate; to join; to take part in',cat:'フィールド'},
      {w:'経験値',r:'けいけんち',m:'experience points; EXP (points earned from battles)',cat:'フィールド'},
      {w:'さらに',r:'さらに',m:'furthermore; moreover; additionally; even more',cat:'フィールド'},
      {w:'可愛く',r:'かわいく',m:'cutely; in a cute way (adverb form of 可愛い)',cat:'フィールド'},
      {w:'頑張る',r:'がんばる',m:"to do one's best; to persist; to hang in there",cat:'フィールド'},
      {w:'細長い',r:'ほそながい',m:'long and thin; slender; elongated',cat:'フィールド'},
      {w:'体',r:'からだ',m:'body; physique; health',cat:'フィールド'},
      {w:'間',r:'あいだ',m:'space; interval; between; period of time',cat:'フィールド'},
      {w:'短パン',r:'たんぱん',m:'shorts; short pants',cat:'フィールド'},
      {w:'小僧',r:'こぞう',m:'brat; kid; young boy (slightly rude term)',cat:'フィールド'},
      {w:'倒す',r:'たおす',m:'to knock down; to defeat; to beat',cat:'フィールド'},
      {w:'替える',r:'かえる',m:'to replace; to substitute; to switch (cf. 変える = to change)',cat:'フィールド'},
      {w:'入れる',r:'いれる',m:'to put in; to insert; to include; to let in',cat:'フィールド'},
      {w:'負ける',r:'まける',m:'to lose; to be defeated',cat:'フィールド'},
      {w:'休みます',r:'やすみます',m:'to rest; to take a break (polite form of 休む)',cat:'フィールド'},
      // ── わざ ─────────────────────────────────────────────────────────
      {w:'体当たり',r:'たいあたり',m:'Tackle — throw oneself bodily at the target',cat:'わざ'},
      {w:'睨みつける',r:'にらみつける',m:'Leer — glare hard at the target to lower its Defense',cat:'わざ'},
      {w:'蔓の鞭',r:'つるのむち',m:'Vine Whip — whip the target with slender vines',cat:'わざ'},
      {w:'引っ掻く',r:'ひっかく',m:'Scratch — scratch the target with sharp claws',cat:'わざ'},
      {w:'巻きつく',r:'まきつく',m:'Wrap — coil around and squeeze the target for multiple turns',cat:'わざ'},
    ],
  },

  acnh: {
    label: 'どうぶつの森',
    diff: 'N5–N4',
    cats: ['すべて', '日常', 'どうぐ', 'しぜん', 'むらびと', 'いえ'],
    vocab: [
      // ── 日常 ─────────────────────────────────────────────────────────
      {w:'たぬきち',r:'たぬきち',m:'Tom Nook',cat:'むらびと'},
      {w:'しずえ',r:'しずえ',m:'Isabelle',cat:'むらびと'},
      {w:'もりのくらし',r:'もりのくらし',m:'island life; living in the village',cat:'日常'},
      {w:'まいにちのせいかつ',r:'まいにちのせいかつ',m:'daily life',cat:'日常'},
      {w:'おはなし',r:'おはなし',m:'talking; conversation (polite)',cat:'日常'},
      {w:'ごあいさつ',r:'ごあいさつ',m:'greeting (polite)',cat:'日常'},
      {w:'にっか',r:'にっか',m:'daily schedule; program',cat:'日常'},
      {w:'かいもの',r:'かいもの',m:'shopping',cat:'日常'},
      {w:'かせぐ',r:'かせぐ',m:'to earn (money, miles)',cat:'日常'},
      {w:'ローン',r:'ローン',m:'loan; mortgage',cat:'日常'},
      {w:'かえす',r:'かえす',m:'to pay back; to return',cat:'日常'},
      {w:'マイル',r:'マイル',m:'Nook Miles',cat:'日常'},
      {w:'おいのり',r:'おいのり',m:'prayer; wishing on a star',cat:'日常'},
      {w:'まつり',r:'まつり',m:'festival',cat:'日常'},
      {w:'きねんび',r:'きねんび',m:'anniversary; special day',cat:'日常'},
      // ── どうぐ ───────────────────────────────────────────────────────
      {w:'つりざお',r:'つりざお',m:'fishing rod',cat:'どうぐ'},
      {w:'あみ',r:'あみ',m:'net; bug net',cat:'どうぐ'},
      {w:'スコップ',r:'スコップ',m:'shovel',cat:'どうぐ'},
      {w:'ジョウロ',r:'ジョウロ',m:'watering can',cat:'どうぐ'},
      {w:'おの',r:'おの',m:'axe',cat:'どうぐ'},
      {w:'パチンコ',r:'パチンコ',m:'slingshot',cat:'どうぐ'},
      {w:'はしご',r:'はしご',m:'ladder; stepladder',cat:'どうぐ'},
      {w:'さおだけ',r:'さおだけ',m:'vaulting pole',cat:'どうぐ'},
      {w:'かいちゅうでんとう',r:'かいちゅうでんとう',m:'flashlight; torch',cat:'どうぐ'},
      {w:'スマホ',r:'スマホ',m:'smartphone (NookPhone)',cat:'どうぐ'},
      {w:'きれいなみず',r:'きれいなみず',m:'fresh water; watering',cat:'どうぐ'},
      // ── しぜん ───────────────────────────────────────────────────────
      {w:'さかな',r:'さかな',m:'fish',cat:'しぜん'},
      {w:'むし',r:'むし',m:'bug; insect',cat:'しぜん'},
      {w:'はな',r:'はな',m:'flower',cat:'しぜん'},
      {w:'き',r:'き',m:'tree',cat:'しぜん'},
      {w:'くだもの',r:'くだもの',m:'fruit',cat:'しぜん'},
      {w:'しましまのかぶ',r:'しましまのかぶ',m:'turnip (Stalk Market)',cat:'しぜん'},
      {w:'ほし',r:'ほし',m:'star',cat:'しぜん'},
      {w:'りゅうせい',r:'りゅうせい',m:'shooting star; meteor',cat:'しぜん'},
      {w:'おちば',r:'おちば',m:'fallen leaves',cat:'しぜん'},
      {w:'ゆき',r:'ゆき',m:'snow',cat:'しぜん'},
      {w:'かわ',r:'かわ',m:'river',cat:'しぜん'},
      {w:'うみ',r:'うみ',m:'sea; ocean',cat:'しぜん'},
      {w:'がけ',r:'がけ',m:'cliff',cat:'しぜん'},
      {w:'たきつぼ',r:'たきつぼ',m:'waterfall pool',cat:'しぜん'},
      {w:'かぶ',r:'かぶ',m:'turnip; stock (Stalk Market)',cat:'しぜん'},
      // ── むらびと ─────────────────────────────────────────────────────
      {w:'むらびと',r:'むらびと',m:'villager; island resident',cat:'むらびと'},
      {w:'しまのせいかつ',r:'しまのせいかつ',m:'island life',cat:'むらびと'},
      {w:'あそびにくる',r:'あそびにくる',m:'to come to visit; come hang out',cat:'むらびと'},
      {w:'プレゼント',r:'プレゼント',m:'present; gift',cat:'むらびと'},
      {w:'てがみ',r:'てがみ',m:'letter',cat:'むらびと'},
      {w:'なかよし',r:'なかよし',m:'close friends; getting along well',cat:'むらびと'},
      {w:'ともだちコード',r:'ともだちコード',m:'friend code',cat:'むらびと'},
      // ── いえ ─────────────────────────────────────────────────────────
      {w:'かぐ',r:'かぐ',m:'furniture',cat:'いえ'},
      {w:'かべがみ',r:'かべがみ',m:'wallpaper',cat:'いえ'},
      {w:'ゆか',r:'ゆか',m:'flooring',cat:'いえ'},
      {w:'おへや',r:'おへや',m:'room (polite)',cat:'いえ'},
      {w:'インテリア',r:'インテリア',m:'interior design',cat:'いえ'},
      {w:'テント',r:'テント',m:'tent',cat:'いえ'},
      {w:'いえ',r:'いえ',m:'house; home',cat:'いえ'},
      {w:'かんせい',r:'かんせい',m:'completion; finished',cat:'いえ'},
      {w:'DIY',r:'ディーアイワイ',m:'DIY crafting',cat:'いえ'},
      {w:'レシピ',r:'レシピ',m:'recipe; crafting formula',cat:'いえ'},
    ]
  },

  dq11: {
    label: 'DQ XI',
    diff: 'N4–N3',
    cats: ['すべて', 'バトル', 'じゅもん', 'アイテム', 'ストーリー', 'しょくぎょう', 'まち', 'かいわ', 'セリフ'],
    // セリフ = dialogue comprehension questions (separate from vocab)
    dialogues: [
      // ── やどや・まちのNPC ────────────────────────────────────────────
      {
        s:'ゆっくりお休みください。旅の疲れをいやしていってくださいね。',
        r:'ゆっくりおやすみください。たびのつかれをいやしていってくださいね。',
        sp:'やどや',
        a:'Please rest well. Let yourself recover from the fatigue of your journey.',
        c:[
          'Please rest well. Let yourself recover from the fatigue of your journey.',
          'You look tired. Have you been travelling long? Where are you headed?',
          'We\'re fully booked tonight, I\'m afraid. Please try again tomorrow.',
          'You can rest here, but watch out — monsters have been seen nearby.',
        ],
        e:'疲れをいやす = to soothe / recover from fatigue. いやしていって = "go and heal yourself here"',
      },
      {
        s:'このあたりでは魔物が増えていて、夜は外に出られないんですよ。本当に困っています。',
        r:'このあたりではまものがふえていて、よるはそとにでられないんですよ。ほんとうにこまっています。',
        sp:'村人',
        a:'Monsters have been increasing around here, so we can\'t go outside at night. We\'re really struggling.',
        c:[
          'Monsters have been increasing around here, so we can\'t go outside at night. We\'re really struggling.',
          'The monsters here only come out at night, so travelling in the day is fine.',
          'We\'ve been catching lots of monsters lately. It\'s actually been quite profitable.',
          'The monsters left after a hero defeated them. Things have been peaceful since.',
        ],
        e:'増えている = increasing (ている = ongoing state). 出られない = cannot go out (potential negative). 困っています = we are troubled / struggling',
      },
      {
        s:'西に進むと、デルカダール王国があります。国王様にご用がおありなのですか？',
        r:'にしにすすむと、デルカダールおうこくがあります。こくおうさまにごようがおありなのですか？',
        sp:'村人',
        a:'If you go west, you\'ll find the Kingdom of Heliodor. Do you have business with the king?',
        c:[
          'If you go west, you\'ll find the Kingdom of Heliodor. Do you have business with the king?',
          'The Kingdom of Heliodor is to the east. The king is expecting you.',
          'The road west is blocked. You\'ll need permission from the king to pass.',
          'Heliodor is far to the north. Few travellers make it there safely.',
        ],
        e:'〜に進む = to advance / head towards ~. ご用がおありですか = polite "do you have business/an errand?"',
      },
      {
        s:'道具屋でやくそうをたくさん買っておくといいですよ。この先の洞窟は手強いらしいので。',
        r:'どうぐやでやくそうをたくさんかっておくといいですよ。このさきのどうくつはてごわいらしいので。',
        sp:'村人',
        a:'You should stock up on medicinal herbs at the item shop. Apparently the cave ahead is tough.',
        c:[
          'You should stock up on medicinal herbs at the item shop. Apparently the cave ahead is tough.',
          'The item shop sells herbs, but they\'re expensive. You\'re better off finding them in the cave.',
          'Don\'t bother with herbs — the monsters in the cave drop plenty of items.',
          'The item shop is closed today. You\'ll have to manage without supplies.',
        ],
        e:'〜ておく = do in advance / stock up. 手強い = tough / formidable. 〜らしい = apparently / I hear that',
      },
      {
        s:'まおうが現れてから、世界はずっと暗くなる一方だ。誰かが何とかしてくれないと…。',
        r:'まおうがあらわれてから、せかいはずっとくらくなるいっぽうだ。だれかがなんとかしてくれないと…。',
        sp:'村人',
        a:'Ever since the Dark Lord appeared, the world has only been getting darker. If someone doesn\'t do something…',
        c:[
          'Ever since the Dark Lord appeared, the world has only been getting darker. If someone doesn\'t do something…',
          'The Dark Lord appeared once before, but a hero defeated him. It will happen again.',
          'People say the world is getting darker, but I think things will improve on their own.',
          'Since the Dark Lord appeared, trade has boomed. Dark times can be profitable.',
        ],
        e:'〜て以来 / から = ever since ~. 〜一方だ = keeps doing ~; only getting more ~. 何とかする = to do something about it',
      },
      {
        s:'勇者のしるしを持つ者が、いつかこの地に現れると言い伝えられておる。',
        r:'ゆうしゃのしるしをもつものが、いつかこのちにあらわれるといいつたえられておる。',
        sp:'長老',
        a:'It is passed down in legend that one who bears the mark of the hero will one day appear in this land.',
        c:[
          'It is passed down in legend that one who bears the mark of the hero will one day appear in this land.',
          'The hero\'s mark was lost long ago. No one alive has ever seen it.',
          'A person bearing the mark appeared here before, but they failed and disappeared.',
          'The mark of the hero is said to choose its bearer — you cannot seek it out.',
        ],
        e:'〜と言い伝えられている = it is passed down / legend has it that ~. 〜おる = archaic/dialect form of いる (elder speech)',
      },
      // ── ロウ（老人口調：〜じゃ）───────────────────────────────────
      {
        s:'そうじゃ、お主が本当の勇者なのじゃ。ワシはずっと信じておったぞ。',
        r:'そうじゃ、おぬしがほんとうのゆうしゃなのじゃ。わしはずっとしんじておったぞ。',
        sp:'ロウ',
        a:'That\'s right — you are the true Luminary. I always believed in you.',
        c:[
          'That\'s right — you are the true Luminary. I always believed in you.',
          'So you really think you\'re the hero? You still have much to prove, I\'m afraid.',
          'Is that so? Others have claimed to be the hero before. I\'ll wait and see.',
          'You\'re the hero? I had my doubts, but perhaps the mark doesn\'t lie.',
        ],
        e:'お主 = archaic "you" (used by elders). 〜のじゃ = elder sentence-ender (= 〜のだ). 信じておった = had been believing (past progressive, archaic)',
      },
      {
        s:'この先の道は険しいのじゃ。じゃが、お主ならきっと乗り越えられるじゃろう。',
        r:'このさきのみちはけわしいのじゃ。じゃが、おぬしならきっとのりこえられるじゃろう。',
        sp:'ロウ',
        a:'The road ahead is steep and harsh. But knowing you, you will surely overcome it.',
        c:[
          'The road ahead is steep and harsh. But knowing you, you will surely overcome it.',
          'The road ahead is easy enough. Even alone you should have no trouble.',
          'The road is too dangerous. I cannot allow you to go any further.',
          'The path is long. We should rest here before continuing tomorrow.',
        ],
        e:'険しい = steep / harsh / severe. じゃが = elder form of "but / however". 乗り越えられる = can overcome / surmount',
      },
      {
        s:'無茶だけはしないでくれよ。お主のことが心配なんじゃ。',
        r:'むちゃだけはしないでくれよ。おぬしのことがしんぱいなんじゃ。',
        sp:'ロウ',
        a:'Just please don\'t do anything reckless. I\'m worried about you.',
        c:[
          'Just please don\'t do anything reckless. I\'m worried about you.',
          'Go ahead and take risks — that\'s what being a hero is about. I\'m proud of you.',
          'Don\'t hold back. The enemy is reckless, so you need to be too.',
          'You worry too much. I\'m fine — focus on the mission.',
        ],
        e:'無茶をする = to be reckless / overdo it. 〜ないでくれ = please don\'t ~. 心配 = worried / concerned',
      },
      {
        s:'あの山の向こうに、古い神殿があるのじゃ。そこに伝説の武器が眠っておるらしい。',
        r:'あのやまのむこうに、ふるいしんでんがあるのじゃ。そこにでんせつのぶきがねむっておるらしい。',
        sp:'ロウ',
        a:'Beyond that mountain, there is an ancient temple. A legendary weapon is said to sleep there.',
        c:[
          'Beyond that mountain, there is an ancient temple. A legendary weapon is said to sleep there.',
          'There\'s nothing beyond that mountain — I\'ve checked. Don\'t waste your time.',
          'The temple beyond the mountain is cursed. No one who entered has ever returned.',
          'The mountain ahead has no temple. The legend you heard is just a rumour.',
        ],
        e:'向こう = beyond / the other side. 古い = old / ancient. 〜が眠っている = ~ lies dormant / sleeps. 〜らしい = apparently / I hear',
      },
      // ── エリック（タメ口・若者言葉）──────────────────────────────────
      {
        s:'おいおい、マジかよ。あんな数の魔物、どうやって倒すんだよ。',
        r:'おいおい、まじかよ。あんなかずのまもの、どうやってたおすんだよ。',
        sp:'エリック',
        a:'Whoa whoa, are you serious? How are we supposed to beat that many monsters?',
        c:[
          'Whoa whoa, are you serious? How are we supposed to beat that many monsters?',
          'Hey, look at all those monsters! This is going to be so easy for us.',
          'Hmm, there are a lot of enemies. I\'ve handled worse though. Let\'s go.',
          'Oh no, monsters ahead. You go first — I\'ll cover you from behind.',
        ],
        e:'おいおい = "hey hey / whoa" (casual surprise). マジかよ = "seriously? / for real?" (casual). あんな = "that kind of / that many (over there)"',
      },
      {
        s:'まあ、なんとかなるって。俺たちがいるんだから、心配すんなよ。',
        r:'まあ、なんとかなるって。おれたちがいるんだから、しんぱいすんなよ。',
        sp:'エリック',
        a:'Eh, it\'ll work out. We\'re here with you, so don\'t worry.',
        c:[
          'Eh, it\'ll work out. We\'re here with you, so don\'t worry.',
          'Actually, I\'m not sure we can win this one. We should think carefully.',
          'I know it looks bad, but run if you have to — no shame in it.',
          'It\'s not going to work out. We need to find another way.',
        ],
        e:'なんとかなる = it\'ll work out somehow. 〜って = casual sentence-ender (assertion). 心配すんな = don\'t worry (すんな = casual negative command of する)',
      },
      {
        s:'この戦いが終わったら、みんなでゆっくり旅をしようじゃないか。',
        r:'このたたかいがおわったら、みんなでゆっくりたびをしようじゃないか。',
        sp:'エリック',
        a:'When this battle is over, let\'s all travel together at our own pace.',
        c:[
          'When this battle is over, let\'s all travel together at our own pace.',
          'After this, I\'m going back home. I\'ve had enough of travelling.',
          'This battle might be our last. Let\'s make it count.',
          'Once we win, the others can go. I\'ll stay and keep watch.',
        ],
        e:'〜たら = when/after ~ (conditional on completion). 〜ようじゃないか = "let\'s ~, shall we?" (casual suggestion)',
      },
      {
        s:'ちょっと待ってくれ。なんか嫌な予感がするんだよな…。',
        r:'ちょっとまってくれ。なんかいやなよかんがするんだよな…。',
        sp:'エリック',
        a:'Hold on. I\'ve got a bad feeling about this somehow…',
        c:[
          'Hold on. I\'ve got a bad feeling about this somehow…',
          'All good — I checked ahead and it\'s clear. Let\'s keep moving.',
          'Don\'t pay attention to feelings. Just keep going.',
          'I actually feel great about this. Best odds we\'ve had in a while.',
        ],
        e:'ちょっと待ってくれ = "hold on / wait a sec" (casual). 嫌な予感 = bad feeling / ominous premonition. 〜がするんだよな = "I\'ve got a feeling that ~" (casual, seeking agreement)',
      },
      // ── ベロニカ（お嬢様口調：〜ですわ）─────────────────────────────
      {
        s:'わたくしの魔法の腕前、とくとごらんなさいですわ！',
        r:'わたくしのまほうのうでまえ、とくとごらんなさいですわ！',
        sp:'ベロニカ',
        a:'Take a good, close look at my magical skills!',
        c:[
          'Take a good, close look at my magical skills!',
          'Please lend me your magical power — mine isn\'t strong enough alone.',
          'Don\'t watch me — focus on the enemy. I can handle myself.',
          'My magic is a secret. I\'d rather you didn\'t watch.',
        ],
        e:'わたくし = formal "I" (refined feminine). とくとごらんなさい = "take a good look / watch closely" (instructive, slightly theatrical). 〜ですわ = refined feminine sentence-ender',
      },
      {
        s:'べ、別にあなたのことを心配してたわけじゃないんだからね！',
        r:'べ、べつにあなたのことをしんぱいしてたわけじゃないんだからね！',
        sp:'ベロニカ',
        a:'I-It\'s not like I was worried about you or anything!',
        c:[
          'I-It\'s not like I was worried about you or anything!',
          'Of course I was worried about you. Don\'t do that again.',
          'I wasn\'t watching you at all. I had my own things to deal with.',
          'Why would I be worried? You\'re the hero. You\'ll be fine.',
        ],
        e:'Classic tsundere line. 別に〜わけじゃない = "it\'s not like ~". 〜だからね！ = assertive self-justification. The hesitation (べ、別に) signals embarrassment.',
      },
      // ── セーニャ（丁寧・やさしい口調）──────────────────────────────
      {
        s:'あなたの力を信じています。どうか、無事でいてください。',
        r:'あなたのちからをしんじています。どうか、ぶじでいてください。',
        sp:'セーニャ',
        a:'I believe in your strength. Please, stay safe.',
        c:[
          'I believe in your strength. Please, stay safe.',
          'I\'m not sure you can do this alone. Let me come with you.',
          'Your power is fading. Please rest before you go any further.',
          'I believe in you, but please be careful — I have a bad feeling.',
        ],
        e:'〜を信じています = I believe in ~. どうか = please (earnest, emotional). 無事でいる = to be safe / to remain unharmed',
      },
      {
        s:'みんなで力を合わせれば、きっと乗り越えられます。あきらめないでください。',
        r:'みんなでちからをあわせれば、きっとのりこえられます。あきらめないでください。',
        sp:'セーニャ',
        a:'If we all combine our strength, we can surely overcome this. Please don\'t give up.',
        c:[
          'If we all combine our strength, we can surely overcome this. Please don\'t give up.',
          'Our combined strength isn\'t enough. We need to find another way.',
          'I know it\'s hard, but sometimes giving up is the right choice.',
          'I\'ll combine my strength with yours, but the others can\'t help us here.',
        ],
        e:'力を合わせる = to combine strength / join forces. 〜ば = if ~ (conditional). 乗り越えられる = can overcome. あきらめないで = don\'t give up',
      },
      {
        s:'神様、どうかみんなを守ってください。この祈りが届きますように。',
        r:'かみさま、どうかみんなをまもってください。このいのりがとどきますように。',
        sp:'セーニャ',
        a:'O gods, please protect everyone. May this prayer reach you.',
        c:[
          'O gods, please protect everyone. May this prayer reach you.',
          'The gods haven\'t answered our prayers. We need to act ourselves.',
          'I\'ve given up on praying. We need action, not words.',
          'Prayers are just words. Focus on what we can actually do.',
        ],
        e:'どうか = please (earnest). 〜ますように = "may ~ happen; I pray that ~" (wish/prayer). 届く = to reach / to be heard',
      },
      // ── グレイグ（武人口調：〜ぬ / 〜だ）────────────────────────────
      {
        s:'お前が勇者だというなら、その力を見せてみろ。言葉だけでは信じられぬ。',
        r:'おまえがゆうしゃだというなら、そのちからをみせてみろ。ことばだけではしんじられぬ。',
        sp:'グレイグ',
        a:'If you claim to be the hero, show me your strength. I cannot believe words alone.',
        c:[
          'If you claim to be the hero, show me your strength. I cannot believe words alone.',
          'So you are the hero. I\'ve been waiting for you — your reputation precedes you.',
          'The hero, you say? I\'ll take your word for it. We need all the help we can get.',
          'You don\'t need to prove anything to me. The mark speaks for itself.',
        ],
        e:'〜というなら = if you say / if you claim ~. 見せてみろ = show me (strong command). 〜ぬ = archaic/formal negative (= 〜ない), used by stern warrior types',
      },
      {
        s:'国を守るのが我らの使命だ。たとえ命を賭けることになろうとも。',
        r:'くにをまもるのがわれらのしめいだ。たとえいのちをかけることになろうとも。',
        sp:'グレイグ',
        a:'Protecting the kingdom is our duty. Even if it means risking our lives.',
        c:[
          'Protecting the kingdom is our duty. Even if it means risking our lives.',
          'Protecting the kingdom is important, but we must also protect ourselves first.',
          'Our duty to the kingdom is over. Now we fight for ourselves.',
          'The king has ordered us to retreat. Protecting the kingdom means surviving.',
        ],
        e:'我ら = archaic "we / us" (soldier speech). 使命 = duty / mission. たとえ〜とも = even if ~. 命を賭ける = to risk one\'s life',
      },
      // ── シルビア（明るい・陽気な口調）──────────────────────────────
      {
        s:'ダーリン、諦めちゃダメよ！あたしたちはあなたのそばにいるんだから！',
        r:'ダーリン、あきらめちゃダメよ！あたしたちはあなたのそばにいるんだから！',
        sp:'シルビア',
        a:'Darling, don\'t you dare give up! We\'re right here beside you!',
        c:[
          'Darling, don\'t you dare give up! We\'re right here beside you!',
          'Darling, I think we should give up this time. It\'s too much for us.',
          'Darling, I\'ll be right back. Just hold on without me for now.',
          'Darling, this is too dangerous. We should run while we still can.',
        ],
        e:'ダーリン = Sylvando\'s affectionate address. 諦めちゃダメ = "you absolutely mustn\'t give up" (〜ちゃダメ = mustn\'t ~). そばにいる = to be by one\'s side',
      },
      {
        s:'このシルビアさまが盛り上げてあげますわよ！元気を出して！',
        r:'このシルビアさまがもりあげてあげますわよ！げんきをだして！',
        sp:'シルビア',
        a:'The great Sylvando will liven things up for you! Cheer up!',
        c:[
          'The great Sylvando will liven things up for you! Cheer up!',
          'Sylvando will calm things down. Everyone needs to focus right now.',
          'I can\'t help today — I\'m not feeling my best.',
          'Don\'t look at me. I\'m really not the cheerful type.',
        ],
        e:'〜さま after own name = theatrical self-address (grandiose). 盛り上げる = to liven up / hype up. 元気を出す = to cheer up / summon energy',
      },
      // ── ストーリー・感情的な場面 ──────────────────────────────────────
      {
        s:'まさか…。あの人が敵だったとは、信じたくないが、現実を受け入れるしかない。',
        r:'まさか…。あのひとがてきだったとは、しんじたくないが、げんじつをうけいれるしかない。',
        sp:'パーティー',
        a:'No way…. I don\'t want to believe that person was our enemy, but we have no choice but to accept reality.',
        c:[
          'No way…. I don\'t want to believe that person was our enemy, but we have no choice but to accept reality.',
          'Of course that person was the enemy — I always suspected it.',
          'That person helped us all along. We\'d be nothing without them.',
          'The enemy fooled us into thinking that person was our ally. We\'ve been betrayed.',
        ],
        e:'まさか = "no way / surely not" (shock). 〜だったとは = "that ~ was the case" (shocked realization). 受け入れるしかない = have no choice but to accept',
      },
      {
        s:'いったい、何が起きているんだ…？こんなはずじゃなかったのに。',
        r:'いったい、なにがおきているんだ…？こんなはずじゃなかったのに。',
        sp:'エリック',
        a:'What on earth is going on…? This isn\'t how it was supposed to be.',
        c:[
          'What on earth is going on…? This isn\'t how it was supposed to be.',
          'Everything is going exactly as planned. This is what we hoped for.',
          'I know what\'s happening. I\'ve seen this before — don\'t panic.',
          'Something is happening, but it\'s nothing to worry about. Trust me.',
        ],
        e:'いったい = "on earth / just what" (intensifier in questions). こんなはずじゃなかった = "it wasn\'t supposed to be like this" — very common JRPG line',
      },
      {
        s:'世界を救うのに、ひとりの力では足りない。仲間を信じて、共に戦うしかないんだ。',
        r:'せかいをすくうのに、ひとりのちからではたりない。なかまをしんじて、ともにたたかうしかないんだ。',
        sp:'ナレーション',
        a:'To save the world, the power of one person is not enough. All you can do is believe in your companions and fight together.',
        c:[
          'To save the world, the power of one person is not enough. All you can do is believe in your companions and fight together.',
          'To save the world, you must become stronger alone. Relying on others is a weakness.',
          'The world can be saved, but not through battle. You must find a peaceful solution.',
          'One person\'s power is enough. You just need to believe in yourself.',
        ],
        e:'〜のに = in order to ~. 足りない = not enough / insufficient. 信じて = believing in (て = and then / by). 〜しかない = have no choice but to ~',
      },
      {
        s:'たとえ何度倒されても、また立ち上がる。それが勇者というものだ。',
        r:'たとえなんどたおされても、またたちあがる。それがゆうしゃというものだ。',
        sp:'ロウ',
        a:'No matter how many times you are knocked down, you rise again. That is what it means to be a hero.',
        c:[
          'No matter how many times you are knocked down, you rise again. That is what it means to be a hero.',
          'A hero should never fall. If you are defeated, your journey is over.',
          'Being a hero means never fighting alone. Never face an enemy by yourself.',
          'A hero knows when to retreat. Living to fight another day is true courage.',
        ],
        e:'たとえ〜ても = even if ~; no matter how ~. 何度 = how many times. 立ち上がる = to stand up / rise again. 〜というものだ = that is what ~ is; that\'s the nature of ~',
      },
      {
        s:'この呪いを解くには、せかいじゅの雫が必要じゃ。じゃが、あれを手に入れるのは容易ではないぞ。',
        r:'こののろいをとくには、せかいじゅのしずくがひつようじゃ。じゃが、あれをてにいれるのはよういではないぞ。',
        sp:'ロウ',
        a:'To break this curse, the Yggdrasil Dew is needed. However, obtaining it is no easy matter.',
        c:[
          'To break this curse, the Yggdrasil Dew is needed. However, obtaining it is no easy matter.',
          'The curse can be broken with holy water. You can buy it at the item shop.',
          'The Yggdrasil Dew will break the curse, and it\'s easy to get — I know where it is.',
          'There\'s no known way to break this curse. We must find another solution.',
        ],
        e:'〜を解く = to break / undo ~ (a curse, a code, a problem). 〜には〜が必要 = ~ is needed in order to ~. 容易ではない = not easy / no easy feat',
      },
      {
        s:'あなたに出会えてよかった。これからも、ずっと一緒にいてください。',
        r:'あなたにであえてよかった。これからも、ずっといっしょにいてください。',
        sp:'セーニャ',
        a:'I\'m so glad I met you. Please stay with us — always.',
        c:[
          'I\'m so glad I met you. Please stay with us — always.',
          'I\'m glad we met, but our journey together ends here. Go on without me.',
          'Meeting you changed everything. But I think it\'s time for us to part ways.',
          'I\'m glad to have met you. I hope our paths cross again someday.',
        ],
        e:'〜に出会えてよかった = I\'m glad I was able to meet ~. これからも = from now on too / going forward. ずっと = always / the whole time',
      },
      {
        s:'勇者よ、世界の命運はお前の肩にかかっている。',
        r:'ゆうしゃよ、せかいのめいうんはおまえのかたにかかっている。',
        sp:'長老',
        a:'O hero, the fate of the world rests on your shoulders.',
        c:[
          'O hero, the fate of the world rests on your shoulders.',
          'O hero, the fate of the world is in good hands. We\'re not worried.',
          'The world\'s fate has been decided — there\'s nothing left to do.',
          'The world doesn\'t need a single hero. We just need everyone to work together.',
        ],
        e:'〜よ = vocative particle (direct address). 命運 = fate / destiny (formal, weighty). 肩にかかっている = rests on one\'s shoulders (idiom)',
      },
      {
        s:'こんな所で…終わりたくない。もっと強くならなければ。',
        r:'こんなところで…おわりたくない。もっとつよくならなければ。',
        sp:'パーティー',
        a:'I don\'t want it to end here…. I have to get stronger.',
        c:[
          'I don\'t want it to end here…. I have to get stronger.',
          'This is actually a fine place to stop. I\'m happy to end here.',
          'It ends here for me. The others should carry on without me.',
          'Ending here is fine. We\'ve already done more than enough.',
        ],
        e:'こんな所で = "in a place like this / here of all places". 〜たくない = don\'t want to ~. 〜なければ = must; have to (〜なければならない contracted)',
      },
    ],
    vocab: [
      // ── バトル ───────────────────────────────────────────────────────
      {w:'攻撃',r:'こうげき',m:'attack',cat:'バトル'},
      {w:'防御',r:'ぼうぎょ',m:'defense; defend',cat:'バトル'},
      {w:'特技',r:'とくぎ',m:'special skill; ability',cat:'バトル'},
      {w:'呪文',r:'じゅもん',m:'magic spell',cat:'バトル'},
      {w:'どうぐをつかう',r:'どうぐをつかう',m:'use an item',cat:'バトル'},
      {w:'逃げる',r:'にげる',m:'flee; run away',cat:'バトル'},
      {w:'MP',r:'エムピー',m:'MP (Magic Points)',cat:'バトル'},
      {w:'HP',r:'エイチピー',m:'HP (Hit Points)',cat:'バトル'},
      {w:'力',r:'ちから',m:'strength; power',cat:'バトル'},
      {w:'素早さ',r:'すばやさ',m:'agility; speed',cat:'バトル'},
      {w:'身の守り',r:'みのまもり',m:'defense stat; protection',cat:'バトル'},
      {w:'回復',r:'かいふく',m:'recovery; healing',cat:'バトル'},
      {w:'戦闘',r:'せんとう',m:'battle; combat',cat:'バトル'},
      {w:'先どり',r:'さきどり',m:'pre-emptive strike; first move',cat:'バトル'},
      {w:'一撃必殺',r:'いちげきひっさつ',m:'one-hit kill; instant kill',cat:'バトル'},
      {w:'連続攻撃',r:'れんぞくこうげき',m:'combo attack; consecutive hits',cat:'バトル'},
      {w:'会心',r:'かいしん',m:'critical hit (DQ term)',cat:'バトル'},
      {w:'マヒ',r:'マヒ',m:'paralysis (status)',cat:'バトル'},
      {w:'毒',r:'どく',m:'poison (status)',cat:'バトル'},
      {w:'眠り',r:'ねむり',m:'sleep (status)',cat:'バトル'},
      {w:'混乱',r:'こんらん',m:'confusion (status)',cat:'バトル'},
      {w:'マホトーン',r:'マホトーン',m:'Fizzle — seals enemy spells',cat:'バトル'},
      {w:'テンション',r:'テンション',m:'Tension (charge mechanic)',cat:'バトル'},
      {w:'ゾーン',r:'ゾーン',m:'Pep (Zone state — party power-up)',cat:'バトル'},
      {w:'連携',r:'れんけい',m:'combination move (Pep skill)',cat:'バトル'},
      {w:'経験値',r:'けいけんち',m:'experience points (EXP)',cat:'バトル'},
      {w:'レベルアップ',r:'レベルアップ',m:'level up',cat:'バトル'},
      {w:'ゴールド',r:'ゴールド',m:'Gold (currency)',cat:'バトル'},
      // ── じゅもん ─────────────────────────────────────────────────────
      {w:'ホイミ',r:'ホイミ',m:'Heal — restores a little HP',cat:'じゅもん'},
      {w:'ベホイミ',r:'ベホイミ',m:'Midheal — restores moderate HP',cat:'じゅもん'},
      {w:'ベホマ',r:'ベホマ',m:'Fullheal — fully restores one ally\'s HP',cat:'じゅもん'},
      {w:'ベホマズン',r:'ベホマズン',m:'Omniheal — fully heals the whole party',cat:'じゅもん'},
      {w:'ザオ',r:'ザオ',m:'Zing — 50% chance to revive fallen ally',cat:'じゅもん'},
      {w:'ザオリク',r:'ザオリク',m:'Kazing — fully revives a fallen ally',cat:'じゅもん'},
      {w:'メラ',r:'メラ',m:'Frizz — small fire attack',cat:'じゅもん'},
      {w:'メラミ',r:'メラミ',m:'Frizzle — medium fire attack',cat:'じゅもん'},
      {w:'メラゾーマ',r:'メラゾーマ',m:'Kafrizzle — powerful fire attack',cat:'じゅもん'},
      {w:'ギラ',r:'ギラ',m:'Sizz — small fire (all enemies)',cat:'じゅもん'},
      {w:'ベギラマ',r:'ベギラマ',m:'Sizzle — medium fire (all enemies)',cat:'じゅもん'},
      {w:'ヒャド',r:'ヒャド',m:'Crack — small ice attack',cat:'じゅもん'},
      {w:'ヒャダルコ',r:'ヒャダルコ',m:'Crackle — medium ice (all enemies)',cat:'じゅもん'},
      {w:'バギ',r:'バギ',m:'Whoosh — small wind attack',cat:'じゅもん'},
      {w:'バギマ',r:'バギマ',m:'Swoosh — medium wind (all enemies)',cat:'じゅもん'},
      {w:'イオ',r:'イオ',m:'Bang — small explosion (all enemies)',cat:'じゅもん'},
      {w:'イオラ',r:'イオラ',m:'Boom — medium explosion (all enemies)',cat:'じゅもん'},
      {w:'デイン',r:'デイン',m:'Zap — lightning (one enemy)',cat:'じゅもん'},
      {w:'ザキ',r:'ザキ',m:'Whack — instant death (one enemy)',cat:'じゅもん'},
      {w:'ルーラ',r:'ルーラ',m:'Zoom — teleport to visited towns',cat:'じゅもん'},
      {w:'リレミト',r:'リレミト',m:'Evac — escape from a dungeon',cat:'じゅもん'},
      {w:'マホカンタ',r:'マホカンタ',m:'Bounce — reflects enemy spells',cat:'じゅもん'},
      {w:'スカラ',r:'スカラ',m:'Buff — raises one ally\'s defence',cat:'じゅもん'},
      {w:'バイキルト',r:'バイキルト',m:'Oomph — doubles one ally\'s attack',cat:'じゅもん'},
      {w:'フバーハ',r:'フバーハ',m:'Insulatle — reduces breath damage',cat:'じゅもん'},
      // ── アイテム ─────────────────────────────────────────────────────
      {w:'薬草',r:'やくそう',m:'medicinal herb — restores ~30 HP',cat:'アイテム'},
      {w:'上やくそう',r:'じょうやくそう',m:'superior herb — restores ~75 HP',cat:'アイテム'},
      {w:'毒けし草',r:'どくけしそう',m:'antidote herb — cures poison',cat:'アイテム'},
      {w:'満月草',r:'まんげつそう',m:'moonwort bulb — cures sleep/confusion',cat:'アイテム'},
      {w:'聖水',r:'せいすい',m:'holy water — repels weaker monsters',cat:'アイテム'},
      {w:'キメラのつばさ',r:'キメラのつばさ',m:'chimera wing — return to last town (= Zoom)',cat:'アイテム'},
      {w:'毒針',r:'どくばり',m:'poison needle — may instantly kill',cat:'アイテム'},
      {w:'魔物よけのすず',r:'まものよけのすず',m:'repellent bell — reduces encounters',cat:'アイテム'},
      {w:'天空の剣',r:'てんくうのつるぎ',m:'Sword of Light — legendary weapon',cat:'アイテム'},
      {w:'魔法の聖水',r:'まほうのせいすい',m:'magic water — restores ~30 MP',cat:'アイテム'},
      {w:'エルフの飲み薬',r:'エルフののみぐすり',m:'elf elixir — restores ~60 MP',cat:'アイテム'},
      {w:'元気のもと',r:'げんきのもと',m:'yggdrasil dew — revives one ally with full HP',cat:'アイテム'},
      {w:'小さなメダル',r:'ちいさなメダル',m:'mini medal — collectible; trade for prizes',cat:'アイテム'},
      {w:'レシピブック',r:'レシピブック',m:'recipe book — unlocks forge recipes',cat:'アイテム'},
      {w:'ふしぎな鍛冶',r:'ふしぎなかじ',m:'Fun-Size Forge — item crafting system',cat:'アイテム'},
      // ── ストーリー ───────────────────────────────────────────────────
      {w:'英雄',r:'えいゆう',m:'hero; champion',cat:'ストーリー'},
      {w:'勇者',r:'ゆうしゃ',m:'Luminary; chosen hero',cat:'ストーリー'},
      {w:'予言',r:'よげん',m:'prophecy; prediction',cat:'ストーリー'},
      {w:'伝説',r:'でんせつ',m:'legend; legendary',cat:'ストーリー'},
      {w:'ろうし',r:'ろうし',m:'legendary hero (Erdwin — the old hero)',cat:'ストーリー'},
      {w:'魔王',r:'まおう',m:'Dark Lord; Demon King',cat:'ストーリー'},
      {w:'大魔王',r:'だいまおう',m:'Great Demon King (most powerful evil)',cat:'ストーリー'},
      {w:'ニズゼルファ',r:'ニズゼルファ',m:'Calasmos — the true final boss',cat:'ストーリー'},
      {w:'仲間',r:'なかま',m:'companion; party member',cat:'ストーリー'},
      {w:'試練',r:'しれん',m:'trial; ordeal',cat:'ストーリー'},
      {w:'定め',r:'さだめ',m:'fate; destiny',cat:'ストーリー'},
      {w:'呪い',r:'のろい',m:'curse',cat:'ストーリー'},
      {w:'復活',r:'ふっかつ',m:'revival; resurrection; comeback',cat:'ストーリー'},
      {w:'暗闇',r:'くらやみ',m:'darkness',cat:'ストーリー'},
      {w:'世界樹',r:'せかいじゅ',m:'Yggdrasil — the World Tree',cat:'ストーリー'},
      {w:'命',r:'いのち',m:'life; soul',cat:'ストーリー'},
      {w:'絆',r:'きずな',m:'bond; tie; connection (between characters)',cat:'ストーリー'},
      {w:'怒り',r:'いかり',m:'anger; rage; fury',cat:'ストーリー'},
      {w:'悲しみ',r:'かなしみ',m:'sorrow; sadness; grief',cat:'ストーリー'},
      {w:'喜び',r:'よろこび',m:'joy; delight; happiness',cat:'ストーリー'},
      {w:'許す',r:'ゆるす',m:'to forgive; to pardon',cat:'ストーリー'},
      {w:'戦う',r:'たたかう',m:'to fight; to battle; to struggle against',cat:'ストーリー'},
      {w:'倒す',r:'たおす',m:'to defeat; to bring down; to topple',cat:'ストーリー'},
      {w:'救う',r:'すくう',m:'to save; to rescue; to help',cat:'ストーリー'},
      {w:'諦めない',r:'あきらめない',m:'don\'t give up; refuse to quit',cat:'ストーリー'},
      {w:'まさか',r:'まさか',m:'no way; surely not; I can\'t believe it',cat:'ストーリー'},
      {w:'王国',r:'おうこく',m:'kingdom',cat:'ストーリー'},
      {w:'じょうけん',r:'じょうけん',m:'castle (palace)',cat:'ストーリー'},
      {w:'旅人',r:'たびびと',m:'traveler; wanderer',cat:'ストーリー'},
      {w:'冒険',r:'ぼうけん',m:'adventure',cat:'ストーリー'},
      {w:'奇跡',r:'きせき',m:'miracle',cat:'ストーリー'},
      {w:'平和',r:'へいわ',m:'peace',cat:'ストーリー'},
      // ── しょくぎょう ─────────────────────────────────────────────────
      {w:'剣士',r:'けんし',m:'swordsman (Erik\'s base class)',cat:'しょくぎょう'},
      {w:'魔法使い',r:'まほうつかい',m:'mage (Veronica\'s class)',cat:'しょくぎょう'},
      {w:'僧侶',r:'そうりょ',m:'priest; cleric (Serena\'s class)',cat:'しょくぎょう'},
      {w:'道具師',r:'どうぐし',m:'gadgeteer; item specialist (Sylvando)',cat:'しょくぎょう'},
      {w:'武器',r:'ぶき',m:'weapon',cat:'しょくぎょう'},
      {w:'鎧',r:'よろい',m:'armor',cat:'しょくぎょう'},
      {w:'盾',r:'たて',m:'shield',cat:'しょくぎょう'},
      {w:'剣',r:'けん',m:'sword',cat:'しょくぎょう'},
      {w:'ヤリ',r:'ヤリ',m:'spear',cat:'しょくぎょう'},
      {w:'ムチ',r:'ムチ',m:'whip (Jade\'s weapon)',cat:'しょくぎょう'},
      {w:'ブーメラン',r:'ブーメラン',m:'boomerang (Erik\'s weapon)',cat:'しょくぎょう'},
      {w:'杖',r:'つえ',m:'staff; cane (mage weapon)',cat:'しょくぎょう'},
      {w:'スキルパネル',r:'スキルパネル',m:'skill panel (character growth board)',cat:'しょくぎょう'},
      {w:'スキルポイント',r:'スキルポイント',m:'skill points (spent on skill panel)',cat:'しょくぎょう'},
      // ── まち ─────────────────────────────────────────────────────────
      {w:'宿屋',r:'やどや',m:'inn — rest to save & recover HP/MP',cat:'まち'},
      {w:'教会',r:'きょうかい',m:'church — save point & resurrect fallen allies',cat:'まち'},
      {w:'道具屋',r:'どうぐや',m:'item shop',cat:'まち'},
      {w:'武器屋',r:'ぶきや',m:'weapon shop',cat:'まち'},
      {w:'防具屋',r:'ぼうぐや',m:'armor shop',cat:'まち'},
      {w:'カジノ',r:'カジノ',m:'casino',cat:'まち'},
      {w:'銀行',r:'ぎんこう',m:'bank — item storage',cat:'まち'},
      {w:'酒場',r:'さかば',m:'tavern; bar',cat:'まち'},
      {w:'メダル王の城',r:'メダルおうのしろ',m:'Medal King\'s castle — trade mini medals',cat:'まち'},
      {w:'町',r:'まち',m:'town; city',cat:'まち'},
      {w:'村',r:'むら',m:'village',cat:'まち'},
      {w:'城',r:'しろ',m:'castle',cat:'まち'},
      {w:'洞窟',r:'どうくつ',m:'cave; dungeon',cat:'まち'},
      {w:'塔',r:'とう',m:'tower',cat:'まち'},
      {w:'森',r:'もり',m:'forest',cat:'まち'},
      {w:'荒野',r:'こうや',m:'wilderness; open field',cat:'まち'},
      {w:'港',r:'みなと',m:'harbor; port',cat:'まち'},
      {w:'船',r:'ふね',m:'ship; boat',cat:'まち'},
      {w:'泉',r:'いずみ',m:'spring; fountain (save/heal point)',cat:'まち'},
      {w:'魔法のカギ',r:'まほうのカギ',m:'magic key — unlocks locked doors in towns',cat:'まち'},
      {w:'宝箱',r:'たからばこ',m:'treasure chest',cat:'まち'},
      {w:'壺',r:'つぼ',m:'pot; jar (often contains items)',cat:'まち'},
      {w:'たんす',r:'たんす',m:'dresser; chest of drawers (search for items)',cat:'まち'},
      // ── かいわ ───────────────────────────────────────────────────────
      // Common phrases you will actually read in DQ11 dialogue
      {w:'旅のお方',r:'たびのおかた',m:'"Traveler" — how NPCs address you (polite)',cat:'かいわ'},
      {w:'ようこそ',r:'ようこそ',m:'Welcome!',cat:'かいわ'},
      {w:'お気をつけて',r:'おきをつけて',m:'Please take care; travel safe',cat:'かいわ'},
      {w:'ありがとうございます',r:'ありがとうございます',m:'Thank you very much (polite)',cat:'かいわ'},
      {w:'たのんだぞ',r:'たのんだぞ',m:'I\'m counting on you! I\'m leaving it to you!',cat:'かいわ'},
      {w:'よろしくたのむ',r:'よろしくたのむ',m:'I\'m counting on you (casual/masculine)',cat:'かいわ'},
      {w:'助けてください',r:'たすけてください',m:'Please help me!',cat:'かいわ'},
      {w:'どうかお願いします',r:'どうかおねがいします',m:'Please, I beg you (earnest request)',cat:'かいわ'},
      {w:'〜を探しています',r:'〜をさがしています',m:'I am looking for ~',cat:'かいわ'},
      {w:'〜に行ったことがありますか',r:'〜にいったことがありますか',m:'Have you ever been to ~?',cat:'かいわ'},
      {w:'どこから来たのですか',r:'どこからきたのですか',m:'Where have you come from?',cat:'かいわ'},
      {w:'〜へようこそ',r:'〜へようこそ',m:'Welcome to ~ (greeting on arriving at a place)',cat:'かいわ'},
      {w:'またいつでもどうぞ',r:'またいつでもどうぞ',m:'Please come again anytime',cat:'かいわ'},
      {w:'そうじゃ',r:'そうじゃ',m:'That\'s right; indeed (old man speech — Rab says this constantly)',cat:'かいわ'},
      {w:'〜じゃよ',r:'〜じゃよ',m:'Sentence-ender for old/wise characters (≈ 〜ですよ)',cat:'かいわ'},
      {w:'〜ぞ',r:'〜ぞ',m:'Assertive masculine sentence-ender (≈ "I tell you!")',cat:'かいわ'},
      {w:'〜ですわ',r:'〜ですわ',m:'Refined/noble feminine sentence-ender (Veronica, Jade)',cat:'かいわ'},
      {w:'まさか',r:'まさか',m:'No way…! Surely not…! (shocked disbelief)',cat:'かいわ'},
      {w:'なんと',r:'なんと',m:'What?! / What a ~ ! (exclamation of surprise)',cat:'かいわ'},
      {w:'やはり',r:'やはり',m:'Just as I thought; as expected; after all',cat:'かいわ'},
      {w:'しかし',r:'しかし',m:'However; but (formal contrast)',cat:'かいわ'},
      {w:'それにしても',r:'それにしても',m:'Even so; that said; nevertheless',cat:'かいわ'},
      {w:'いったい',r:'いったい',m:'Just what…? / On earth…? (intensifier in questions)',cat:'かいわ'},
      {w:'〜というわけだ',r:'〜というわけだ',m:'So that\'s why ~; so it means ~; no wonder',cat:'かいわ'},
      {w:'〜にちがいない',r:'〜にちがいない',m:'It must be ~; there\'s no doubt that ~',cat:'かいわ'},
      {w:'世界を救う',r:'せかいをすくう',m:'to save the world',cat:'かいわ'},
      {w:'あきらめるな',r:'あきらめるな',m:'Don\'t give up! (command form)',cat:'かいわ'},
      {w:'おまえにはまだ早い',r:'おまえにはまだはやい',m:'It\'s still too early for you; you\'re not ready yet',cat:'かいわ'},
      {w:'ご無事で',r:'ごぶじで',m:'Please be safe; I hope you\'re alright',cat:'かいわ'},
      {w:'お体に気をつけて',r:'おからだにきをつけて',m:'Please take care of yourself',cat:'かいわ'},
      {w:'いらっしゃいませ',r:'いらっしゃいませ',m:'Welcome! (shop/inn greeting)',cat:'かいわ'},
      {w:'どうぞごゆっくり',r:'どうぞごゆっくり',m:'Please take your time; make yourself at home',cat:'かいわ'},
      {w:'〜でよろしいですか',r:'〜でよろしいですか',m:'Will ~ be alright? (shop confirmation before purchase)',cat:'かいわ'},
      {w:'おめざめですか',r:'おめざめですか',m:'Are you awake? Good morning (inn, after resting)',cat:'かいわ'},
      {w:'おつかれさまでした',r:'おつかれさまでした',m:'Good work; you must be tired (said after an ordeal)',cat:'かいわ'},
      {w:'うわさに聞いた',r:'うわさにきいた',m:'I\'ve heard the rumour; word has reached me',cat:'かいわ'},
      {w:'お気の毒に',r:'おきのどくに',m:'How unfortunate; I\'m sorry to hear that (sympathy)',cat:'かいわ'},
      {w:'ご無事でなによりです',r:'ごぶじでなによりです',m:'I\'m so glad you\'re safe (relief)',cat:'かいわ'},
      {w:'嫌な予感',r:'いやなよかん',m:'bad feeling; ominous premonition',cat:'かいわ'},
      {w:'向こう',r:'むこう',m:'beyond; the other side; over there',cat:'かいわ'},
      // ── ストーリー追加 ───────────────────────────────────────────────
      {w:'命運',r:'めいうん',m:'fate; destiny (of a nation or world)',cat:'ストーリー'},
      {w:'勇気',r:'ゆうき',m:'courage; bravery',cat:'ストーリー'},
      {w:'希望',r:'きぼう',m:'hope',cat:'ストーリー'},
      {w:'絶望',r:'ぜつぼう',m:'despair',cat:'ストーリー'},
      {w:'決心',r:'けっしん',m:'resolve; determination',cat:'ストーリー'},
      {w:'誓い',r:'ちかい',m:'vow; oath; promise',cat:'ストーリー'},
      {w:'別れ',r:'わかれ',m:'parting; farewell; separation',cat:'ストーリー'},
      {w:'再会',r:'さいかい',m:'reunion; meeting again',cat:'ストーリー'},
      {w:'涙',r:'なみだ',m:'tears',cat:'ストーリー'},
      {w:'祈る',r:'いのる',m:'to pray; to wish',cat:'ストーリー'},
      {w:'信じる',r:'しんじる',m:'to believe; to trust',cat:'ストーリー'},
    ]
  }
};
