// Game vocabulary data
// w = word (displayed on card), r = reading, m = English meaning, cat = category
// If w === r (katakana), reading is not shown separately
const gameData = {
  pokemon: {
    label: 'ポケモン',
    diff: 'N5',
    cats: ['すべて', 'ポケモン', 'わざ', 'アイテム', 'バトル', 'じょうたい'],
    vocab: [
      // ── ポケモン ────────────────────────────────────────────────────────
      {w:'フシギダネ',r:'フシギダネ',m:'Bulbasaur',cat:'ポケモン'},
      {w:'フシギソウ',r:'フシギソウ',m:'Ivysaur',cat:'ポケモン'},
      {w:'フシギバナ',r:'フシギバナ',m:'Venusaur',cat:'ポケモン'},
      {w:'ヒトカゲ',r:'ヒトカゲ',m:'Charmander',cat:'ポケモン'},
      {w:'リザード',r:'リザード',m:'Charmeleon',cat:'ポケモン'},
      {w:'リザードン',r:'リザードン',m:'Charizard',cat:'ポケモン'},
      {w:'ゼニガメ',r:'ゼニガメ',m:'Squirtle',cat:'ポケモン'},
      {w:'カメール',r:'カメール',m:'Wartortle',cat:'ポケモン'},
      {w:'カメックス',r:'カメックス',m:'Blastoise',cat:'ポケモン'},
      {w:'キャタピー',r:'キャタピー',m:'Caterpie',cat:'ポケモン'},
      {w:'トランセル',r:'トランセル',m:'Metapod',cat:'ポケモン'},
      {w:'バタフリー',r:'バタフリー',m:'Butterfree',cat:'ポケモン'},
      {w:'ビードル',r:'ビードル',m:'Weedle',cat:'ポケモン'},
      {w:'コクーン',r:'コクーン',m:'Kakuna',cat:'ポケモン'},
      {w:'スピアー',r:'スピアー',m:'Beedrill',cat:'ポケモン'},
      {w:'ポッポ',r:'ポッポ',m:'Pidgey',cat:'ポケモン'},
      {w:'ピジョン',r:'ピジョン',m:'Pidgeotto',cat:'ポケモン'},
      {w:'ピジョット',r:'ピジョット',m:'Pidgeot',cat:'ポケモン'},
      {w:'コラッタ',r:'コラッタ',m:'Rattata',cat:'ポケモン'},
      {w:'ラッタ',r:'ラッタ',m:'Raticate',cat:'ポケモン'},
      {w:'オニスズメ',r:'オニスズメ',m:'Spearow',cat:'ポケモン'},
      {w:'オニドリル',r:'オニドリル',m:'Fearow',cat:'ポケモン'},
      {w:'アーボ',r:'アーボ',m:'Ekans',cat:'ポケモン'},
      {w:'アーボック',r:'アーボック',m:'Arbok',cat:'ポケモン'},
      {w:'ピカチュウ',r:'ピカチュウ',m:'Pikachu',cat:'ポケモン'},
      {w:'ライチュウ',r:'ライチュウ',m:'Raichu',cat:'ポケモン'},
      {w:'サンド',r:'サンド',m:'Sandshrew',cat:'ポケモン'},
      {w:'サンドパン',r:'サンドパン',m:'Sandslash',cat:'ポケモン'},
      {w:'ニドラン♀',r:'ニドラン♀',m:'Nidoran♀',cat:'ポケモン'},
      {w:'ニドリーナ',r:'ニドリーナ',m:'Nidorina',cat:'ポケモン'},
      {w:'ニドクイン',r:'ニドクイン',m:'Nidoqueen',cat:'ポケモン'},
      {w:'ニドラン♂',r:'ニドラン♂',m:'Nidoran♂',cat:'ポケモン'},
      {w:'ニドリーノ',r:'ニドリーノ',m:'Nidorino',cat:'ポケモン'},
      {w:'ニドキング',r:'ニドキング',m:'Nidoking',cat:'ポケモン'},
      {w:'プリン',r:'プリン',m:'Jigglypuff',cat:'ポケモン'},
      {w:'プクリン',r:'プクリン',m:'Wigglytuff',cat:'ポケモン'},
      {w:'ロコン',r:'ロコン',m:'Vulpix',cat:'ポケモン'},
      {w:'キュウコン',r:'キュウコン',m:'Ninetales',cat:'ポケモン'},
      {w:'パラス',r:'パラス',m:'Paras',cat:'ポケモン'},
      {w:'パラセクト',r:'パラセクト',m:'Parasect',cat:'ポケモン'},
      {w:'コンパン',r:'コンパン',m:'Venonat',cat:'ポケモン'},
      {w:'モルフォン',r:'モルフォン',m:'Venomoth',cat:'ポケモン'},
      {w:'ディグダ',r:'ディグダ',m:'Diglett',cat:'ポケモン'},
      {w:'ダグトリオ',r:'ダグトリオ',m:'Dugtrio',cat:'ポケモン'},
      {w:'ニャース',r:'ニャース',m:'Meowth',cat:'ポケモン'},
      {w:'ペルシアン',r:'ペルシアン',m:'Persian',cat:'ポケモン'},
      {w:'コダック',r:'コダック',m:'Psyduck',cat:'ポケモン'},
      {w:'ゴルダック',r:'ゴルダック',m:'Golduck',cat:'ポケモン'},
      {w:'マンキー',r:'マンキー',m:'Mankey',cat:'ポケモン'},
      {w:'オコリザル',r:'オコリザル',m:'Primeape',cat:'ポケモン'},
      {w:'ガーディ',r:'ガーディ',m:'Growlithe',cat:'ポケモン'},
      {w:'ウインディ',r:'ウインディ',m:'Arcanine',cat:'ポケモン'},
      {w:'ニョロモ',r:'ニョロモ',m:'Poliwag',cat:'ポケモン'},
      {w:'ニョロゾ',r:'ニョロゾ',m:'Poliwhirl',cat:'ポケモン'},
      {w:'ニョロボン',r:'ニョロボン',m:'Poliwrath',cat:'ポケモン'},
      {w:'ケーシィ',r:'ケーシィ',m:'Abra',cat:'ポケモン'},
      {w:'ユンゲラー',r:'ユンゲラー',m:'Kadabra',cat:'ポケモン'},
      {w:'フーディン',r:'フーディン',m:'Alakazam',cat:'ポケモン'},
      {w:'ワンリキー',r:'ワンリキー',m:'Machop',cat:'ポケモン'},
      {w:'ゴーリキー',r:'ゴーリキー',m:'Machoke',cat:'ポケモン'},
      {w:'カイリキー',r:'カイリキー',m:'Machamp',cat:'ポケモン'},
      {w:'マダツボミ',r:'マダツボミ',m:'Bellsprout',cat:'ポケモン'},
      {w:'ウツドン',r:'ウツドン',m:'Weepinbell',cat:'ポケモン'},
      {w:'ウツボット',r:'ウツボット',m:'Victreebel',cat:'ポケモン'},
      {w:'メノクラゲ',r:'メノクラゲ',m:'Tentacool',cat:'ポケモン'},
      {w:'ドククラゲ',r:'ドククラゲ',m:'Tentacruel',cat:'ポケモン'},
      {w:'イシツブテ',r:'イシツブテ',m:'Geodude',cat:'ポケモン'},
      {w:'ゴローン',r:'ゴローン',m:'Graveler',cat:'ポケモン'},
      {w:'ゴローニャ',r:'ゴローニャ',m:'Golem',cat:'ポケモン'},
      {w:'ポニータ',r:'ポニータ',m:'Ponyta',cat:'ポケモン'},
      {w:'ギャロップ',r:'ギャロップ',m:'Rapidash',cat:'ポケモン'},
      {w:'ヤドン',r:'ヤドン',m:'Slowpoke',cat:'ポケモン'},
      {w:'ヤドラン',r:'ヤドラン',m:'Slowbro',cat:'ポケモン'},
      {w:'コイル',r:'コイル',m:'Magnemite',cat:'ポケモン'},
      {w:'レアコイル',r:'レアコイル',m:'Magneton',cat:'ポケモン'},
      {w:'ドードー',r:'ドードー',m:'Doduo',cat:'ポケモン'},
      {w:'ドードリオ',r:'ドードリオ',m:'Dodrio',cat:'ポケモン'},
      {w:'パウワウ',r:'パウワウ',m:'Seel',cat:'ポケモン'},
      {w:'ジュゴン',r:'ジュゴン',m:'Dewgong',cat:'ポケモン'},
      {w:'ベトベター',r:'ベトベター',m:'Grimer',cat:'ポケモン'},
      {w:'ベトベトン',r:'ベトベトン',m:'Muk',cat:'ポケモン'},
      {w:'シェルダー',r:'シェルダー',m:'Shellder',cat:'ポケモン'},
      {w:'パルシェン',r:'パルシェン',m:'Cloyster',cat:'ポケモン'},
      {w:'ゴース',r:'ゴース',m:'Gastly',cat:'ポケモン'},
      {w:'ゴースト',r:'ゴースト',m:'Haunter',cat:'ポケモン'},
      {w:'ゲンガー',r:'ゲンガー',m:'Gengar',cat:'ポケモン'},
      {w:'イワーク',r:'イワーク',m:'Onix',cat:'ポケモン'},
      {w:'スリープ',r:'スリープ',m:'Drowzee',cat:'ポケモン'},
      {w:'スリーパー',r:'スリーパー',m:'Hypno',cat:'ポケモン'},
      {w:'クラブ',r:'クラブ',m:'Krabby',cat:'ポケモン'},
      {w:'キングラー',r:'キングラー',m:'Kingler',cat:'ポケモン'},
      {w:'ビリリダマ',r:'ビリリダマ',m:'Voltorb',cat:'ポケモン'},
      {w:'マルマイン',r:'マルマイン',m:'Electrode',cat:'ポケモン'},
      {w:'タマタマ',r:'タマタマ',m:'Exeggcute',cat:'ポケモン'},
      {w:'ナッシー',r:'ナッシー',m:'Exeggutor',cat:'ポケモン'},
      {w:'カラカラ',r:'カラカラ',m:'Cubone',cat:'ポケモン'},
      {w:'ガラガラ',r:'ガラガラ',m:'Marowak',cat:'ポケモン'},
      {w:'ルージュラ',r:'ルージュラ',m:'Jynx',cat:'ポケモン'},
      {w:'エレブー',r:'エレブー',m:'Electabuzz',cat:'ポケモン'},
      {w:'ブーバー',r:'ブーバー',m:'Magmar',cat:'ポケモン'},
      {w:'カイロス',r:'カイロス',m:'Pinsir',cat:'ポケモン'},
      {w:'ケンタロス',r:'ケンタロス',m:'Tauros',cat:'ポケモン'},
      {w:'コイキング',r:'コイキング',m:'Magikarp',cat:'ポケモン'},
      {w:'ギャラドス',r:'ギャラドス',m:'Gyarados',cat:'ポケモン'},
      {w:'ラプラス',r:'ラプラス',m:'Lapras',cat:'ポケモン'},
      {w:'メタモン',r:'メタモン',m:'Ditto',cat:'ポケモン'},
      {w:'イーブイ',r:'イーブイ',m:'Eevee',cat:'ポケモン'},
      {w:'シャワーズ',r:'シャワーズ',m:'Vaporeon',cat:'ポケモン'},
      {w:'サンダース',r:'サンダース',m:'Jolteon',cat:'ポケモン'},
      {w:'ブースター',r:'ブースター',m:'Flareon',cat:'ポケモン'},
      {w:'ポリゴン',r:'ポリゴン',m:'Porygon',cat:'ポケモン'},
      {w:'オムナイト',r:'オムナイト',m:'Omanyte',cat:'ポケモン'},
      {w:'オムスター',r:'オムスター',m:'Omastar',cat:'ポケモン'},
      {w:'カブト',r:'カブト',m:'Kabuto',cat:'ポケモン'},
      {w:'カブトプス',r:'カブトプス',m:'Kabutops',cat:'ポケモン'},
      {w:'プテラ',r:'プテラ',m:'Aerodactyl',cat:'ポケモン'},
      {w:'カビゴン',r:'カビゴン',m:'Snorlax',cat:'ポケモン'},
      {w:'フリーザー',r:'フリーザー',m:'Articuno',cat:'ポケモン'},
      {w:'サンダー',r:'サンダー',m:'Zapdos',cat:'ポケモン'},
      {w:'ファイヤー',r:'ファイヤー',m:'Moltres',cat:'ポケモン'},
      {w:'ミニリュウ',r:'ミニリュウ',m:'Dratini',cat:'ポケモン'},
      {w:'ハクリュー',r:'ハクリュー',m:'Dragonair',cat:'ポケモン'},
      {w:'カイリュー',r:'カイリュー',m:'Dragonite',cat:'ポケモン'},
      {w:'ミュウツー',r:'ミュウツー',m:'Mewtwo',cat:'ポケモン'},
      {w:'ミュウ',r:'ミュウ',m:'Mew',cat:'ポケモン'},
      // ── わざ ────────────────────────────────────────────────────────
      {w:'ひのこ',r:'ひのこ',m:'Ember',cat:'わざ'},
      {w:'かえんほうしゃ',r:'かえんほうしゃ',m:'Flamethrower',cat:'わざ'},
      {w:'みずでっぽう',r:'みずでっぽう',m:'Water Gun',cat:'わざ'},
      {w:'なみのり',r:'なみのり',m:'Surf',cat:'わざ'},
      {w:'かみなり',r:'かみなり',m:'Thunder',cat:'わざ'},
      {w:'10まんボルト',r:'10まんボルト',m:'Thunderbolt',cat:'わざ'},
      {w:'はっぱカッター',r:'はっぱカッター',m:'Razor Leaf',cat:'わざ'},
      {w:'たいあたり',r:'たいあたり',m:'Tackle',cat:'わざ'},
      {w:'ひっかく',r:'ひっかく',m:'Scratch',cat:'わざ'},
      {w:'きりさく',r:'きりさく',m:'Cut',cat:'わざ'},
      {w:'はかいこうせん',r:'はかいこうせん',m:'Hyper Beam',cat:'わざ'},
      {w:'げきりん',r:'げきりん',m:'Outrage',cat:'わざ'},
      {w:'つるぎのまい',r:'つるぎのまい',m:'Sword Dance',cat:'わざ'},
      {w:'あくのはどう',r:'あくのはどう',m:'Dark Pulse',cat:'わざ'},
      {w:'サイコキネシス',r:'サイコキネシス',m:'Psychic',cat:'わざ'},
      {w:'ふぶき',r:'ふぶき',m:'Blizzard',cat:'わざ'},
      {w:'じしん',r:'じしん',m:'Earthquake',cat:'わざ'},
      {w:'いわなだれ',r:'いわなだれ',m:'Rock Slide',cat:'わざ'},
      {w:'ほのおのうず',r:'ほのおのうず',m:'Fire Spin',cat:'わざ'},
      {w:'さいみんじゅつ',r:'さいみんじゅつ',m:'Hypnosis',cat:'わざ'},
      {w:'しびれごな',r:'しびれごな',m:'Stun Spore',cat:'わざ'},
      {w:'どくどく',r:'どくどく',m:'Toxic',cat:'わざ'},
      {w:'かたくなる',r:'かたくなる',m:'Harden',cat:'わざ'},
      {w:'なきごえ',r:'なきごえ',m:'Growl',cat:'わざ'},
      {w:'でんこうせっか',r:'でんこうせっか',m:'Quick Attack',cat:'わざ'},
      {w:'そらをとぶ',r:'そらをとぶ',m:'Fly',cat:'わざ'},
      {w:'ねむる',r:'ねむる',m:'Rest',cat:'わざ'},
      {w:'めざめるパワー',r:'めざめるパワー',m:'Hidden Power',cat:'わざ'},
      {w:'メガドレイン',r:'メガドレイン',m:'Mega Drain',cat:'わざ'},
      {w:'くすぐる',r:'くすぐる',m:'Tickle',cat:'わざ'},
      // ── アイテム ─────────────────────────────────────────────────────
      {w:'モンスターボール',r:'モンスターボール',m:'Poké Ball',cat:'アイテム'},
      {w:'スーパーボール',r:'スーパーボール',m:'Great Ball',cat:'アイテム'},
      {w:'ハイパーボール',r:'ハイパーボール',m:'Ultra Ball',cat:'アイテム'},
      {w:'マスターボール',r:'マスターボール',m:'Master Ball',cat:'アイテム'},
      {w:'きずぐすり',r:'きずぐすり',m:'Potion',cat:'アイテム'},
      {w:'いいきずぐすり',r:'いいきずぐすり',m:'Super Potion',cat:'アイテム'},
      {w:'すごいきずぐすり',r:'すごいきずぐすり',m:'Hyper Potion',cat:'アイテム'},
      {w:'まんたんのくすり',r:'まんたんのくすり',m:'Max Potion',cat:'アイテム'},
      {w:'げんきのかけら',r:'げんきのかけら',m:'Revive',cat:'アイテム'},
      {w:'げんきのかたまり',r:'げんきのかたまり',m:'Max Revive',cat:'アイテム'},
      {w:'どうのみのみ',r:'どうのみのみ',m:'Oran Berry',cat:'アイテム'},
      {w:'ひかりのいし',r:'ひかりのいし',m:'Fire Stone',cat:'アイテム'},
      {w:'かみなりのいし',r:'かみなりのいし',m:'Thunder Stone',cat:'アイテム'},
      {w:'みずのいし',r:'みずのいし',m:'Water Stone',cat:'アイテム'},
      {w:'ぼうぐのこな',r:'ぼうぐのこな',m:'Escape Rope',cat:'アイテム'},
      {w:'むしよけスプレー',r:'むしよけスプレー',m:'Repel',cat:'アイテム'},
      {w:'スーパーじどうじてんしゃ',r:'スーパーじどうじてんしゃ',m:'Bicycle',cat:'アイテム'},
      {w:'なんでもなおし',r:'なんでもなおし',m:'Full Heal',cat:'アイテム'},
      {w:'カスタム',r:'カスタム',m:'TM (Technical Machine)',cat:'アイテム'},
      {w:'ひでんマシン',r:'ひでんマシン',m:'HM (Hidden Machine)',cat:'アイテム'},
      // ── バトル ───────────────────────────────────────────────────────
      {w:'たたかう',r:'たたかう',m:'Fight (battle command)',cat:'バトル'},
      {w:'にげる',r:'にげる',m:'Run (battle command)',cat:'バトル'},
      {w:'ポケモン',r:'ポケモン',m:'Pokémon (switch command)',cat:'バトル'},
      {w:'どうぐ',r:'どうぐ',m:'Bag / Items (battle command)',cat:'バトル'},
      {w:'こうどう',r:'こうどう',m:'Action / turn',cat:'バトル'},
      {w:'ひんし',r:'ひんし',m:'Fainted (KO\'d)',cat:'バトル'},
      {w:'きゅうしょにあたった',r:'きゅうしょにあたった',m:'Critical hit!',cat:'バトル'},
      {w:'こうかはばつぐんだ',r:'こうかはばつぐんだ',m:'It\'s super effective!',cat:'バトル'},
      {w:'こうかはいまひとつだ',r:'こうかはいまひとつだ',m:'It\'s not very effective...',cat:'バトル'},
      {w:'こうかがない',r:'こうかがない',m:'It has no effect.',cat:'バトル'},
      {w:'わざはそれいじょうつかえない',r:'わざはそれいじょうつかえない',m:'The move ran out of PP.',cat:'バトル'},
      // ── じょうたい ───────────────────────────────────────────────────
      {w:'まひ',r:'まひ',m:'Paralysis',cat:'じょうたい'},
      {w:'どく',r:'どく',m:'Poison',cat:'じょうたい'},
      {w:'もうどく',r:'もうどく',m:'Bad Poison',cat:'じょうたい'},
      {w:'やけど',r:'やけど',m:'Burn',cat:'じょうたい'},
      {w:'こおり',r:'こおり',m:'Frozen',cat:'じょうたい'},
      {w:'ねむり',r:'ねむり',m:'Sleep',cat:'じょうたい'},
      {w:'こんらん',r:'こんらん',m:'Confusion',cat:'じょうたい'},
      {w:'ひるみ',r:'ひるみ',m:'Flinch',cat:'じょうたい'},
      {w:'メロメロ',r:'メロメロ',m:'Infatuation (Attract)',cat:'じょうたい'},
    ]
  },

  acnh: {
    label: 'どうぶつの森',
    diff: 'N5–N4',
    cats: ['すべて', '日常', 'どうぐ', 'しぜん', 'むらびと', 'いえ'],
    vocab: [
      // ── 日常 ─────────────────────────────────────────────────────────
      {w:'たぬきち',r:'たぬきち',m:'Tom Nook',cat:'むらびと'},
      {w:'しずえ',r:'しずえ',m:'Isabelle',cat:'むらびと'},
      {w:'もりのくらし',r:'もりのくらし',m:'island life; living in the village',cat:'日常'},
      {w:'まいにちのせいかつ',r:'まいにちのせいかつ',m:'daily life',cat:'日常'},
      {w:'おはなし',r:'おはなし',m:'talking; conversation (polite)',cat:'日常'},
      {w:'ごあいさつ',r:'ごあいさつ',m:'greeting (polite)',cat:'日常'},
      {w:'にっか',r:'にっか',m:'daily schedule; program',cat:'日常'},
      {w:'かいもの',r:'かいもの',m:'shopping',cat:'日常'},
      {w:'かせぐ',r:'かせぐ',m:'to earn (money, miles)',cat:'日常'},
      {w:'ローン',r:'ローン',m:'loan; mortgage',cat:'日常'},
      {w:'かえす',r:'かえす',m:'to pay back; to return',cat:'日常'},
      {w:'マイル',r:'マイル',m:'Nook Miles',cat:'日常'},
      {w:'おいのり',r:'おいのり',m:'prayer; wishing on a star',cat:'日常'},
      {w:'まつり',r:'まつり',m:'festival',cat:'日常'},
      {w:'きねんび',r:'きねんび',m:'anniversary; special day',cat:'日常'},
      // ── どうぐ ───────────────────────────────────────────────────────
      {w:'つりざお',r:'つりざお',m:'fishing rod',cat:'どうぐ'},
      {w:'あみ',r:'あみ',m:'net; bug net',cat:'どうぐ'},
      {w:'スコップ',r:'スコップ',m:'shovel',cat:'どうぐ'},
      {w:'ジョウロ',r:'ジョウロ',m:'watering can',cat:'どうぐ'},
      {w:'おの',r:'おの',m:'axe',cat:'どうぐ'},
      {w:'パチンコ',r:'パチンコ',m:'slingshot',cat:'どうぐ'},
      {w:'はしご',r:'はしご',m:'ladder; stepladder',cat:'どうぐ'},
      {w:'さおだけ',r:'さおだけ',m:'vaulting pole',cat:'どうぐ'},
      {w:'かいちゅうでんとう',r:'かいちゅうでんとう',m:'flashlight; torch',cat:'どうぐ'},
      {w:'スマホ',r:'スマホ',m:'smartphone (NookPhone)',cat:'どうぐ'},
      {w:'きれいなみず',r:'きれいなみず',m:'fresh water; watering',cat:'どうぐ'},
      // ── しぜん ───────────────────────────────────────────────────────
      {w:'さかな',r:'さかな',m:'fish',cat:'しぜん'},
      {w:'むし',r:'むし',m:'bug; insect',cat:'しぜん'},
      {w:'はな',r:'はな',m:'flower',cat:'しぜん'},
      {w:'き',r:'き',m:'tree',cat:'しぜん'},
      {w:'くだもの',r:'くだもの',m:'fruit',cat:'しぜん'},
      {w:'しましまのかぶ',r:'しましまのかぶ',m:'turnip (Stalk Market)',cat:'しぜん'},
      {w:'ほし',r:'ほし',m:'star',cat:'しぜん'},
      {w:'りゅうせい',r:'りゅうせい',m:'shooting star; meteor',cat:'しぜん'},
      {w:'おちば',r:'おちば',m:'fallen leaves',cat:'しぜん'},
      {w:'ゆき',r:'ゆき',m:'snow',cat:'しぜん'},
      {w:'かわ',r:'かわ',m:'river',cat:'しぜん'},
      {w:'うみ',r:'うみ',m:'sea; ocean',cat:'しぜん'},
      {w:'がけ',r:'がけ',m:'cliff',cat:'しぜん'},
      {w:'たきつぼ',r:'たきつぼ',m:'waterfall pool',cat:'しぜん'},
      {w:'かぶ',r:'かぶ',m:'turnip; stock (Stalk Market)',cat:'しぜん'},
      // ── むらびと ─────────────────────────────────────────────────────
      {w:'むらびと',r:'むらびと',m:'villager; island resident',cat:'むらびと'},
      {w:'しまのせいかつ',r:'しまのせいかつ',m:'island life',cat:'むらびと'},
      {w:'あそびにくる',r:'あそびにくる',m:'to come to visit; come hang out',cat:'むらびと'},
      {w:'プレゼント',r:'プレゼント',m:'present; gift',cat:'むらびと'},
      {w:'てがみ',r:'てがみ',m:'letter',cat:'むらびと'},
      {w:'なかよし',r:'なかよし',m:'close friends; getting along well',cat:'むらびと'},
      {w:'ともだちコード',r:'ともだちコード',m:'friend code',cat:'むらびと'},
      // ── いえ ─────────────────────────────────────────────────────────
      {w:'かぐ',r:'かぐ',m:'furniture',cat:'いえ'},
      {w:'かべがみ',r:'かべがみ',m:'wallpaper',cat:'いえ'},
      {w:'ゆか',r:'ゆか',m:'flooring',cat:'いえ'},
      {w:'おへや',r:'おへや',m:'room (polite)',cat:'いえ'},
      {w:'インテリア',r:'インテリア',m:'interior design',cat:'いえ'},
      {w:'テント',r:'テント',m:'tent',cat:'いえ'},
      {w:'いえ',r:'いえ',m:'house; home',cat:'いえ'},
      {w:'かんせい',r:'かんせい',m:'completion; finished',cat:'いえ'},
      {w:'DIY',r:'ディーアイワイ',m:'DIY crafting',cat:'いえ'},
      {w:'レシピ',r:'レシピ',m:'recipe; crafting formula',cat:'いえ'},
    ]
  },

  dq11: {
    label: 'DQ XI',
    diff: 'N4–N3',
    cats: ['すべて', 'バトル', 'じゅもん', 'アイテム', 'ストーリー', 'しょくぎょう', 'まち', 'かいわ', 'セリフ'],
    // セリフ = dialogue comprehension questions (separate from vocab)
    dialogues: [
      // ── やどや・まちのNPC ────────────────────────────────────────────
      {
        s:'ゆっくりお休みください。旅の疲れをいやしていってくださいね。',
        sp:'やどや',
        a:'Please rest well. Let yourself recover from the fatigue of your journey.',
        c:[
          'Please rest well. Let yourself recover from the fatigue of your journey.',
          'You look tired. Have you been travelling long? Where are you headed?',
          'We\'re fully booked tonight, I\'m afraid. Please try again tomorrow.',
          'You can rest here, but watch out — monsters have been seen nearby.',
        ],
        e:'疲れをいやす = to soothe / recover from fatigue. いやしていって = "go and heal yourself here"',
      },
      {
        s:'このあたりでは魔物が増えていて、夜は外に出られないんですよ。本当に困っています。',
        sp:'村人',
        a:'Monsters have been increasing around here, so we can\'t go outside at night. We\'re really struggling.',
        c:[
          'Monsters have been increasing around here, so we can\'t go outside at night. We\'re really struggling.',
          'The monsters here only come out at night, so travelling in the day is fine.',
          'We\'ve been catching lots of monsters lately. It\'s actually been quite profitable.',
          'The monsters left after a hero defeated them. Things have been peaceful since.',
        ],
        e:'増えている = increasing (ている = ongoing state). 出られない = cannot go out (potential negative). 困っています = we are troubled / struggling',
      },
      {
        s:'西に進むと、デルカダール王国があります。国王様にご用がおありなのですか？',
        sp:'村人',
        a:'If you go west, you\'ll find the Kingdom of Heliodor. Do you have business with the king?',
        c:[
          'If you go west, you\'ll find the Kingdom of Heliodor. Do you have business with the king?',
          'The Kingdom of Heliodor is to the east. The king is expecting you.',
          'The road west is blocked. You\'ll need permission from the king to pass.',
          'Heliodor is far to the north. Few travellers make it there safely.',
        ],
        e:'〜に進む = to advance / head towards ~. ご用がおありですか = polite "do you have business/an errand?"',
      },
      {
        s:'道具屋でやくそうをたくさん買っておくといいですよ。この先の洞窟は手強いらしいので。',
        sp:'村人',
        a:'You should stock up on medicinal herbs at the item shop. Apparently the cave ahead is tough.',
        c:[
          'You should stock up on medicinal herbs at the item shop. Apparently the cave ahead is tough.',
          'The item shop sells herbs, but they\'re expensive. You\'re better off finding them in the cave.',
          'Don\'t bother with herbs — the monsters in the cave drop plenty of items.',
          'The item shop is closed today. You\'ll have to manage without supplies.',
        ],
        e:'〜ておく = do in advance / stock up. 手強い = tough / formidable. 〜らしい = apparently / I hear that',
      },
      {
        s:'まおうが現れてから、世界はずっと暗くなる一方だ。誰かが何とかしてくれないと…。',
        sp:'村人',
        a:'Ever since the Dark Lord appeared, the world has only been getting darker. If someone doesn\'t do something…',
        c:[
          'Ever since the Dark Lord appeared, the world has only been getting darker. If someone doesn\'t do something…',
          'The Dark Lord appeared once before, but a hero defeated him. It will happen again.',
          'People say the world is getting darker, but I think things will improve on their own.',
          'Since the Dark Lord appeared, trade has boomed. Dark times can be profitable.',
        ],
        e:'〜て以来 / から = ever since ~. 〜一方だ = keeps doing ~; only getting more ~. 何とかする = to do something about it',
      },
      {
        s:'勇者のしるしを持つ者が、いつかこの地に現れると言い伝えられておる。',
        sp:'長老',
        a:'It is passed down in legend that one who bears the mark of the hero will one day appear in this land.',
        c:[
          'It is passed down in legend that one who bears the mark of the hero will one day appear in this land.',
          'The hero\'s mark was lost long ago. No one alive has ever seen it.',
          'A person bearing the mark appeared here before, but they failed and disappeared.',
          'The mark of the hero is said to choose its bearer — you cannot seek it out.',
        ],
        e:'〜と言い伝えられている = it is passed down / legend has it that ~. 〜おる = archaic/dialect form of いる (elder speech)',
      },
      // ── ロウ（老人口調：〜じゃ）───────────────────────────────────
      {
        s:'そうじゃ、お主が本当の勇者なのじゃ。ワシはずっと信じておったぞ。',
        sp:'ロウ',
        a:'That\'s right — you are the true Luminary. I always believed in you.',
        c:[
          'That\'s right — you are the true Luminary. I always believed in you.',
          'So you really think you\'re the hero? You still have much to prove, I\'m afraid.',
          'Is that so? Others have claimed to be the hero before. I\'ll wait and see.',
          'You\'re the hero? I had my doubts, but perhaps the mark doesn\'t lie.',
        ],
        e:'お主 = archaic "you" (used by elders). 〜のじゃ = elder sentence-ender (= 〜のだ). 信じておった = had been believing (past progressive, archaic)',
      },
      {
        s:'この先の道は険しいのじゃ。じゃが、お主ならきっと乗り越えられるじゃろう。',
        sp:'ロウ',
        a:'The road ahead is steep and harsh. But knowing you, you will surely overcome it.',
        c:[
          'The road ahead is steep and harsh. But knowing you, you will surely overcome it.',
          'The road ahead is easy enough. Even alone you should have no trouble.',
          'The road is too dangerous. I cannot allow you to go any further.',
          'The path is long. We should rest here before continuing tomorrow.',
        ],
        e:'険しい = steep / harsh / severe. じゃが = elder form of "but / however". 乗り越えられる = can overcome / surmount',
      },
      {
        s:'無茶だけはしないでくれよ。お主のことが心配なんじゃ。',
        sp:'ロウ',
        a:'Just please don\'t do anything reckless. I\'m worried about you.',
        c:[
          'Just please don\'t do anything reckless. I\'m worried about you.',
          'Go ahead and take risks — that\'s what being a hero is about. I\'m proud of you.',
          'Don\'t hold back. The enemy is reckless, so you need to be too.',
          'You worry too much. I\'m fine — focus on the mission.',
        ],
        e:'無茶をする = to be reckless / overdo it. 〜ないでくれ = please don\'t ~. 心配 = worried / concerned',
      },
      // ── エリック（タメ口・若者言葉）──────────────────────────────────
      {
        s:'おいおい、マジかよ。あんな数の魔物、どうやって倒すんだよ。',
        sp:'エリック',
        a:'Whoa whoa, are you serious? How are we supposed to beat that many monsters?',
        c:[
          'Whoa whoa, are you serious? How are we supposed to beat that many monsters?',
          'Hey, look at all those monsters! This is going to be so easy for us.',
          'Hmm, there are a lot of enemies. I\'ve handled worse though. Let\'s go.',
          'Oh no, monsters ahead. You go first — I\'ll cover you from behind.',
        ],
        e:'おいおい = "hey hey / whoa" (casual surprise). マジかよ = "seriously? / for real?" (casual). あんな = "that kind of / that many (over there)"',
      },
      {
        s:'まあ、なんとかなるって。俺たちがいるんだから、心配すんなよ。',
        sp:'エリック',
        a:'Eh, it\'ll work out. We\'re here with you, so don\'t worry.',
        c:[
          'Eh, it\'ll work out. We\'re here with you, so don\'t worry.',
          'Actually, I\'m not sure we can win this one. We should think carefully.',
          'I know it looks bad, but run if you have to — no shame in it.',
          'It\'s not going to work out. We need to find another way.',
        ],
        e:'なんとかなる = it\'ll work out somehow. 〜って = casual sentence-ender (assertion). 心配すんな = don\'t worry (すんな = casual negative command of する)',
      },
      {
        s:'この戦いが終わったら、みんなでゆっくり旅をしようじゃないか。',
        sp:'エリック',
        a:'When this battle is over, let\'s all travel together at our own pace.',
        c:[
          'When this battle is over, let\'s all travel together at our own pace.',
          'After this, I\'m going back home. I\'ve had enough of travelling.',
          'This battle might be our last. Let\'s make it count.',
          'Once we win, the others can go. I\'ll stay and keep watch.',
        ],
        e:'〜たら = when/after ~ (conditional on completion). 〜ようじゃないか = "let\'s ~, shall we?" (casual suggestion)',
      },
      // ── ベロニカ（お嬢様口調：〜ですわ）─────────────────────────────
      {
        s:'わたくしの魔法の腕前、とくとごらんなさいですわ！',
        sp:'ベロニカ',
        a:'Take a good, close look at my magical skills!',
        c:[
          'Take a good, close look at my magical skills!',
          'Please lend me your magical power — mine isn\'t strong enough alone.',
          'Don\'t watch me — focus on the enemy. I can handle myself.',
          'My magic is a secret. I\'d rather you didn\'t watch.',
        ],
        e:'わたくし = formal "I" (refined feminine). とくとごらんなさい = "take a good look / watch closely" (instructive, slightly theatrical). 〜ですわ = refined feminine sentence-ender',
      },
      {
        s:'べ、別にあなたのことを心配してたわけじゃないんだからね！',
        sp:'ベロニカ',
        a:'I-It\'s not like I was worried about you or anything!',
        c:[
          'I-It\'s not like I was worried about you or anything!',
          'Of course I was worried about you. Don\'t do that again.',
          'I wasn\'t watching you at all. I had my own things to deal with.',
          'Why would I be worried? You\'re the hero. You\'ll be fine.',
        ],
        e:'Classic tsundere line. 別に〜わけじゃない = "it\'s not like ~". 〜だからね！ = assertive self-justification. The hesitation (べ、別に) signals embarrassment.',
      },
      // ── セーニャ（丁寧・やさしい口調）──────────────────────────────
      {
        s:'あなたの力を信じています。どうか、無事でいてください。',
        sp:'セーニャ',
        a:'I believe in your strength. Please, stay safe.',
        c:[
          'I believe in your strength. Please, stay safe.',
          'I\'m not sure you can do this alone. Let me come with you.',
          'Your power is fading. Please rest before you go any further.',
          'I believe in you, but please be careful — I have a bad feeling.',
        ],
        e:'〜を信じています = I believe in ~. どうか = please (earnest, emotional). 無事でいる = to be safe / to remain unharmed',
      },
      {
        s:'みんなで力を合わせれば、きっと乗り越えられます。あきらめないでください。',
        sp:'セーニャ',
        a:'If we all combine our strength, we can surely overcome this. Please don\'t give up.',
        c:[
          'If we all combine our strength, we can surely overcome this. Please don\'t give up.',
          'Our combined strength isn\'t enough. We need to find another way.',
          'I know it\'s hard, but sometimes giving up is the right choice.',
          'I\'ll combine my strength with yours, but the others can\'t help us here.',
        ],
        e:'力を合わせる = to combine strength / join forces. 〜ば = if ~ (conditional). 乗り越えられる = can overcome. あきらめないで = don\'t give up',
      },
      // ── グレイグ（武人口調：〜ぬ / 〜だ）────────────────────────────
      {
        s:'お前が勇者だというなら、その力を見せてみろ。言葉だけでは信じられぬ。',
        sp:'グレイグ',
        a:'If you claim to be the hero, show me your strength. I cannot believe words alone.',
        c:[
          'If you claim to be the hero, show me your strength. I cannot believe words alone.',
          'So you are the hero. I\'ve been waiting for you — your reputation precedes you.',
          'The hero, you say? I\'ll take your word for it. We need all the help we can get.',
          'You don\'t need to prove anything to me. The mark speaks for itself.',
        ],
        e:'〜というなら = if you say / if you claim ~. 見せてみろ = show me (strong command). 〜ぬ = archaic/formal negative (= 〜ない), used by stern warrior types',
      },
      {
        s:'国を守るのが我らの使命だ。たとえ命を賭けることになろうとも。',
        sp:'グレイグ',
        a:'Protecting the kingdom is our duty. Even if it means risking our lives.',
        c:[
          'Protecting the kingdom is our duty. Even if it means risking our lives.',
          'Protecting the kingdom is important, but we must also protect ourselves first.',
          'Our duty to the kingdom is over. Now we fight for ourselves.',
          'The king has ordered us to retreat. Protecting the kingdom means surviving.',
        ],
        e:'我ら = archaic "we / us" (soldier speech). 使命 = duty / mission. たとえ〜とも = even if ~. 命を賭ける = to risk one\'s life',
      },
      // ── ストーリー・感情的な場面 ──────────────────────────────────────
      {
        s:'まさか…。あの人が敵だったとは、信じたくないが、現実を受け入れるしかない。',
        sp:'パーティー',
        a:'No way…. I don\'t want to believe that person was our enemy, but we have no choice but to accept reality.',
        c:[
          'No way…. I don\'t want to believe that person was our enemy, but we have no choice but to accept reality.',
          'Of course that person was the enemy — I always suspected it.',
          'That person helped us all along. We\'d be nothing without them.',
          'The enemy fooled us into thinking that person was our ally. We\'ve been betrayed.',
        ],
        e:'まさか = "no way / surely not" (shock). 〜だったとは = "that ~ was the case" (shocked realization). 受け入れるしかない = have no choice but to accept',
      },
      {
        s:'いったい、何が起きているんだ…？こんなはずじゃなかったのに。',
        sp:'エリック',
        a:'What on earth is going on…? This isn\'t how it was supposed to be.',
        c:[
          'What on earth is going on…? This isn\'t how it was supposed to be.',
          'Everything is going exactly as planned. This is what we hoped for.',
          'I know what\'s happening. I\'ve seen this before — don\'t panic.',
          'Something is happening, but it\'s nothing to worry about. Trust me.',
        ],
        e:'いったい = "on earth / just what" (intensifier in questions). こんなはずじゃなかった = "it wasn\'t supposed to be like this" — very common JRPG line',
      },
      {
        s:'世界を救うのに、ひとりの力では足りない。仲間を信じて、共に戦うしかないんだ。',
        sp:'ナレーション',
        a:'To save the world, the power of one person is not enough. All you can do is believe in your companions and fight together.',
        c:[
          'To save the world, the power of one person is not enough. All you can do is believe in your companions and fight together.',
          'To save the world, you must become stronger alone. Relying on others is a weakness.',
          'The world can be saved, but not through battle. You must find a peaceful solution.',
          'One person\'s power is enough. You just need to believe in yourself.',
        ],
        e:'〜のに = in order to ~. 足りない = not enough / insufficient. 信じて = believing in (て = and then / by). 〜しかない = have no choice but to ~',
      },
      {
        s:'たとえ何度倒されても、また立ち上がる。それが勇者というものだ。',
        sp:'ロウ',
        a:'No matter how many times you are knocked down, you rise again. That is what it means to be a hero.',
        c:[
          'No matter how many times you are knocked down, you rise again. That is what it means to be a hero.',
          'A hero should never fall. If you are defeated, your journey is over.',
          'Being a hero means never fighting alone. Never face an enemy by yourself.',
          'A hero knows when to retreat. Living to fight another day is true courage.',
        ],
        e:'たとえ〜ても = even if ~; no matter how ~. 何度 = how many times. 立ち上がる = to stand up / rise again. 〜というものだ = that is what ~ is; that\'s the nature of ~',
      },
      {
        s:'この呪いを解くには、せかいじゅの雫が必要じゃ。じゃが、あれを手に入れるのは容易ではないぞ。',
        sp:'ロウ',
        a:'To break this curse, the Yggdrasil Dew is needed. However, obtaining it is no easy matter.',
        c:[
          'To break this curse, the Yggdrasil Dew is needed. However, obtaining it is no easy matter.',
          'The curse can be broken with holy water. You can buy it at the item shop.',
          'The Yggdrasil Dew will break the curse, and it\'s easy to get — I know where it is.',
          'There\'s no known way to break this curse. We must find another solution.',
        ],
        e:'〜を解く = to break / undo ~ (a curse, a code, a problem). 〜には〜が必要 = ~ is needed in order to ~. 容易ではない = not easy / no easy feat',
      },
      {
        s:'あなたに出会えてよかった。これからも、ずっと一緒にいてください。',
        sp:'セーニャ',
        a:'I\'m so glad I met you. Please stay with us — always.',
        c:[
          'I\'m so glad I met you. Please stay with us — always.',
          'I\'m glad we met, but our journey together ends here. Go on without me.',
          'Meeting you changed everything. But I think it\'s time for us to part ways.',
          'I\'m glad to have met you. I hope our paths cross again someday.',
        ],
        e:'〜に出会えてよかった = I\'m glad I was able to meet ~. これからも = from now on too / going forward. ずっと = always / the whole time',
      },
    ],
    vocab: [
      // ── バトル ───────────────────────────────────────────────────────
      {w:'こうげき',r:'こうげき',m:'attack',cat:'バトル'},
      {w:'ぼうぎょ',r:'ぼうぎょ',m:'defense; defend',cat:'バトル'},
      {w:'とくぎ',r:'とくぎ',m:'special skill; ability',cat:'バトル'},
      {w:'じゅもん',r:'じゅもん',m:'magic spell',cat:'バトル'},
      {w:'どうぐをつかう',r:'どうぐをつかう',m:'use an item',cat:'バトル'},
      {w:'にげる',r:'にげる',m:'flee; run away',cat:'バトル'},
      {w:'MP',r:'エムピー',m:'MP (Magic Points)',cat:'バトル'},
      {w:'HP',r:'エイチピー',m:'HP (Hit Points)',cat:'バトル'},
      {w:'ちから',r:'ちから',m:'strength; power',cat:'バトル'},
      {w:'すばやさ',r:'すばやさ',m:'agility; speed',cat:'バトル'},
      {w:'みのまもり',r:'みのまもり',m:'defense stat; protection',cat:'バトル'},
      {w:'かいふく',r:'かいふく',m:'recovery; healing',cat:'バトル'},
      {w:'せんとう',r:'せんとう',m:'battle; combat',cat:'バトル'},
      {w:'さきどり',r:'さきどり',m:'pre-emptive strike; first move',cat:'バトル'},
      {w:'いちげきひっさつ',r:'いちげきひっさつ',m:'one-hit kill; instant kill',cat:'バトル'},
      {w:'れんぞくこうげき',r:'れんぞくこうげき',m:'combo attack; consecutive hits',cat:'バトル'},
      {w:'かいしん',r:'かいしん',m:'critical hit (DQ term)',cat:'バトル'},
      {w:'マヒ',r:'マヒ',m:'paralysis (status)',cat:'バトル'},
      {w:'どく',r:'どく',m:'poison (status)',cat:'バトル'},
      {w:'ねむり',r:'ねむり',m:'sleep (status)',cat:'バトル'},
      {w:'こんらん',r:'こんらん',m:'confusion (status)',cat:'バトル'},
      {w:'マホトーン',r:'マホトーン',m:'Fizzle — seals enemy spells',cat:'バトル'},
      {w:'テンション',r:'テンション',m:'Tension (charge mechanic)',cat:'バトル'},
      {w:'ゾーン',r:'ゾーン',m:'Pep (Zone state — party power-up)',cat:'バトル'},
      {w:'れんけい',r:'れんけい',m:'combination move (Pep skill)',cat:'バトル'},
      {w:'けいけんち',r:'けいけんち',m:'experience points (EXP)',cat:'バトル'},
      {w:'レベルアップ',r:'レベルアップ',m:'level up',cat:'バトル'},
      {w:'ゴールド',r:'ゴールド',m:'Gold (currency)',cat:'バトル'},
      // ── じゅもん ─────────────────────────────────────────────────────
      {w:'ホイミ',r:'ホイミ',m:'Heal — restores a little HP',cat:'じゅもん'},
      {w:'ベホイミ',r:'ベホイミ',m:'Midheal — restores moderate HP',cat:'じゅもん'},
      {w:'ベホマ',r:'ベホマ',m:'Fullheal — fully restores one ally\'s HP',cat:'じゅもん'},
      {w:'ベホマズン',r:'ベホマズン',m:'Omniheal — fully heals the whole party',cat:'じゅもん'},
      {w:'ザオ',r:'ザオ',m:'Zing — 50% chance to revive fallen ally',cat:'じゅもん'},
      {w:'ザオリク',r:'ザオリク',m:'Kazing — fully revives a fallen ally',cat:'じゅもん'},
      {w:'メラ',r:'メラ',m:'Frizz — small fire attack',cat:'じゅもん'},
      {w:'メラミ',r:'メラミ',m:'Frizzle — medium fire attack',cat:'じゅもん'},
      {w:'メラゾーマ',r:'メラゾーマ',m:'Kafrizzle — powerful fire attack',cat:'じゅもん'},
      {w:'ギラ',r:'ギラ',m:'Sizz — small fire (all enemies)',cat:'じゅもん'},
      {w:'ベギラマ',r:'ベギラマ',m:'Sizzle — medium fire (all enemies)',cat:'じゅもん'},
      {w:'ヒャド',r:'ヒャド',m:'Crack — small ice attack',cat:'じゅもん'},
      {w:'ヒャダルコ',r:'ヒャダルコ',m:'Crackle — medium ice (all enemies)',cat:'じゅもん'},
      {w:'バギ',r:'バギ',m:'Whoosh — small wind attack',cat:'じゅもん'},
      {w:'バギマ',r:'バギマ',m:'Swoosh — medium wind (all enemies)',cat:'じゅもん'},
      {w:'イオ',r:'イオ',m:'Bang — small explosion (all enemies)',cat:'じゅもん'},
      {w:'イオラ',r:'イオラ',m:'Boom — medium explosion (all enemies)',cat:'じゅもん'},
      {w:'デイン',r:'デイン',m:'Zap — lightning (one enemy)',cat:'じゅもん'},
      {w:'ザキ',r:'ザキ',m:'Whack — instant death (one enemy)',cat:'じゅもん'},
      {w:'ルーラ',r:'ルーラ',m:'Zoom — teleport to visited towns',cat:'じゅもん'},
      {w:'リレミト',r:'リレミト',m:'Evac — escape from a dungeon',cat:'じゅもん'},
      {w:'マホカンタ',r:'マホカンタ',m:'Bounce — reflects enemy spells',cat:'じゅもん'},
      {w:'スカラ',r:'スカラ',m:'Buff — raises one ally\'s defence',cat:'じゅもん'},
      {w:'バイキルト',r:'バイキルト',m:'Oomph — doubles one ally\'s attack',cat:'じゅもん'},
      {w:'フバーハ',r:'フバーハ',m:'Insulatle — reduces breath damage',cat:'じゅもん'},
      // ── アイテム ─────────────────────────────────────────────────────
      {w:'やくそう',r:'やくそう',m:'medicinal herb — restores ~30 HP',cat:'アイテム'},
      {w:'上やくそう',r:'じょうやくそう',m:'superior herb — restores ~75 HP',cat:'アイテム'},
      {w:'どくけしそう',r:'どくけしそう',m:'antidote herb — cures poison',cat:'アイテム'},
      {w:'まんげつそう',r:'まんげつそう',m:'moonwort bulb — cures sleep/confusion',cat:'アイテム'},
      {w:'せいすい',r:'せいすい',m:'holy water — repels weaker monsters',cat:'アイテム'},
      {w:'キメラのつばさ',r:'キメラのつばさ',m:'chimera wing — return to last town (= Zoom)',cat:'アイテム'},
      {w:'どくばり',r:'どくばり',m:'poison needle — may instantly kill',cat:'アイテム'},
      {w:'まものよけのすず',r:'まものよけのすず',m:'repellent bell — reduces encounters',cat:'アイテム'},
      {w:'てんくうのつるぎ',r:'てんくうのつるぎ',m:'Sword of Light — legendary weapon',cat:'アイテム'},
      {w:'まほうのせいすい',r:'まほうのせいすい',m:'magic water — restores ~30 MP',cat:'アイテム'},
      {w:'エルフののみぐすり',r:'エルフののみぐすり',m:'elf elixir — restores ~60 MP',cat:'アイテム'},
      {w:'げんきのもと',r:'げんきのもと',m:'yggdrasil dew — revives one ally with full HP',cat:'アイテム'},
      {w:'ちいさなメダル',r:'ちいさなメダル',m:'mini medal — collectible; trade for prizes',cat:'アイテム'},
      {w:'レシピブック',r:'レシピブック',m:'recipe book — unlocks forge recipes',cat:'アイテム'},
      {w:'ふしぎな鍛冶',r:'ふしぎなかじ',m:'Fun-Size Forge — item crafting system',cat:'アイテム'},
      // ── ストーリー ───────────────────────────────────────────────────
      {w:'えいゆう',r:'えいゆう',m:'hero; champion',cat:'ストーリー'},
      {w:'ゆうしゃ',r:'ゆうしゃ',m:'Luminary; chosen hero',cat:'ストーリー'},
      {w:'よげん',r:'よげん',m:'prophecy; prediction',cat:'ストーリー'},
      {w:'でんせつ',r:'でんせつ',m:'legend; legendary',cat:'ストーリー'},
      {w:'ろうし',r:'ろうし',m:'legendary hero (Erdwin — the old hero)',cat:'ストーリー'},
      {w:'まおう',r:'まおう',m:'Dark Lord; Demon King',cat:'ストーリー'},
      {w:'だいまおう',r:'だいまおう',m:'Great Demon King (most powerful evil)',cat:'ストーリー'},
      {w:'ニズゼルファ',r:'ニズゼルファ',m:'Calasmos — the true final boss',cat:'ストーリー'},
      {w:'なかま',r:'なかま',m:'companion; party member',cat:'ストーリー'},
      {w:'しれん',r:'しれん',m:'trial; ordeal',cat:'ストーリー'},
      {w:'さだめ',r:'さだめ',m:'fate; destiny',cat:'ストーリー'},
      {w:'のろい',r:'のろい',m:'curse',cat:'ストーリー'},
      {w:'ふっかつ',r:'ふっかつ',m:'revival; resurrection; comeback',cat:'ストーリー'},
      {w:'くらやみ',r:'くらやみ',m:'darkness',cat:'ストーリー'},
      {w:'せかいじゅ',r:'せかいじゅ',m:'Yggdrasil — the World Tree',cat:'ストーリー'},
      {w:'いのち',r:'いのち',m:'life; soul',cat:'ストーリー'},
      {w:'きずな',r:'きずな',m:'bond; tie; connection (between characters)',cat:'ストーリー'},
      {w:'いかり',r:'いかり',m:'anger; rage; fury',cat:'ストーリー'},
      {w:'かなしみ',r:'かなしみ',m:'sorrow; sadness; grief',cat:'ストーリー'},
      {w:'よろこび',r:'よろこび',m:'joy; delight; happiness',cat:'ストーリー'},
      {w:'ゆるす',r:'ゆるす',m:'to forgive; to pardon',cat:'ストーリー'},
      {w:'たたかう',r:'たたかう',m:'to fight; to battle; to struggle against',cat:'ストーリー'},
      {w:'たおす',r:'たおす',m:'to defeat; to bring down; to topple',cat:'ストーリー'},
      {w:'すくう',r:'すくう',m:'to save; to rescue; to help',cat:'ストーリー'},
      {w:'あきらめない',r:'あきらめない',m:'don\'t give up; refuse to quit',cat:'ストーリー'},
      {w:'まさか',r:'まさか',m:'no way; surely not; I can\'t believe it',cat:'ストーリー'},
      {w:'おうこく',r:'おうこく',m:'kingdom',cat:'ストーリー'},
      {w:'じょうけん',r:'じょうけん',m:'castle (palace)',cat:'ストーリー'},
      {w:'たびびと',r:'たびびと',m:'traveler; wanderer',cat:'ストーリー'},
      {w:'ぼうけん',r:'ぼうけん',m:'adventure',cat:'ストーリー'},
      {w:'きせき',r:'きせき',m:'miracle',cat:'ストーリー'},
      {w:'へいわ',r:'へいわ',m:'peace',cat:'ストーリー'},
      // ── しょくぎょう ─────────────────────────────────────────────────
      {w:'けんし',r:'けんし',m:'swordsman (Erik\'s base class)',cat:'しょくぎょう'},
      {w:'まほうつかい',r:'まほうつかい',m:'mage (Veronica\'s class)',cat:'しょくぎょう'},
      {w:'そうりょ',r:'そうりょ',m:'priest; cleric (Serena\'s class)',cat:'しょくぎょう'},
      {w:'どうぐし',r:'どうぐし',m:'gadgeteer; item specialist (Sylvando)',cat:'しょくぎょう'},
      {w:'ぶき',r:'ぶき',m:'weapon',cat:'しょくぎょう'},
      {w:'よろい',r:'よろい',m:'armor',cat:'しょくぎょう'},
      {w:'たて',r:'たて',m:'shield',cat:'しょくぎょう'},
      {w:'けん',r:'けん',m:'sword',cat:'しょくぎょう'},
      {w:'ヤリ',r:'ヤリ',m:'spear',cat:'しょくぎょう'},
      {w:'ムチ',r:'ムチ',m:'whip (Jade\'s weapon)',cat:'しょくぎょう'},
      {w:'ブーメラン',r:'ブーメラン',m:'boomerang (Erik\'s weapon)',cat:'しょくぎょう'},
      {w:'つえ',r:'つえ',m:'staff; cane (mage weapon)',cat:'しょくぎょう'},
      {w:'スキルパネル',r:'スキルパネル',m:'skill panel (character growth board)',cat:'しょくぎょう'},
      {w:'スキルポイント',r:'スキルポイント',m:'skill points (spent on skill panel)',cat:'しょくぎょう'},
      // ── まち ─────────────────────────────────────────────────────────
      {w:'やどや',r:'やどや',m:'inn — rest to save & recover HP/MP',cat:'まち'},
      {w:'きょうかい',r:'きょうかい',m:'church — save point & resurrect fallen allies',cat:'まち'},
      {w:'どうぐや',r:'どうぐや',m:'item shop',cat:'まち'},
      {w:'ぶきや',r:'ぶきや',m:'weapon shop',cat:'まち'},
      {w:'ぼうぐや',r:'ぼうぐや',m:'armor shop',cat:'まち'},
      {w:'カジノ',r:'カジノ',m:'casino',cat:'まち'},
      {w:'ぎんこう',r:'ぎんこう',m:'bank — item storage',cat:'まち'},
      {w:'さかば',r:'さかば',m:'tavern; bar',cat:'まち'},
      {w:'メダルおうのしろ',r:'メダルおうのしろ',m:'Medal King\'s castle — trade mini medals',cat:'まち'},
      {w:'まち',r:'まち',m:'town; city',cat:'まち'},
      {w:'むら',r:'むら',m:'village',cat:'まち'},
      {w:'しろ',r:'しろ',m:'castle',cat:'まち'},
      {w:'どうくつ',r:'どうくつ',m:'cave; dungeon',cat:'まち'},
      {w:'とう',r:'とう',m:'tower',cat:'まち'},
      {w:'もり',r:'もり',m:'forest',cat:'まち'},
      {w:'こうや',r:'こうや',m:'wilderness; open field',cat:'まち'},
      {w:'みなと',r:'みなと',m:'harbor; port',cat:'まち'},
      {w:'ふね',r:'ふね',m:'ship; boat',cat:'まち'},
      {w:'いずみ',r:'いずみ',m:'spring; fountain (save/heal point)',cat:'まち'},
      {w:'まほうのカギ',r:'まほうのカギ',m:'magic key — unlocks locked doors in towns',cat:'まち'},
      {w:'たからばこ',r:'たからばこ',m:'treasure chest',cat:'まち'},
      {w:'つぼ',r:'つぼ',m:'pot; jar (often contains items)',cat:'まち'},
      {w:'たんす',r:'たんす',m:'dresser; chest of drawers (search for items)',cat:'まち'},
      // ── かいわ ───────────────────────────────────────────────────────
      // Common phrases you will actually read in DQ11 dialogue
      {w:'旅のお方',r:'たびのおかた',m:'"Traveler" — how NPCs address you (polite)',cat:'かいわ'},
      {w:'ようこそ',r:'ようこそ',m:'Welcome!',cat:'かいわ'},
      {w:'お気をつけて',r:'おきをつけて',m:'Please take care; travel safe',cat:'かいわ'},
      {w:'ありがとうございます',r:'ありがとうございます',m:'Thank you very much (polite)',cat:'かいわ'},
      {w:'たのんだぞ',r:'たのんだぞ',m:'I\'m counting on you! I\'m leaving it to you!',cat:'かいわ'},
      {w:'よろしくたのむ',r:'よろしくたのむ',m:'I\'m counting on you (casual/masculine)',cat:'かいわ'},
      {w:'助けてください',r:'たすけてください',m:'Please help me!',cat:'かいわ'},
      {w:'どうかお願いします',r:'どうかおねがいします',m:'Please, I beg you (earnest request)',cat:'かいわ'},
      {w:'〜を探しています',r:'〜をさがしています',m:'I am looking for ~',cat:'かいわ'},
      {w:'〜に行ったことがありますか',r:'〜にいったことがありますか',m:'Have you ever been to ~?',cat:'かいわ'},
      {w:'どこから来たのですか',r:'どこからきたのですか',m:'Where have you come from?',cat:'かいわ'},
      {w:'〜へようこそ',r:'〜へようこそ',m:'Welcome to ~ (greeting on arriving at a place)',cat:'かいわ'},
      {w:'またいつでもどうぞ',r:'またいつでもどうぞ',m:'Please come again anytime',cat:'かいわ'},
      {w:'そうじゃ',r:'そうじゃ',m:'That\'s right; indeed (old man speech — Rab says this constantly)',cat:'かいわ'},
      {w:'〜じゃよ',r:'〜じゃよ',m:'Sentence-ender for old/wise characters (≈ 〜ですよ)',cat:'かいわ'},
      {w:'〜ぞ',r:'〜ぞ',m:'Assertive masculine sentence-ender (≈ "I tell you!")',cat:'かいわ'},
      {w:'〜ですわ',r:'〜ですわ',m:'Refined/noble feminine sentence-ender (Veronica, Jade)',cat:'かいわ'},
      {w:'まさか',r:'まさか',m:'No way…! Surely not…! (shocked disbelief)',cat:'かいわ'},
      {w:'なんと',r:'なんと',m:'What?! / What a ~ ! (exclamation of surprise)',cat:'かいわ'},
      {w:'やはり',r:'やはり',m:'Just as I thought; as expected; after all',cat:'かいわ'},
      {w:'しかし',r:'しかし',m:'However; but (formal contrast)',cat:'かいわ'},
      {w:'それにしても',r:'それにしても',m:'Even so; that said; nevertheless',cat:'かいわ'},
      {w:'いったい',r:'いったい',m:'Just what…? / On earth…? (intensifier in questions)',cat:'かいわ'},
      {w:'〜というわけだ',r:'〜というわけだ',m:'So that\'s why ~; so it means ~; no wonder',cat:'かいわ'},
      {w:'〜にちがいない',r:'〜にちがいない',m:'It must be ~; there\'s no doubt that ~',cat:'かいわ'},
      {w:'世界を救う',r:'せかいをすくう',m:'to save the world',cat:'かいわ'},
      {w:'あきらめるな',r:'あきらめるな',m:'Don\'t give up! (command form)',cat:'かいわ'},
      {w:'おまえにはまだ早い',r:'おまえにはまだはやい',m:'It\'s still too early for you; you\'re not ready yet',cat:'かいわ'},
      {w:'ご無事で',r:'ごぶじで',m:'Please be safe; I hope you\'re alright',cat:'かいわ'},
      {w:'お体に気をつけて',r:'おからだにきをつけて',m:'Please take care of yourself',cat:'かいわ'},
    ]
  }
};
